
SELECT distinct ORG_SOURCE
from APTTUS_DW.PRODUCT."Monthly_Score_Package_Org"	
;

with get_current_of_C1 AS (
        SELECT MAX(EXTRACT_DATE) AS EXTRACT_DATE, ID
        FROM   APTTUS_DW.SNAPSHOTS.ASSET_C1_HISTORY
        WHERE ACTIVITY_DATE <= current_Date()
        group by ID
)
SELECT *
FROM APTTUS_DW.SNAPSHOTS.ASSET_C1_HISTORY A
        INNER JOIN               get_current_of_C1 D
                            ON  A.ID = D.ID
                            AND A.EXTRACT_DATE = D.EXTRACT_DATE  
WHERE ACCOUNTID IN ('0015000001AbjZ6AAJ')
  AND PRODUCT2ID IN ('01t50000005At6nAAC')
  AND ENTITLEMENT_STATUS__C = 'Active'
;  

SELECT ACCOUNTID, ORGID18__C, PRODUCT2ID, ID, MRR_ASSET_MRR__C, QUANTITY, ENTITLEMENT_STATUS__C, START_DATE__C, END_DATE__C  
FROM APTTUS_DW.SF_CONGA1_1.ASSET
WHERE ACCOUNTID IN ('0015000001AbjZ6AAJ') 
  AND PRODUCT2ID IN ('01t50000005At6nAAC')
--  AND ENTITLEMENT_STATUS__C = 'Active'  