SELECT
	CREATEDBYID
	, CREATEDDATE
	, ID
	, ISDELETED
	, LASTMODIFIEDBYID
	, LASTMODIFIEDDATE
	, "NAME"
	, SFFMA__FEATUREPARAMETER__C
	, SFFMA__LICENSE__C
	, SFFMA__VALUE__C
	, SYSTEMMODSTAMP
	, "_SDC_BATCHED_AT"
	, "_SDC_EXTRACTED_AT"
	, "_SDC_RECEIVED_AT"
	, "_SDC_SEQUENCE"
	, "_SDC_TABLE_VERSION"
	, SNAP_LOAD_AT
	, ACTIVITY_DATE
	, EXTRACT_DATE
	, REPORTING_DATE
FROM
	APTTUS_DW.SNAPSHOTS.FMA_VALUES_HISTORY
WHERE  ACTIVITY_DATE > '2020-09-01'	
ORDER BY SFFMA__LICENSE__C 
    , SFFMA__FEATUREPARAMETER__C
	, REPORTING_DATE
	;
-- example of activity date repeating
select *
FROM APTTUS_DW.SNAPSHOTS.FMA_VALUES_HISTORY
WHERE
SFFMA__LICENSE__C IN ('a025000000gYtWsAAK') AND
SFFMA__FEATUREPARAMETER__C IN ('a9v1T0000007o67QAA')
;
