select 
       A.CONGA_ENFORCE_LMA__C
     , A.CONGA_ENFORCE_USER_MANAGEMENT__C                
     , A.ORG_SEATS_OVERRIDE
     , A.LICENSE_SEAT_TYPE AS LMA_LICENSE_SEAT_TYPE        
     , A.LMA_ORIGINAL_SEATS
     , A.SEATS AS REPORTED_SEATS
     , A.USED_LICENSES
     , A.INSTALL_DATE 
     , A.CUSTOMER_ORG
     , A.PRODUCT
     , A.LICENSE_ID
     , A.ACCOUNT_ID
     , C.ACCOUNT_NAME 
     , A.LAST_ACTIVITY_DATE
from                     APTTUS_DW.PRODUCT.LMA_LIC_PRODUCTLINE_CURRENT A
LEFT OUTER JOIN          APTTUS_DW.SF_PRODUCTION."Account_C2" C
                  ON  UPPER(A.CRM_SOURCE) = UPPER(C.SOURCE)
                  AND A.ACCOUNT_ID = C.ACCOUNTID_18__C 
where A.ORG_SEATS_OVERRIDE IN ('REPLACED', 'SAME')
order by 3, 13
;

SELECT COUNT(*), ORG_SEATS_OVERRIDE
from APTTUS_DW.PRODUCT.LMA_LIC_PRODUCTLINE_CURRENT
group by ORG_SEATS_OVERRIDE
;