SELECT PACKAGEID, PACKAGENAME, PRODUCT, PRODUCTFAMILY, null as MARKT_ENG_NAME 
FROM APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_FAMILY
UNION
SELECT P.ID as PACKAGEID
     , P.NAME AS PACKAGENAME
     , null as PRODUCT 
     , null as PRODUCTFAMILY
     , L.PRODUCT_LINE as MARKT_ENG_NAME
     
FROM                   APTTUS_DW.SF_CONGA1_1.SFLMA__PACKAGE__C P
LEFT OUTER JOIN        APTTUS_DW.PRODUCT.LICENSE_PACKAGE_PRODUCT_LINE L
                 ON P.NAME = L.PACKAGE_NAME
Order by 5 desc, 4, 2
;


select PRODUCT_LINE__C
     , PRODUCTCODE
     , FAMILY
     , LOB__C
     , NAME
     , DESCRIPTION 
from  APTTUS_DW.SF_CONGA1_0.PRODUCT2
where isactive = true
order by product_line__C

; 
