--SELECT CURRENT_ROLE();

--create table APTTUS_DW.PRODUCT.PIPELINED_MONTHLY_ACTIVITY_TESTING
--as select * from APTTUS_DW.PRODUCT.PIPELINED_MONTHLY_ACTIVITY 
--;
--INSERT INTO APTTUS_DW.PRODUCT.PRODUCT_METRICS_RUN_CONTROL (RUN_FOR_MONTH, OPERATOR, EXECUTION_TIME, STATUS, PROC_OR_STEP)
SELECT date_trunc('MONTH',dateadd(month, -1, CURRENT_DATE())) AS RUN_FOR_MONTH -- USE THIS TO MANUALLY OVERRIDE THE RUN DATE OTHERWISE IT WILL DEFAULT
     , CURRENT_USER() AS OPERATOR
     , CONVERT_TIMEZONE('UTC',CURRENT_TIMESTAMP()) AS EXECUTION_TIME
     , 'Incomplete' AS STATUS
     , 'FILL_SIGN_MONTHLY_ACTIVITY' as PROC_OR_STEP
;
--DELETE from APTTUS_DW.PRODUCT.PIPELINED_MONTHLY_ACTIVITY_TESTING
where  PRODUCT_LINE = 'Conga Sign'
  and ACTIVITY_MONTH_DATE = '2020-09-01'
;

MERGE INTO APTTUS_DW.PRODUCT.PIPELINED_MONTHLY_ACTIVITY_TESTING TARGET_T 
using ( 
WITH CONTROL_LAST AS (
        SELECT MAX(EXECUTION_TIME) AS RECENT_EXEC 
        FROM APTTUS_DW.PRODUCT.PRODUCT_METRICS_RUN_CONTROL
        WHERE PROC_OR_STEP = 'FILL_SIGN_MONTHLY_ACTIVITY' 
)
--
, DATE_FROM_CONTROL AS (
                SELECT RUN_FOR_MONTH
                FROM APTTUS_DW.PRODUCT.PRODUCT_METRICS_RUN_CONTROL
                WHERE EXECUTION_TIME = (SELECT RECENT_EXEC FROM CONTROL_LAST)
                  AND PROC_OR_STEP = 'FILL_SIGN_MONTHLY_ACTIVITY'
)
--
, SET_DATE_RANGE AS (
        SELECT date_trunc('MONTH', (SELECT RUN_FOR_MONTH FROM DATE_FROM_CONTROL)) AS COMPLETED_MONTH
             , YEAR(COMPLETED_MONTH) AS REPORT_YEAR
             , MONTH(COMPLETED_MONTH) AS REPORT_MONTH 
             , COMPLETED_MONTH AS REPORT_DATE
)
, EDIT_SENT_EVENTS AS (
        SELECT SYSTEM_TYPE AS ORG_SOURCE
             , CASE
                 WHEN SYSTEM_TYPE <> 'COLLABORATE'
                   THEN SYSTEM_ID 
                 WHEN SYSTEM_TYPE = 'COLLABORATE'
                  AND SYSTEM_ID  LIKE 'collaborate-production-%'
                   THEN SUBSTRING(SYSTEM_ID ,24)
                else SYSTEM_ID         
               END AS SOURCE_ORG_ID
             , YEAR(REQUEST_TIMESTAMP) AS ACTIVITY_YEAR
             , MONTH(REQUEST_TIMESTAMP) AS ACTIVITY_MONTH
             , SENDER_ID
             , CASE 
                 WHEN SYSTEM_ENVIRONMENT <> 'SANDBOX'
                   THEN 0::BOOLEAN
                 ELSE 1::BOOLEAN
               END AS IS_SANDBOX_EDITION                      
        FROM APTTUS_DW.SF_PRODUCTION.SIGN_SIGNINGREQUEST_EVENT 
        WHERE EVENT_TYPE = 'SENT'
          and Year(REQUEST_TIMESTAMP) = (select REPORT_YEAR from SET_DATE_RANGE)
          and Month(REQUEST_TIMESTAMP) = (select REPORT_MONTH from SET_DATE_RANGE)
)        
, GROUP_EVENTS AS (
        SELECT ORG_SOURCE
             , SOURCE_ORG_ID
             , ACTIVITY_YEAR
             , ACTIVITY_MONTH
             , COUNT(*) AS ACTIVITY_COUNT
             , COUNT(DISTINCT SENDER_ID) AS UNIQUE_USERS
             , BOOLAND_AGG(IS_SANDBOX_EDITION) AS IS_SANDBOX_EDITION                      
        FROM EDIT_SENT_EVENTS
        GROUP BY ORG_SOURCE
             , SOURCE_ORG_ID
             , ACTIVITY_YEAR
             , ACTIVITY_MONTH               
)
        SELECT A.ORG_SOURCE
             , A.SOURCE_ORG_ID
             , A.ACTIVITY_YEAR
             , A.ACTIVITY_MONTH
             , B."Date" as ACTIVITY_MONTH_DATE 
             , 'Conga Sign' as PRODUCT_LINE             
             , A.ACTIVITY_COUNT
             , A.UNIQUE_USERS
             , A.IS_SANDBOX_EDITION    
        FROM                   GROUP_EVENTS A      
        INNER JOIN             APTTUS_DW.SF_PRODUCTION."DateDim" B
                     ON  A.ACTIVITY_YEAR = B."Calendar_Year"
                     AND A.ACTIVITY_MONTH = B."Calendar_Month"
                     AND B."Day" = 1 
) SOURCE_T
    ON  TARGET_T.ORG_SOURCE = SOURCE_T.ORG_SOURCE
    AND TARGET_T.SOURCE_ORG_ID = SOURCE_T.SOURCE_ORG_ID
    AND TARGET_T.ACTIVITY_MONTH_DATE = SOURCE_T.ACTIVITY_MONTH_DATE
    AND TARGET_T.PRODUCT_LINE = SOURCE_T.PRODUCT_LINE
WHEN NOT MATCHED THEN 
INSERT 
(              ORG_SOURCE
             , SOURCE_ORG_ID
             , ACTIVITY_YEAR
             , ACTIVITY_MONTH
             , ACTIVITY_MONTH_DATE 
             , PRODUCT_LINE
             , ACTIVITY_COUNT
             , UNIQUE_USERS
             , IS_SANDBOX_EDITION
             , ACTIVITY_ACCOUNT_ID
             , ACTIVITY_ACCOUNT_NAME
) VALUES
(              SOURCE_T.ORG_SOURCE
             , SOURCE_T.SOURCE_ORG_ID
             , SOURCE_T.ACTIVITY_YEAR
             , SOURCE_T.ACTIVITY_MONTH
             , SOURCE_T.ACTIVITY_MONTH_DATE 
             , SOURCE_T.PRODUCT_LINE
             , SOURCE_T.ACTIVITY_COUNT
             , SOURCE_T.UNIQUE_USERS
             , SOURCE_T.IS_SANDBOX_EDITION 
             , null
             , null 
)                      