describe procedure "APTTUS_DW"."SF_PRODUCTION"."PRO_S3_LOADING"();


SELECT * FROM @APTTUS_DW.SF_PRODUCTION.SIGN_SIGNINGREQUEST_EVENT_S3;


COPY INTO APTTUS_DW.SF_PRODUCTION.SIGN_SIGNINGREQUEST_EVENT FROM (SELECT * FROM @APTTUS_DW.SF_PRODUCTION.SIGN_SIGNINGREQUEST_EVENT_S3 t) ON_ERROR = CONTINUE;

show procedures IN SCHEMA SF_PRODUCTION;
show tasks IN SCHEMA SF_PRODUCTION;

