select count(*), ACTIVITY_MONTH_DATE, PACKAGE_NAMESPACE
from APTTUS_DW.PRODUCT.COMPOSER_MONTHLY_ACTIVITY
group by  ACTIVITY_MONTH_DATE, PACKAGE_NAMESPACE
order by ACTIVITY_MONTH_DATE desc, PACKAGE_NAMESPACE
;