
SELECT * 
FROM APTTUS_DW.PRODUCT.LMA_LIC_PRODUCTLINE_CURRENT
WHERE CUSTOMER_ORG = '00Di0000000ZbEdEAK'
;

SELECT *
FROM APTTUS_DW.SF_CONGA1_0.SALESFORCE_ORG__C
WHERE ORG_ID__C = '00Di0000000ZbEdEAK'
;

SELECT ACCOUNTID__C, ORG_ID__C, SALESFORCE_ACCOUNT_ID__C AS CUSTOMER_ORG,  LICENSED_SEATS__C, CONGA_LICENSES__C, *
FROM APTTUS_DW.SF_CONGA1_0.SALESFORCE_ORG__C
WHERE ACCOUNTID__C IN ('0015000001D5IGjAAN','0015000000qIyu9AAC')
  AND ORG_TYPE__C = 'Production'

;

SELECT *
FROM APTTUS_DW.SF_CONGA1_0.SFLMA__LICENSE__C
--FROM APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_CURRENT
--WHERE CUSTOMER_ORG_ID__C = '00Di0000000ZbEdEAK'
--WHERE ID = 'a025000000RLnXzAAL'
WHERE NAME = 'L-17264'
;

SELECT A.ACCOUNTID__C
     , A.SALESFORCE_ACCOUNT_ID__C AS CUSTOMER_ORG_18
     , A.SALESFORCE_ORG_ID_15__C AS ORG_15
     , A.COMPOSER_LICENSE__C
     , A.LICENSED_SEATS__C
     , A.CONGA_LICENSES__C
     , B.SFLMA__PACKAGE__C AS PACKAGE_ID 
     , B.SFLMA__LICENSED_SEATS__C
     , B.SFLMA__SEATS__C
     , B.ID AS LICENSE_ID
     , B.NAME AS LICENSE_NAME
     , P.PRODUCTFAMILY
     , P.PRODUCT                                 -- replaces C1 product_line but will still match Assets product_line 
     , P.PACKAGENAME                             AS PACKAGE_NAME                         
     , B.PACKAGE_NAMEFX__C                       AS PACKAGE_NAMEFX     
FROM                         APTTUS_DW.SF_CONGA1_0.SALESFORCE_ORG__C A
LEFT OUTER JOIN              APTTUS_DW.SF_CONGA1_0.SFLMA__LICENSE__C B         
                    ON   A.SALESFORCE_ACCOUNT_ID__C = B.CUSTOMER_ORG_ID__C
                    AND  A.COMPOSER_LICENSE__C = B.ID
                    --AND  B.PACKAGE_NAMEFX__C = 'Conga Composer'
LEFT OUTER JOIN              APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_FAMILY P
                   ON B.SFLMA__PACKAGE__C = P.PACKAGEID               
WHERE A.ORG_TYPE__C = 'Production' AND 
      A.ACCOUNTID__C IN ('0015000001D5IGjAAN','0015000000qIyu9AAC')
;    

WITH joinAndCase AS ( 
	SELECT A.ACCOUNTID__C
	     , A.SALESFORCE_ACCOUNT_ID__C AS CUSTOMER_ORG_18
	     , A.SALESFORCE_ORG_ID_15__C AS ORG_15
	     , A.COMPOSER_LICENSE__C
	     , A.LICENSED_SEATS__C
	     , A.CONGA_LICENSES__C
	     , B.PACKAGE_ID 
	     , B.PACKAGE_NAME
	     , B.LICENSE_SEAT_TYPE
	     , B.SEATS
	     , B.LICENSE_ID
	     , B.LICENSE_NAME
	     , CASE 
	         WHEN A.LICENSED_SEATS__C = -1 
	          AND A.CONGA_LICENSES__C > 0 -- both SITE and Seat count 
	            THEN 1::BOOLEAN
	         WHEN A.LICENSED_SEATS__C > -1 
	          AND A.LICENSED_SEATS__C <> A.CONGA_LICENSES__C -- seat counts don't agree
	            THEN 1::BOOLEAN
	         WHEN B.LICENSE_ID IS NULL 
	            THEN 1::BOOLEAN
	         WHEN A.LICENSED_SEATS__C = -1 
	          AND B.LICENSE_SEAT_TYPE = 'Seats'
	            THEN 1::BOOLEAN
	         WHEN A.LICENSED_SEATS__C > -1 AND B.LICENSE_SEAT_TYPE = 'Site'
	            THEN 1::BOOLEAN
	         WHEN A.LICENSED_SEATS__C > 0
	          AND A.LICENSED_SEATS__C <> B.SEATS  
	            THEN 1::BOOLEAN
	       ELSE 0::BOOLEAN
	      END AS LICENSE_MISMATCH 
	FROM                         APTTUS_DW.SF_CONGA1_0.SALESFORCE_ORG__C A
	LEFT OUTER JOIN              APTTUS_DW.PRODUCT.LMA_LIC_PRODUCTLINE_CURRENT B         
	                    ON   A.SALESFORCE_ACCOUNT_ID__C = B.CUSTOMER_ORG
	                    AND  A.COMPOSER_LICENSE__C = B.LICENSE_ID
	                    AND  B.PRODUCT = 'Conga Composer'
	WHERE A.ORG_TYPE__C = 'Production'
)
SELECT * 
FROM joinAndCase
WHERE LICENSE_MISMATCH = TRUE
;
