-- APTTUS_DW.SF_PRODUCTION.C2_QUOTE_LINE source
-- 1.25.21 -- Ryan Created Quote_Line View

CREATE OR REPLACE VIEW APTTUS_DW.SF_PRODUCTION.C2_QUOTE_LINE 
COMMENT = 'all purpose Quote_Line view for Blended Conga2.0
'

AS
SELECT 
   'Conga1.0' AS CRM_SOURCE
   ,ID AS QUOTE_ID
FROM   APTTUS_DW.SNAPSHOTS.QUOTELINE_C1_CURRENT

UNION

SELECT 
   'Apttus1.0' AS CRM_SOURCE   
  , ID AS QUOTE_ID
FROM APTTUS_DW.SNAPSHOTS.PROPOSAL_LINEITEM_A1_CURRENT
;