DROP TABLE APTTUS_DW.PRODUCT.ACCOUNT_ASSET_PRODUCT_PERC_HISTORY ;

This table no longer used
--CREATE TABLE  APTTUS_DW.PRODUCT.ACCOUNT_ASSET_PRODUCT_PERC_HISTORY 
        (ACCOUNTID VARCHAR(16777216)
        , CRM VARCHAR(250)
        , PRODUCT VARCHAR(16777216)
        , REPORT_DATE DATE
        , QUANTITY INTEGER
        , ORG_COUNT INTEGER
        , PRODUCT_ID_COUNT INTEGER
        , PRODUCT_ACV NUMBER(19,2)
        , ACV_ON_ACCOUNT NUMBER(19,2)
        , PRODUCT_ACV_PERCENTAGE NUMBER(19,2)
        , POSITIVE_ACCOUNT_ACV NUMBER(19,2)
);

select * from APTTUS_DW.PRODUCT.ACCOUNT_ASSET_PRODUCT_PERC_HISTORY;
 