DROP TABLE APTTUS_DW.PRODUCT.ACCOUNT_ASSET_PRODUCT_HISTORY ;
--DELETE FROM APTTUS_DW.PRODUCT.ACCOUNT_ASSET_PRODUCT_HISTORY ;

CREATE TABLE APTTUS_DW.PRODUCT.ACCOUNT_ASSET_PRODUCT_HISTORY 
        (ACCOUNTID VARCHAR(16777216)
        , CRM VARCHAR(250)
        , ASSET_ID VARCHAR(16777216)
        , ASSET_NAME VARCHAR(16777216)
        , REPORT_DATE DATE
        , PRODUCT_ID VARCHAR(16777216)
        , PRODUCT_NAME VARCHAR(16777216)
        , PRODUCT VARCHAR(16777216)
        , PRODUCT_LINE VARCHAR(16777216)
        , PRODUCT_FAMILY VARCHAR(16777216)
        , PRODUCT2_LINE VARCHAR(16777216)
        , ORG_SOURCE VARCHAR(16777216)                  
        , CUSTOMER_ORG VARCHAR(16777216)
        , QUANTITY INTEGER
        , ACV NUMBER(19,2) -- asset level ACV     
        , ACV_ON_ACCOUNT NUMBER(19,2)
        , ASSET_STATUS VARCHAR(16777216)
        , START_DATE TIMESTAMP_TZ
        , END_DATE TIMESTAMP_TZ
        , ORIGINAL_CURRENCY VARCHAR(16777216)
        , ORIGINAL_ACV NUMBER(29,2)
);

select * from APTTUS_DW.PRODUCT.ACCOUNT_ASSET_PRODUCT_HISTORY;

select COUNT(*), REPORT_DATE 
from APTTUS_DW.PRODUCT.ACCOUNT_ASSET_PRODUCT_HISTORY
GROUP BY REPORT_DATE
; 