DROP VIEW APTTUS_DW.PRODUCT.CONTRACTS_CLIENT_CONFIGURATION_CURRENT;

CREATE OR REPLACE VIEW APTTUS_DW.PRODUCT.CONTRACTS_CLIENT_CONFIGURATION_CURRENT 
COMMENT = 'Get the most current data about Contracts Company'
AS 
with get_last as (
        select USER_COMPANY_UUID, MAX(REPORT_DATE) as LAST_REPORT_DATE
        from APTTUS_DW.SF_PRODUCTION.CONTRACTS_CLIENT_CONFIGURATION
        group by USER_COMPANY_UUID
)
SELECT A.USER_COMPANY_UUID 
       , COMPANY_NAME 
       , DATABASE_NAME 
       , ENVIRONMENT 
       , REGION 
       , REPORT_DATE 
       , PORTAL_ENABLED 
       , SUPPLIER_REGISTRATION_ENABLED 
       , DELETED 
       , INBOUND_EMAIL_PROCESSING_ENABLED 
       , ESIGNATURE_ENABLED 
       , ESIGNATURE_PROVIDER 
       , BI_TOOLBOX_ENABLED 
       , BULK_DATA_UPLOAD_TOOL_ENABLED 
       , CLAUSE_MANAGEMENT_ENABLED 
       , CONGA_PLATFORM_ENABLED 
       , ELASTICSEARCH_ENABLED 
       , OCR_ENABLED 
       , OCR_CREATE_SEARCHABLE_DOCUMENT_ENABLED 
       , API_ENABLED 
       , API_CALL_LIMIT 
FROM         APTTUS_DW.SF_PRODUCTION.CONTRACTS_CLIENT_CONFIGURATION A
INNER JOIN   get_last B
           ON A.USER_COMPANY_UUID = B.USER_COMPANY_UUID 
           AND A.REPORT_DATE = B.LAST_REPORT_DATE