
--CREATE TABLE APTTUS_DW.PRODUCT.FMA_DAILY_ACTIVITY
(     SOURCE_ORG_ID
    , ACTIVITY_DATE 
    , PRODUCT_LINE
    , LICENSE_ID 
    , ACTIVITY_COUNT 
    , UNIQUE_USERS
)            
AS
        SELECT SOURCE_ORG_ID
             , ACTIVITY_DATE 
             , PRODUCT_LINE
             , LICENSE_ID
             , CASE 
                 WHEN PRODUCT_LINE = 'Conga Contracts for Salesforce'
                   THEN CONTRACTS4SF_DAILY_ACTIVITY
                ELSE ROLLING_ACTIVITY_COUNT
               END AS ACTIVITY_COUNT
             , ROLLING_ACTIVE_USERS as UNIQUE_USERS 
        FROM APTTUS_DW.PRODUCT."FMA_Rolling_Activity" 
;        


MERGE INTO APTTUS_DW.PRODUCT.FMA_DAILY_ACTIVITY TARGET_T 
using (
        SELECT SOURCE_ORG_ID
             , ACTIVITY_DATE 
             , PRODUCT_LINE
             , LICENSE_ID
             , CASE 
                 WHEN PRODUCT_LINE = 'Conga Contracts for Salesforce'
                   THEN CONTRACTS4SF_DAILY_ACTIVITY
                ELSE ROLLING_ACTIVITY_COUNT
               END AS ACTIVITY_COUNT
             , ROLLING_ACTIVE_USERS as UNIQUE_USERS 
        FROM APTTUS_DW.PRODUCT."FMA_Rolling_Activity" 
        WHERE ACTIVITY_DATE > CURRENT_DATE() - 10   
) SOURCE_T
    ON TARGET_T.SOURCE_ORG_ID = SOURCE_T.SOURCE_ORG_ID
    AND TARGET_T.ACTIVITY_DATE = SOURCE_T.ACTIVITY_DATE
    AND TARGET_T.PRODUCT_LINE = SOURCE_T.PRODUCT_LINE
    AND TARGET_T.LICENSE_ID = SOURCE_T.LICENSE_ID
WHEN NOT MATCHED THEN 
INSERT 
(     SOURCE_ORG_ID
    , ACTIVITY_DATE 
    , PRODUCT_LINE
    , LICENSE_ID 
    , ACTIVITY_COUNT 
    , UNIQUE_USERS
) VALUES ( 
      SOURCE_T.SOURCE_ORG_ID
    , SOURCE_T.ACTIVITY_DATE 
    , SOURCE_T.PRODUCT_LINE
    , SOURCE_T.LICENSE_ID 
    , SOURCE_T.ACTIVITY_COUNT 
    , SOURCE_T.UNIQUE_USERS
)    