CREATE TABLE APTTUS_DW.PRODUCT.LICENSE_PACKAGE_PRODUCT_LINE_TWO
as
select PACKAGE_NAME, PRODUCT_LINE, CRM, LMA_PACKAGE_ID, PACKAGE_ID, MANAGED_PACKAGE_NAMESPACE
from APTTUS_DW.PRODUCT.LICENSE_PACKAGE_PRODUCT_LINE_C2
where CRM = 'Conga1.0' 
  and LMA_PACKAGE_ID is not null
;
  