--DROP TABLE APTTUS_DW.PRODUCT.LMA_LIC_PACKAGE_WEEKLY;

CREATE TABLE APTTUS_DW.PRODUCT.LMA_LIC_PACKAGE_WEEKLY  --lma_lic_package_weekly 
  ( 
     customer_org                VARCHAR(16777216), 
     product                     VARCHAR(16777216), 
     productfamily               VARCHAR(16777216), 
     reporting_date              DATE, 
     customer_org_15             VARCHAR(16777216), 
     customer_org_18             VARCHAR(16777216), 
     package_name                VARCHAR(16777216), 
     active_package_list         VARCHAR(16777216), 
     package_id                  VARCHAR(16777216), 
     package_version_id          VARCHAR(16777216), 
     org_package                 VARCHAR(16777216), 
     active_seat_type            VARCHAR(16777216), 
     primary_row_seat_type       VARCHAR(16777216), 
     active_license_count        INTEGER, 
     active_licenses_wseats      INTEGER, 
     nonprod_license_count       INTEGER, 
     sandbox_license_count       INTEGER, 
     active_seats                INTEGER, 
     active_used                 INTEGER, 
     nonprod_seats               INTEGER, 
     nonprod_used                INTEGER, 
     sandbox_seats               INTEGER, 
     sandbox_used                INTEGER, 
     primary_row_seats           INTEGER, 
     primary_row_used            INTEGER, 
     longest_active_install      INTEGER, 
     active_license_id_list      VARCHAR(16777216), 
     nonprod_license_id_list     VARCHAR(16777216), 
     sandbox_license_id_list     VARCHAR(16777216), 
     status                      VARCHAR(16777216), 
     org_status                  VARCHAR(16777216), 
     account_id                  VARCHAR(16777216), 
     account_name                VARCHAR(16777216), 
     is_sandbox                  BOOLEAN, 
     install_date                TIMESTAMPTZ, 
     uninstall_date              TIMESTAMPTZ, 
     months_installed            INTEGER, 
     install_date_string         VARCHAR(16777216), 
     expiration_date             DATE, 
     expiration_date_string      VARCHAR(16777216), 
     last_activity_date          DATE, 
     suspend_account_bool        BOOLEAN, 
     account_suspended_reason    VARCHAR(16777216), 
     license_name                VARCHAR(16777216), 
     c1_production_bool          BOOLEAN, 
     primary_license_id          VARCHAR(16777216), 
     predicted_package_namespace VARCHAR(16777216), 
     crm_source                  VARCHAR(16777216), 
     product_line                VARCHAR(16777216) 
  ); 

--DROP TABLE APTTUS_DW.PRODUCT.LMA_LIC_PACKAGE_MONTHLY;
  
CREATE TABLE APTTUS_DW.PRODUCT.LMA_LIC_PACKAGE_MONTHLY
  ( 
     customer_org                VARCHAR(16777216), 
     product                     VARCHAR(16777216), 
     productfamily               VARCHAR(16777216), 
     reporting_date              DATE, 
     customer_org_15             VARCHAR(16777216), 
     customer_org_18             VARCHAR(16777216), 
     package_name                VARCHAR(16777216), 
     active_package_list         VARCHAR(16777216), 
     package_id                  VARCHAR(16777216), 
     package_version_id          VARCHAR(16777216), 
     org_package                 VARCHAR(16777216), 
     active_seat_type            VARCHAR(16777216), 
     primary_row_seat_type       VARCHAR(16777216), 
     active_license_count        INTEGER, 
     active_licenses_wseats      INTEGER, 
     nonprod_license_count       INTEGER, 
     sandbox_license_count       INTEGER, 
     active_seats                INTEGER, 
     active_used                 INTEGER, 
     nonprod_seats               INTEGER, 
     nonprod_used                INTEGER, 
     sandbox_seats               INTEGER, 
     sandbox_used                INTEGER, 
     primary_row_seats           INTEGER, 
     primary_row_used            INTEGER, 
     longest_active_install      INTEGER, 
     active_license_id_list      VARCHAR(16777216), 
     nonprod_license_id_list     VARCHAR(16777216), 
     sandbox_license_id_list     VARCHAR(16777216), 
     status                      VARCHAR(16777216), 
     org_status                  VARCHAR(16777216), 
     account_id                  VARCHAR(16777216), 
     account_name                VARCHAR(16777216), 
     is_sandbox                  BOOLEAN, 
     install_date                TIMESTAMPTZ, 
     uninstall_date              TIMESTAMPTZ, 
     months_installed            INTEGER, 
     install_date_string         VARCHAR(16777216), 
     expiration_date             DATE, 
     expiration_date_string      VARCHAR(16777216), 
     last_activity_date          DATE, 
     suspend_account_bool        BOOLEAN, 
     account_suspended_reason    VARCHAR(16777216), 
     license_name                VARCHAR(16777216), 
     c1_production_bool          BOOLEAN, 
     primary_license_id          VARCHAR(16777216), 
     predicted_package_namespace VARCHAR(16777216), 
     crm_source                  VARCHAR(16777216), 
     product_line                VARCHAR(16777216) 
  );   