
--DROP VIEW APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_INTEREST_FAMILY;

CREATE OR REPLACE VIEW APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_INTEREST_FAMILY
COMMENT = 'Join MASTER_PRODUCT_BY_INTEREST to MASTER_PRODUCT_HIERARCHY'
AS  
        SELECT A.PRODUCT_INTEREST
             , A.PRODUCT
             , B.PRODUCT_LINE
             , B.PRODUCT_FAMILY
        FROM                 APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_BY_INTEREST A
        INNER JOIN           APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_HIERARCHY B   
                      ON A.PRODUCT = B.PRODUCT
;                   