--DROP TABLE APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_HIERARCHY;

CREATE TABLE APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_BY_PRODUCTID
        (  PRODUCT_ID        VARCHAR(16777216)  
         , PRODUCT1          VARCHAR(16777216)
        )
; 

ALTER TABLE APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_BY_PRODUCTID rename column PRODUCT1 to PRODUCT;