--DROP TABLE APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_HIERARCHY;

CREATE TABLE APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_HIERARCHY
        ( PRODUCT1          VARCHAR(16777216)
        , PRODUCT_LINE     VARCHAR(16777216)
        , PRODUCT_FAMILY   VARCHAR(16777216)
        , PRODUCT_COLOR_CODE INTEGER
        )
; 

ALTER TABLE APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_HIERARCHY rename column PRODUCT1 to PRODUCT;
ALTER TABLE APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_HIERARCHY add column PRODUCT_COLOR_CODE INTEGER;