PUT file://C:\Users\greg.wilson\Documents\C_Projects\ToSnowFlake\C1_MASTER_PRODUCT_FAMILY.csv @~
;

LIST @~;

CREATE TABLE APTTUS_DW.PRODUCT.C1_MASTER_PRODUCT_FAMILY 
        ( PACKAGEID VARCHAR(16777216)
        , PACKAGENAME VARCHAR(16777216)
        , PRODUCT VARCHAR(16777216)
        , PRODUCTFAMILY VARCHAR(16777216)
        )
;

;
COPY INTO "APTTUS_DW"."PRODUCT"."C1_MASTER_PRODUCT_FAMILY" 
FROM @~/C1_MASTER_PRODUCT_FAMILY.csv.gz
FILE_FORMAT = ( 
TYPE = CSV 
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
DATE_FORMAT = 'YYYY-MM-DD'
)
;

INSERT INTO APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_FAMILY (PACKAGEID, PACKAGENAME, PRODUCT, PRODUCTFAMILY) 
SELECT PACKAGEID, PACKAGENAME, PRODUCT, PRODUCTFAMILY FROM APTTUS_DW.PRODUCT.C1_MASTER_PRODUCT_FAMILY 
;

INSERT INTO APTTUS_DW.SF_PRODUCTION.MASTER_PRODUCT_FAMILY (PACKAGEID, PACKAGENAME, PRODUCT, PRODUCTFAMILY) 
SELECT PACKAGEID, PACKAGENAME, PRODUCT, PRODUCTFAMILY FROM APTTUS_DW.PRODUCT.C1_MASTER_PRODUCT_FAMILY
WHERE PACKAGEID IN ('a015000000A58RtAAJ','a015000000enhmCAAQ')
;