CREATE TABLE APTTUS_DW.PRODUCT.MONTHLY_AA_ACTIVITY_SCORES
  ( 
     CRM                               VARCHAR(16777216), 
     ORGANIZATION_ID                   VARCHAR(16777216), 
     REPORT_YEAR                       NUMBER, 
     REPORT_MONTH                      NUMBER, 
     REPORT_DATE                       DATE, 
     LAST_ACTIVITY_MONTH               DATE, 
     PACKAGE_ID                        VARCHAR(16777216), 
     MANAGED_PACKAGE_NAMESPACE         VARCHAR(16777216),
     ACTIVITY_COUNT                    NUMBER, 
     ACTIVITY_P3_INTERVAL              NUMBER(38, 3), 
     ADOPTION_ACTIVITY_UI              NUMBER(38, 3), 
     ACTIVITY_DIRECTION                VARCHAR(2), 
     HISTORIC_MEDIAN_ACTIVITY_INTERVAL NUMBER(38, 3), 
     HISTORIC_ACTIVITY_DIRECTION       VARCHAR(2), 
     CY_ACTIVITY                       NUMBER, 
     PY_ACTIVITY                       NUMBER, 
     YOY_ACTIVITY_INTERVAL             NUMBER(38, 3), 
     YOY_ACTIVITY_DIRECTION            VARCHAR(2), 
     ACTIVITY_RANGE_SCORE              NUMBER(38, 3), 
     UNIQUE_USERS                      NUMBER, 
     USER_P3_INTERVAL                  NUMBER(38, 3), 
     ADOPTION_USER_UI                  NUMBER(38, 3), 
     USER_DIRECTION                    VARCHAR(2), 
     HISTORIC_MEDIAN_USER_INTERVAL     NUMBER(38, 3), 
     HISTORIC_USER_DIRECTION           VARCHAR(2), 
     CY_USERS                          NUMBER, 
     PY_USERS                          NUMBER, 
     YOY_USERS_INTERVAL                NUMBER(38, 3), 
     YOY_USERS_DIRECTION               VARCHAR(2), 
     USERS_RANGE_SCORE                 NUMBER(38, 3), 
     TOTAL_MONTHS_OF_ACTIVITY          NUMBER 
  ); 