unload ('select * from dim_license')   
to 's3://bi-prod-integrations/unloadcopy/dim_license_20200930.csv' 
iam_role 'arn:aws:iam::637289251939:role/RedshiftS3AccessRole'
CSV
header
parallel off
;

--- no don't drop it DROP TABLE APTTUS_DW.PRODUCT.APTTUS_DW.PRODUCT.BEST_SORTED_LICENSES_HISTORY_RSH; 

CREATE TABLE APTTUS_DW.PRODUCT.DIM_LICENSE_RSH_20200930 (
LICENSE_ID INTEGER,
BA VARCHAR,
BA_EMAIL VARCHAR,
CC4SF_EDITION VARCHAR,
CONTACT VARCHAR,
CREATED_DATE TIMESTAMP,
EXPIRATION DATE,
EXPIRATION_DATE_STRING VARCHAR,
INSTALL_DATE DATE,
IS_SANDBOX BOOLEAN,
LAST_MODIFIED_BY_ID VARCHAR,
LAST_MODIFIED_DATE TIMESTAMP,
LEAD VARCHAR,
LEAD_COMPANY VARCHAR,
LICENSE_TYPE VARCHAR,
LICENSED_SEATS_STRING VARCHAR,
ORG_INSTANCE VARCHAR,
ORG_STATUS VARCHAR,
ORG_TRIAL_EXPIRATION_STRING VARCHAR,
ORG_TYPE VARCHAR,
PACKAGE_ID VARCHAR,
PACKAGE_NAME VARCHAR,
PACKAGE_VERSION_ID VARCHAR,
PACKAGE_VERSION_NUMBER VARCHAR,
PRODUCTION BOOLEAN,
RECORDTYPEID VARCHAR,
SALESFORCE_ACCOUNT_ID VARCHAR,
SALESFORCE_ACCOUNT_NAME VARCHAR,
SALESFORCE_LICENSE_ID VARCHAR,
SALESFORCE_ORGANIZATAION_RECORD_ID VARCHAR,
SEATS DECIMAL(8,0),
STATUS VARCHAR,
SUBSCRIBER_ORG_ID VARCHAR,
UNINSTALL_DATE DATE,
USED_LICENSES DECIMAL(18,0),
SALESFORCE_ORGANIZATAION_RECORD_ACCOUNT_ID VARCHAR
)
;     

PUT file://C:\Users\greg.wilson\Downloads\dim_license_20200930.csv @~
;

LIST @~;

SHOW PARAMETERS LIKE '%date%';

COPY INTO "APTTUS_DW"."PRODUCT"."DIM_LICENSE_RSH_20200930" 
FROM @~/dim_license_20200930.csv.gz
FILE_FORMAT = ( 
TYPE = CSV 
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
DATE_FORMAT = 'YYYY-MM-DD'
)
;


SHOW tasks IN SNAPSHOTS;

select * --count(*), STATUS
from "APTTUS_DW"."PRODUCT"."DIM_LICENSE_RSH_20200930" 
where SALESFORCE_LICENSE_ID not in
( Select distinct ID
from APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_CURRENT
)
and STATUS = 'Active'
and PACKAGE_NAME is not null
--group by status
;

--create table APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_FROMREDSHIFT
--as SELECT * FROM APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_SNAP_1;
--DELETE FROM  APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_FROMREDSHIFT;

-- backload history for LMA snapshots
--INSERT INTO APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_FROMREDSHIFT
SELECT  NULL AS ACCOUNT_SUSPENDED__C
	, BA_EMAIL AS BA_EMAIL__C
	, BA AS BA__C
	, NULL AS COMPANY_FROM_LEAD__C
	, NULL AS CONGA_EDITION__C
	, NULL AS CREATEDBYID
	, CREATED_DATE AS CREATEDDATE
	, SUBSCRIBER_ORG_ID AS CUSTOMER_ORG_ID__C
	, coalesce(TO_CHAR(TO_DATE(EXPIRATION)), 'Does not expire') AS EXPIRATION_DATE__C
	, SALESFORCE_LICENSE_ID AS ID
	, NULL AS INSTALL_DATE_CHECK__C
	, 0::boolean AS ISDELETED
	, LAST_MODIFIED_BY_ID AS LASTMODIFIEDBYID
	, LAST_MODIFIED_DATE AS LASTMODIFIEDDATE
	, NULL AS LEAD_COMPANY__C
	, NULL AS LEAD_EMAIL__C
	, NULL AS LICENSE_CHECK__C
	, NULL AS "NAME"
	, NULL AS OWNERID
	, PACKAGE_NAME AS PACKAGE_NAMEFX__C
	, PRODUCTION AS PRODUCTION__C
	, NULL AS QUIK_CUSTOMER_ID__C
	, RECORDTYPEID
	, NULL AS RECORD_URL__C
	, NULL AS SALESFORCE_ORGID__C
	, SALESFORCE_ACCOUNT_ID AS SFLMA__ACCOUNT__C
	, NULL AS SFLMA__CONTACT__C
	, coalesce(TO_CHAR(TO_DATE(EXPIRATION)), 'Does not expire') AS SFLMA__EXPIRATION_DATE__C
	, null AS SFLMA__EXPIRATION__C
	, NULL AS SFLMA__HELP__C
	, INSTALL_DATE AS SFLMA__INSTALL_DATE__C
	, NULL AS SFLMA__INSTANCE__C
	, IS_SANDBOX AS SFLMA__IS_SANDBOX__C
	, NULL AS SFLMA__LAST_MODIFIED__C
	, NULL AS SFLMA__LEAD__C
	, LICENSED_SEATS_STRING AS SFLMA__LICENSED_SEATS__C
	, STATUS AS SFLMA__LICENSE_STATUS__C
	, LICENSE_TYPE AS SFLMA__LICENSE_TYPE__C
	, NULL AS SFLMA__ORG_EDITION__C
	, NULL AS SFLMA__ORG_INSTANCE__C
	, NULL AS SFLMA__ORG_STATUS_FORMULA__C
	, ORG_STATUS AS SFLMA__ORG_STATUS__C
	, NULL AS SFLMA__ORG_TRIAL_EXPIRATION__C
	, ORG_TYPE AS SFLMA__ORG_TYPE__C
	, NULL AS SFLMA__PACKAGE_LICENSE_ID__C
	, PACKAGE_VERSION_NUMBER AS SFLMA__PACKAGE_VERSION_NUMBER__C
	, PACKAGE_VERSION_ID AS SFLMA__PACKAGE_VERSION__C
	, PACKAGE_ID AS SFLMA__PACKAGE__C
	, NULL AS SFLMA__PROXY_USER__C
	, SEATS AS SFLMA__SEATS__C
	, STATUS AS SFLMA__STATUS__C
	, SUBSCRIBER_ORG_ID AS SFLMA__SUBSCRIBER_ORG_ID__C
	, NULL AS SFLMA__SUBSCRIBER_ORG_IS_SANDBOX__C
	, NULL AS SFLMA__TRIAL_EXPIRATION_DATE__C
	, USED_LICENSES AS SFLMA__USED_LICENSES__C
	, NULL AS SFLMA__VERSION_NUMBER__C
	, NULL AS SUSPEND_ACCOUNT__C
	, LAST_MODIFIED_DATE AS SYSTEMMODSTAMP
	, UNINSTALL_DATE AS UNINSTALL_DATE__C
	, LAST_MODIFIED_DATE AS "_SDC_BATCHED_AT"
	, LAST_MODIFIED_DATE AS "_SDC_EXTRACTED_AT"
	, LAST_MODIFIED_DATE AS "_SDC_RECEIVED_AT"
	, 0 AS "_SDC_SEQUENCE"
	, 0 AS "_SDC_TABLE_VERSION"
	, CURRENT_TIMESTAMP() AS SNAP_LOAD_AT
from "APTTUS_DW"."PRODUCT"."DIM_LICENSE_RSH_20200930" 
where SALESFORCE_LICENSE_ID not in
( Select distinct ID
from APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_CURRENT
)
and STATUS = 'Active'
and PACKAGE_NAME is not null	