SELECT CURRENT_ROLE();

Select TABLE_CATALOG||'.'||TABLE_SCHEMA||'.'||TABLE_NAME, MAX(ORDINAL_POSITION)
 FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME LIKE 'ACCOUNT_A1_SNAP%'
 GROUP by TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
 order by 1
; 

with get_last as(
        Select MAX(ORDINAL_POSITION) as LAST_COL
         FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_NAME = 'ACCOUNT_A1_SNAP_1'
)
Select TABLE_CATALOG||'.'||TABLE_SCHEMA||'.'||TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME
 FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME LIKE 'ACCOUNT_A1_SNAP%'
   AND ORDINAL_POSITION > ((SELECT LAST_COL from get_last)-1)
   AND COLUMN_NAME <> 'SNAP_LOAD_AT'
ORDER BY 1, 2   
;  

Select TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION
FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE 'ASSET_C1_SNAP%'
ORDER BY ORDINAL_POSITION, TABLE_NAME 
;

select count(*) from APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1;
select count(*) from APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1604733784246_1609927633683;
select count(*) from APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1604733784246_1610100423680;
-- CHANGE -- uncommend insert and update table name to previous snap
-- CHANGE -- manage columns near bottom
INSERT INTO APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1604733784246_1609927633683 
          ( ACCOUNTSOURCE, ACCOUNT_ASSIGNED_ENGINEER__C, ACCOUNT_HISTORY_COMMENTS__C, ACCOUNT_LEGAL_NAME__C, ACCOUNT_REGION__C, ACV__C, AMS_SURVEY__C, ANNUALREVENUE
           , AVERAGE_ACV__C, BDR_ASSIGNED__C, BILLINGCITY, BILLINGCOUNTRY, BILLINGCOUNTRYCODE, BILLINGPOSTALCODE, BILLINGSTATE, BILLINGSTATECODE, BILLINGSTREET
           , BILLING_AP_EMAIL__C, BILLING_CONTACT__C, CLOUDINGOAGENT__BAS__C, CLOUDINGOAGENT__SAS__C, CONTRACT_MANAGEMENT_POSITIONS__C, CREATEDBYID, CREATEDDATE
           , CREATED_BY_AUTOMATION__C, CREDIT_CHECK_NOTES__C, CREDIT_CHECK_OVERRIDE__C, CREDIT_CHECK__C, CREDIT_HOLD__C, CREDIT_LIMIT__C, CRM_DYNAMICS__C, CRM_SALESFORCE__C
           , CURRENCYISOCODE, CUSTOMER_DOCUMENTATION__C, CUSTOMER_MANAGER__C, CUSTOMER_SEGMENT__C, CUSTOMER_SENTIMENT__C, CUSTOMER_SUPPORT_TRANSITION__C, DESCRIPTION
           , DSCORGPKG__DELETEDFROMDISCOVERORG__C, DSCORGPKG__DISCOVERORG_FIRST_UPDATE__C, DSCORGPKG__DISCOVERORG_FULLCOUNTRYNAME__C, DSCORGPKG__DISCOVERORG_ID__C
           , DSCORGPKG__DISCOVERORG_LASTUPDATE__C, DSCORGPKG__DISCOVERORG_STATE_FULL_NAME__C, DSCORGPKG__DO_3YR_EMPLOYEES_GROWTH__C, DSCORGPKG__DO_3YR_SALES_GROWTH__C
           , DSCORGPKG__EXCLUDE_UPDATE__C, DSCORGPKG__FORTUNE_RANK__C, DSCORGPKG__ITORGCHART__C, DSCORGPKG__IT_BUDGET__C, DSCORGPKG__IT_EMPLOYEES__C, DSCORGPKG__LEAD_SOURCE__C
           , DSCORGPKG__NAICS_CODES__C, DSCORGPKG__OWNERSHIP__C, DSCORGPKG__SIC_CODES__C, DUPLICATE_GROUP_ID__C, DYNAMICS_GUID__C, D_U_N_S_NUMBER__C, EFXID__C
           , EMPTORIS_SWAP_TYPE__C, EMPTORIS_SWAP__C, ENGAGIO__ENGAGEDPEOPLE__C, ENGAGIO__ENGAGEMENTMINUTESLAST3MONTHS__C, ENGAGIO__ENGAGEMENTMINUTESLAST7DAYS__C
           , ENGAGIO__FIRSTENGAGEMENTDATE__C, ENGAGIO__MQADATE__C, ENGAGIO__NUMBEROFPEOPLE__C, ENGAGIO__STATUS__C, ENGAGIO__WEBVISITSLAST3MONTHS__C, ERP__C, EXECUTIVE_SPONSOR__C
           , FAX, FFERPCORE__ISBILLINGADDRESSVALIDATED__C, FFERPCORE__ISSHIPPINGADDRESSVALIDATED__C, FFERPCORE__MATERIALIZEDBILLINGADDRESSVALIDATED__C
           , FFERPCORE__MATERIALIZEDSHIPPINGADDRESSVALIDATED__C, FISCAL_YEAR_END__C, FORTUNE_1000_RANK__C, GLOBAL_ULTIMATE_GROUPING_ID__C, GLOBAL_ULTIMATE_PARENT_COMPANY_ID__C
           , GLOBAL_ULTIMATE_PARENT_COMPANY__C, GLOBAL_ULTIMATE_PARENT__C, HIRING_CONTRACT_MANAGEMENT_POSITIONS__C, HOLDING_COMPANY__C, ID, INDUSTRY, INDUSTRY_FOCUS__C
           , INDUSTRY__C, INSIDEVIEW_ID__C, INTENT_AUTOMATED_CONTRACT_MANAGEMENT__C, INTENT_BUSINESS_SALES_ENABLEMENT__C, INTENT_BUSINESS_SALES_SALES_PRODUCTIVITY__C
           , INTENT_COMPLIANCE_GOVERNANCE_CLM__C, INTENT_SALES_CONTRACT_NEGOTIATIONS__C, INTENT_SALES_CPQ__C, INTENT_SALES_PROPOSALS_QUOTES__C
           , INTENT_SALES_PROPOSAL_QUOTE_GENERATION__C, ISDELETED, IV__INSIDEVIEW_CREATED__C, IV__INSIDEVIEW_DATE_LAST_UPDATED__C, IV__INSIDEVIEW_USER_LAST_UPDATED__C
           , LASTACTIVITYDATE, LASTMODIFIEDBYID, LASTMODIFIEDDATE, LASTREFERENCEDDATE, LASTVIEWEDDATE, LAST_CREDIT_CHECKED__C, LATEST_ACCOUNT_STATUS_CHANGE_DATE__C
           , LATEST_ACCOUNT_STATUS__C, LEGACY_OWNER_NAME__C, MANAGED_SERVICES_ENGINEER__C, MANAGED_SERVICES_EXPIRATION__C, MANAGED_SERVICES_HOURS__C, MANAGED_SERVICES_NOTES__C
           , MANAGED_SERVICES_PACKAGE__C, MANAGED_SERVICES_START_DATE__C, MASTERRECORDID, MASTER_FLAG__C, MASTER_ID_ADDRESS__C, MASTER_ID__C, MATCHEDSTATUS__C
           , MINTIGO_ACCOUNT_RANK_CLM__C, MINTIGO_ACCOUNT_RANK_CPQ__C, MINTIGO_ACCOUNT_RANK_QTC__C, MINTIGO_HASH__C, MINTIGO_SCORE_CLM__C, MINTIGO_SCORE_CPQ__C
           , MINTIGO_SCORE_QTC__C, MINTIGO_UPDATE_DATETIME__C, NAICS_CODE__C, NAICS_DESCRIPTION__C, NAME, NS_CUSTOMER_ID__C, NUMBEROFEMPLOYEES, OF_OPEN_OPPORTUNITITES__C
           , ORIGINAL_CONTRACT_DATE__C, OVERALL_HEALTH__C, OWNERID, OWNERSHIP, PARENTID, PARTNER_STATUS__C, PARTNER_TIER__C, PARTNER_TYPE__C, PAYMENT_TERMS__C, PHONE, PHOTOURL
           , PLAYBOOKS_NEXT_STEP_DUE_DATE__C, PLAYBOOKS_PLAY_NAME__C, PLAYBOOKS_PLAY_STATUS__C, PLAYBOOKS_STEP_NUMBER__C, PREMIER_SUPPORT_EXPIRATION__C
           , PREMIER_SUPPORT_START_DATE__C, PRIMARY_MS_CONTACT__C, PRODUCTS__C, PRODUCT_VALUES__C, PRODUCT__C, PSE__ADD_BEIS_TO_EXISTING_BATCHES__C, PURCHASE_ORDER__C
           , QUICK_NOTES_AE_UPDATED_ON__C, QUICK_NOTES_AE__C, QUICK_NOTES_BDR__C, RATING, REASON_NOT_IN_REFERENCE_PROGRAM__C, RECORDTYPEID, REFERENCEABLE_CUSTOMER__C
           , REFERENCE_PROGRAM__C, REGIONAL_COVERAGE__C, RENEWAL_DATE__C, RENEWAL_MANAGER__C, SALES_ENGINEER__C, SALES_FOCUS_ACCOUNT__C, SEGMENTATION__C, SHIPPINGCITY
           , SHIPPINGCOUNTRY, SHIPPINGCOUNTRYCODE, SHIPPINGPOSTALCODE, SHIPPINGSTATE, SHIPPINGSTATECODE, SHIPPINGSTREET, SIC, SICDESC, SOLUTION__C, SPECIALIZATION_NOTES__C
           , SPECIAL_ATTENTION_LABEL__C, STATUS__C, SUBSCRIPTION_ATR__C, SUBSCRIPTION_STATUS__C, SUB_INDUSTRY__C, SUB_REGION__C, SUPPORT_ATR__C, SUPPORT_LEVEL_NOTES__C
           , SUPPORT_LEVEL__C, SUPPORT_SERVICE_DETAILS__C, SYSTEMMODSTAMP, TARGET_ACCOUNT__C, TCVV__C, TECHNICAL_SUPPORT__C, TICKERSYMBOL, TOTAL_CERTIFIED_PROFESSIONALS_CLM__C
           , TOTAL_CERTIFIED_PROFESSIONALS_CPQ__C, TOTAL_NUMBER_OF_CERTIFICATIONS__C, TOTAL_OPPORTUNITIES__C, TYPE, ULTIMATE_DUNS__C, VERTICAL__C, WEBSITE, WON_OPPORTUNITIES__C
           , X18_DIGIT_OLD_SFDC_ID__C, X18_DIGIT_SFDC_ID__C, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, HAS_DEFAULT_SHIPPING_ACR__C
           , HAS_DEFAULT_BILLING_ACR__C, INTEGRATION_STATUS__C, ACV_POTENTIAL__C, SPECIAL_ATTENTION__C, DSCORGPKG__EXTERNAL_DISCOVERORG_ID__C, PLATFORM__C, ISCUSTOMERPORTAL
           , DSCORGPKG__FISCAL_YEAR_END__C, ISMIGRATED__C, NO_BDR_CONTACT__C, COMPANY_PARENT_ID__C, INSIDEVIEW_ULTIMATE_PARENT_COMPANY__C, MINTIGO_CLM_BUYING_STAGE__C
           , MINTIGO_CPQ_BUYING_STAGE__C, MINTIGO_QTC_BUYING_STAGE__C, TB_ACCOUNT__C, MINTIGO_LARGE_ACV_RANK__C, MINTIGO_LARGE_ACV_SCORE__C, FORTUNE_1000_COMPANY__C
           , INTENT_FORTUNE_500_PLUS__C, CHURN_DATE__C, ISPARTNER, SHIP_TO_NUM__C, NEXT_CONTRACT_NUMBER__C, LASTUPDATEDATEBYIV__C, BILL_TO_NUM__C, APTTUS_CONFIG2__TAXEXEMPT__C
           , APTTUS_BILLING__EXCLUDEFROMDUNNING__C, APTTUS_CONFIG2__BILLINGDAYOFMONTH__C, MAX_RENEWAL_UPLIFT__C, NUMBER_OF_ACCEPTED_PROPOSALS__C, ACTIVE_MSSA_NUMBER__C
           , APTTUS_BILLING__READYFORINVOICEDATE__C, ACCOUNT_PRIORITY__C, AMS_FTE__C, APTS_ACCOUNT_OWNER_PHONE__C, APTS_ACCOUNT_OWNER_EMAIL__C, APTS_ACCOUNT_OWNER_NAME__C
           , DEAL_DESK_RENEWAL_OPS_NOTES__C, AMS_ASSIST_REQUESTS__C, AMS_FTE__C__FL, TOTAL_ATR__C, RENEWAL_PROCESSED__C, CONGA_CUSTOMER__C, WILL_NOT_RENEW__C
           , TYPE_APPROVAL_PENDING__C, HOLD_TYPE_VALUE_TO_UPDATE_AFTER_APPROVAL__C, DSCORGPKG__DISCOVERORG_CREATED_ON__C, GEO__C, SEGMENT__C, CURRENCY_CONVERSION_RATE__C
           , CONGA_ACCOUNT_ID__C, INSIDEVIEW_REFERESH_NUMBER__C, INSIDEVIEW_ACT_NUMBER__C, PARENT_COMPANY_NAME__C, AT_RISK__C, OVERALL_SCORE__C, COVID_IMPACT__C
           , RENEWAL_PROBABILITY__C, NPS__C, ACCOUNT_FLAG__C, NPS__C__ST, COVID_IMPACT__C__ST, CSM_FORECAST__C, DNBOPTIMIZER__DNBCOMPANYRECORD__C
           , DNBOPTIMIZER__DNB_D_U_N_S_NUMBER__C, DNB_MATCH_SCORE__C, TRANSITION_DATE__C, ANAPLAN_INSIGHT_ANNUAL_REVENUE__C, ANAPLAN_INSIGHT_NUMBER_OF_EMPLOYEES__C
           , AMS_MANAGER__C, TARGET_ANNUAL_INFLUENCED_REVENUE__C, PREVIOUS_ACCOUNT_OWNER_NAME__C, NEW_ACCOUNT_OWNER__C, MANAGED__C, C1_18_DIGIT_SFDC_ID__C
           , ACCOUNT_SOURCE_CUSTOMER__C, ACCOUNTNUMBER, DOZISF__ZOOMINFO_ID__C, DOZISF__ZOOMINFO_LAST_UPDATED__C, DOZISF__ZOOMINFO_FIRST_UPDATED__C
           , PI_CROSS_SELL_SCORE_CONGA_CLM__C, PI_CROSS_SELL_RANK_CONGA_CLM__C, PI_CROSS_SELL_RANK_CONGA_DOCGEN__C, PI_CROSS_SELL_RANK_CONGA_SIGN__C
           , EXECUTIVE_SPONSOR_USER__C, GTM_PLAN__C, PI_CROSS_SELL_SCORECONGA_SIGN__C, PI_CROSS_SELL_SCORE_CONGA_DOCGEN__C, INDUSTRY_SOLUTION_ACCELERATORS__C
           , C1_NEXT_RENEWAL__C, C1_ACCOUNT_CONGA_SIGN_RANK__C, C1_TM_DIVISIONID__C, C1_ACCOUNT_CONGA_COMPOSER_RANK__C, C1_RED_CARE__C, ACCOUNT_ESCALATION_STATUS__C
           , C1_LICENSE_UTILIZATION__C, C1_INTACCT_CUSTOMER_ID__C, C1_ACTIVE_SIGN_MRR__C, C1_ACTIVE_AI_MRR__C, C1_ACCOUNT_CONGA_GRID_RANK__C
           , C1_ACCOUNT_WRITTEN_OFF_TO_BAD_DEBT__C, C1_LEGACY_DIVISION_ID__C, C1_LEGACY_CURRENT_RESELLER_ID__C, C1_ACTIVE_CONTRACTS_MRR__C, C1_ACTIVE_COLLABORATE_MRR__C
           , C1_CUSTOMER_SINCE_DATE_FORMULA__C, C1_ACCOUNT_RANK__C, C1_SBQQ_RENEWALPRICINGMETHOD__C, C1_CURRENT_RESELLER__C, C1_RENEWAL_UPLIFT_CAP__C
           , C1_COMPOSER_LEVEL_1_CERTS__C, C1_HANDLE_WITH_CARE__C, ACCOUNT_ESCALATION_DATE__C, C1_CONTRACTS_CERTS__C, C1_ENGAGIO_STATUS__C, C1_ACCOUNT_COLLABORATE_RANK__C
           , C1_LOGO_ON_WEBSITE__C, C1_ACTIVE_GRID_MRR__C, C1_RED_CARE_OUTCOME__C, C1_HANDLE_WITH_CARE_COMMENT__C, ESCALATION_OWNER__C, C1_COMPOSER_AUTOMATION_CERTS__C
           , C1_ACCOUNT_COURIER_RANK__C, C1_SALESFORCE_INSTANCE__C, C1_CUSTOMER_SUCCESS_MANAGER__C, C1_ACTIVE_ORCHESTRATE_MRR__C, ESCALATION_EXECUTIVE_OWNER__C
           , C1_ACCOUNT_SERVICES_AND_SUPPORT_RANK__C, C1_COMPOSER_LEVEL_2_CERTS__C, C1_OWNER__C, C1_SALESFORCE_ORG_ID_15__C, C1_SF_USERS_TIER__C, C1_CSM_COMMERCIAL_TERMS__C
           , C1_CUSTOMER_SENTIMENT__C, C1_ENGAGIO_ENGAGEMENTMINUTESLAST3MONTHS__C, C1_ACCOUNT_TYPE__C, C1_LEGACY_TERRITORY_MANAGER__C, C1_ACCOUNT_ID__C, C1_HAVE_DOCUSIGN__C
           , C1_ACTIVE_COMPOSER_MRR__C, C1_ENGAGIO_ENGAGEMENTMINUTESLAST7DAYS__C, ESCALATION_CLOSURE_CRITERIA__C, CONGA_INTEGRATION_STATUS__C, C1_TM_RENEWALS_MANAGERID__C
           , C1_ACCOUNT_DELINQUENT_FLAG__C, C1_LEGACY_OWNER__C, C1_ACCOUNT_BATCH_RANK__C, C1_CUSTOMER_HEALTH_FX__C, C1_ACTIVE_COURIER_MRR__C, C1_MINTIGO_HASH__C
           , MATCHED_ACCOUNT__C, C1_RED_CARE_STATUS__C, C1_LEGACY_GEO_ID__C, C1_CUSTOMER_LIKELY_TO__C, C1_ACTIVE_AUTOMATION_MRR__C, C1_OFF_SHORE_OPT_OUT__C
           , C1_MINTIGO_UPDATE_DATETIME__C, C1_GRID_CERTS__C, ACCOUNT_ESCALATION_TYPE__C, C1_INTENT_DOCUMENT_AUTOMATION__C, C1_SIGN_CERTS__C, C1_LEGACY_REGION_ID__C
           , C1_CURRENT_IMPLEMENTATION_PARTNERID__C, C1_ACCOUNT_NAME__C, C1_SUPPORT_LEVEL__C, C1_TEST_ACCOUNT__C, TOTAL_OPPORTUNITIES1__C, C1_LEGACY_SEGMENT_ID__C
           , C1_LEGACY_CURRENT_IMPLEMENTATION_PARTNER__C, C1_ACCOUNT_ORCHESTRATE_RANK__C, C1_PRIMARY_ADOPTION_BLOCKER__C, C1_RED_CARETXT__C, C1_GOLD_LIST_ACCOUNTS__C
           , ESCALATION_SUMMARY__C, C1_LEGACY_TERRITORY_ID__C, C1_SPECIAL_LEGAL_TERMS__C, C1_CS_DIVISION_STAMP__C, C1_ADVANCED_CONTRACTS_CERTS__C, ACCOUNT_ESCALATED_BY__C
           , C1_CUSTOMER_NEEDS__C, REASON_FOR_ACCOUNT_ESCALATION__C, ACCOUNT_LEVEL_PS_OWNER__C, C1_SALESFORCE_USERS__C, C1_LEGACY_CUSTOMER_SUCCESS_MANAGER__C
           , ESCALATION_ACTION_PLAN__C, C1_ACTIVE_MRR_2__C, C1_SALESFORCE_ACCOUNT_ID__C, C1_MINTIGO_TARGETING_PRIORITY__C, DE_ESCALATION_CRITERIA__C, TOTAL_EXPECTED_REVENUE__C
           , A1_SURVIVOR_ACCOUNT_ID__C, ISEXCLUDEDFROMREALIGN, C1_ACTIVE_SUPPORT_MRR__C, C1_BURDENED_MRR__C, C1_CONTRACTS_FOR_SF_CERTS__C, C1_LEGACY_RENEWALS_MANAGER__C
           , C1_SALESFORCE_ACCOUNT_USERS__C, DID_NOT_SURVIVE__C, C1_TM_TERRITORY_MANAGERID__C, C1_INTENT_AUTOMATED_CONTRACT_MANAGEMENT__C, C1_ACTIVE_CONTRACTS_FOR_SF_MRR__C
           , C1_PURCHASING_METHOD__C, C1_BILLABLE_TIME_CURRENT_SUBSCRIPTION__C, C1_SITE_RECORD_EXTERNAL_ID__C, RENEWAL_MODE__C, PI_CROSS_SELL_RANK_APTTUS_CLM__C
           , PI_CROSS_SELL_RANK_APTTUS_QTC__C, PI_CROSS_SELL_SCORE_APTTUS_CLM__C, PI_CROSS_SELL_RANK_APTTUS_CPQ__C, PI_CROSS_SELL_SCORE_APTTUS_QTC__C
           , PI_CROSS_SELL_SCORE_APTTUS_CPQ__C, C1_PARTNERTARGETANNUALINFLUENCED_REVENUE__C
           -- 20201/01/07
           , APTTUS_BILLING__ACTIVE__C   
          -- 
          --
          , SNAP_LOAD_AT) 
SELECT  ACCOUNTSOURCE, ACCOUNT_ASSIGNED_ENGINEER__C, ACCOUNT_HISTORY_COMMENTS__C, ACCOUNT_LEGAL_NAME__C, ACCOUNT_REGION__C, ACV__C, AMS_SURVEY__C, ANNUALREVENUE
           , AVERAGE_ACV__C, BDR_ASSIGNED__C, BILLINGCITY, BILLINGCOUNTRY, BILLINGCOUNTRYCODE, BILLINGPOSTALCODE, BILLINGSTATE, BILLINGSTATECODE, BILLINGSTREET
           , BILLING_AP_EMAIL__C, BILLING_CONTACT__C, CLOUDINGOAGENT__BAS__C, CLOUDINGOAGENT__SAS__C, CONTRACT_MANAGEMENT_POSITIONS__C, CREATEDBYID, CREATEDDATE
           , CREATED_BY_AUTOMATION__C, CREDIT_CHECK_NOTES__C, CREDIT_CHECK_OVERRIDE__C, CREDIT_CHECK__C, CREDIT_HOLD__C, CREDIT_LIMIT__C, CRM_DYNAMICS__C, CRM_SALESFORCE__C
           , CURRENCYISOCODE, CUSTOMER_DOCUMENTATION__C, CUSTOMER_MANAGER__C, CUSTOMER_SEGMENT__C, CUSTOMER_SENTIMENT__C, CUSTOMER_SUPPORT_TRANSITION__C, DESCRIPTION
           , DSCORGPKG__DELETEDFROMDISCOVERORG__C, DSCORGPKG__DISCOVERORG_FIRST_UPDATE__C, DSCORGPKG__DISCOVERORG_FULLCOUNTRYNAME__C, DSCORGPKG__DISCOVERORG_ID__C
           , DSCORGPKG__DISCOVERORG_LASTUPDATE__C, DSCORGPKG__DISCOVERORG_STATE_FULL_NAME__C, DSCORGPKG__DO_3YR_EMPLOYEES_GROWTH__C, DSCORGPKG__DO_3YR_SALES_GROWTH__C
           , DSCORGPKG__EXCLUDE_UPDATE__C, DSCORGPKG__FORTUNE_RANK__C, DSCORGPKG__ITORGCHART__C, DSCORGPKG__IT_BUDGET__C, DSCORGPKG__IT_EMPLOYEES__C, DSCORGPKG__LEAD_SOURCE__C
           , DSCORGPKG__NAICS_CODES__C, DSCORGPKG__OWNERSHIP__C, DSCORGPKG__SIC_CODES__C, DUPLICATE_GROUP_ID__C, DYNAMICS_GUID__C, D_U_N_S_NUMBER__C, EFXID__C
           , EMPTORIS_SWAP_TYPE__C, EMPTORIS_SWAP__C, ENGAGIO__ENGAGEDPEOPLE__C, ENGAGIO__ENGAGEMENTMINUTESLAST3MONTHS__C, ENGAGIO__ENGAGEMENTMINUTESLAST7DAYS__C
           , ENGAGIO__FIRSTENGAGEMENTDATE__C, ENGAGIO__MQADATE__C, ENGAGIO__NUMBEROFPEOPLE__C, ENGAGIO__STATUS__C, ENGAGIO__WEBVISITSLAST3MONTHS__C, ERP__C, EXECUTIVE_SPONSOR__C
           , FAX, FFERPCORE__ISBILLINGADDRESSVALIDATED__C, FFERPCORE__ISSHIPPINGADDRESSVALIDATED__C, FFERPCORE__MATERIALIZEDBILLINGADDRESSVALIDATED__C
           , FFERPCORE__MATERIALIZEDSHIPPINGADDRESSVALIDATED__C, FISCAL_YEAR_END__C, FORTUNE_1000_RANK__C, GLOBAL_ULTIMATE_GROUPING_ID__C, GLOBAL_ULTIMATE_PARENT_COMPANY_ID__C
           , GLOBAL_ULTIMATE_PARENT_COMPANY__C, GLOBAL_ULTIMATE_PARENT__C, HIRING_CONTRACT_MANAGEMENT_POSITIONS__C, HOLDING_COMPANY__C, ID, INDUSTRY, INDUSTRY_FOCUS__C
           , INDUSTRY__C, INSIDEVIEW_ID__C, INTENT_AUTOMATED_CONTRACT_MANAGEMENT__C, INTENT_BUSINESS_SALES_ENABLEMENT__C, INTENT_BUSINESS_SALES_SALES_PRODUCTIVITY__C
           , INTENT_COMPLIANCE_GOVERNANCE_CLM__C, INTENT_SALES_CONTRACT_NEGOTIATIONS__C, INTENT_SALES_CPQ__C, INTENT_SALES_PROPOSALS_QUOTES__C
           , INTENT_SALES_PROPOSAL_QUOTE_GENERATION__C, ISDELETED, IV__INSIDEVIEW_CREATED__C, IV__INSIDEVIEW_DATE_LAST_UPDATED__C, IV__INSIDEVIEW_USER_LAST_UPDATED__C
           , LASTACTIVITYDATE, LASTMODIFIEDBYID, LASTMODIFIEDDATE, LASTREFERENCEDDATE, LASTVIEWEDDATE, LAST_CREDIT_CHECKED__C, LATEST_ACCOUNT_STATUS_CHANGE_DATE__C
           , LATEST_ACCOUNT_STATUS__C, LEGACY_OWNER_NAME__C, MANAGED_SERVICES_ENGINEER__C, MANAGED_SERVICES_EXPIRATION__C, MANAGED_SERVICES_HOURS__C, MANAGED_SERVICES_NOTES__C
           , MANAGED_SERVICES_PACKAGE__C, MANAGED_SERVICES_START_DATE__C, MASTERRECORDID, MASTER_FLAG__C, MASTER_ID_ADDRESS__C, MASTER_ID__C, MATCHEDSTATUS__C
           , MINTIGO_ACCOUNT_RANK_CLM__C, MINTIGO_ACCOUNT_RANK_CPQ__C, MINTIGO_ACCOUNT_RANK_QTC__C, MINTIGO_HASH__C, MINTIGO_SCORE_CLM__C, MINTIGO_SCORE_CPQ__C
           , MINTIGO_SCORE_QTC__C, MINTIGO_UPDATE_DATETIME__C, NAICS_CODE__C, NAICS_DESCRIPTION__C, NAME, NS_CUSTOMER_ID__C, NUMBEROFEMPLOYEES, OF_OPEN_OPPORTUNITITES__C
           , ORIGINAL_CONTRACT_DATE__C, OVERALL_HEALTH__C, OWNERID, OWNERSHIP, PARENTID, PARTNER_STATUS__C, PARTNER_TIER__C, PARTNER_TYPE__C, PAYMENT_TERMS__C, PHONE, PHOTOURL
           , PLAYBOOKS_NEXT_STEP_DUE_DATE__C, PLAYBOOKS_PLAY_NAME__C, PLAYBOOKS_PLAY_STATUS__C, PLAYBOOKS_STEP_NUMBER__C, PREMIER_SUPPORT_EXPIRATION__C
           , PREMIER_SUPPORT_START_DATE__C, PRIMARY_MS_CONTACT__C, PRODUCTS__C, PRODUCT_VALUES__C, PRODUCT__C, PSE__ADD_BEIS_TO_EXISTING_BATCHES__C, PURCHASE_ORDER__C
           , QUICK_NOTES_AE_UPDATED_ON__C, QUICK_NOTES_AE__C, QUICK_NOTES_BDR__C, RATING, REASON_NOT_IN_REFERENCE_PROGRAM__C, RECORDTYPEID, REFERENCEABLE_CUSTOMER__C
           , REFERENCE_PROGRAM__C, REGIONAL_COVERAGE__C, RENEWAL_DATE__C, RENEWAL_MANAGER__C, SALES_ENGINEER__C, SALES_FOCUS_ACCOUNT__C, SEGMENTATION__C, SHIPPINGCITY
           , SHIPPINGCOUNTRY, SHIPPINGCOUNTRYCODE, SHIPPINGPOSTALCODE, SHIPPINGSTATE, SHIPPINGSTATECODE, SHIPPINGSTREET, SIC, SICDESC, SOLUTION__C, SPECIALIZATION_NOTES__C
           , SPECIAL_ATTENTION_LABEL__C, STATUS__C, SUBSCRIPTION_ATR__C, SUBSCRIPTION_STATUS__C, SUB_INDUSTRY__C, SUB_REGION__C, SUPPORT_ATR__C, SUPPORT_LEVEL_NOTES__C
           , SUPPORT_LEVEL__C, SUPPORT_SERVICE_DETAILS__C, SYSTEMMODSTAMP, TARGET_ACCOUNT__C, TCVV__C, TECHNICAL_SUPPORT__C, TICKERSYMBOL, TOTAL_CERTIFIED_PROFESSIONALS_CLM__C
           , TOTAL_CERTIFIED_PROFESSIONALS_CPQ__C, TOTAL_NUMBER_OF_CERTIFICATIONS__C, TOTAL_OPPORTUNITIES__C, TYPE, ULTIMATE_DUNS__C, VERTICAL__C, WEBSITE, WON_OPPORTUNITIES__C
           , X18_DIGIT_OLD_SFDC_ID__C, X18_DIGIT_SFDC_ID__C, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, HAS_DEFAULT_SHIPPING_ACR__C
           , HAS_DEFAULT_BILLING_ACR__C, INTEGRATION_STATUS__C, ACV_POTENTIAL__C, SPECIAL_ATTENTION__C, DSCORGPKG__EXTERNAL_DISCOVERORG_ID__C, PLATFORM__C, ISCUSTOMERPORTAL
           , DSCORGPKG__FISCAL_YEAR_END__C, ISMIGRATED__C, NO_BDR_CONTACT__C, COMPANY_PARENT_ID__C, INSIDEVIEW_ULTIMATE_PARENT_COMPANY__C, MINTIGO_CLM_BUYING_STAGE__C
           , MINTIGO_CPQ_BUYING_STAGE__C, MINTIGO_QTC_BUYING_STAGE__C, TB_ACCOUNT__C, MINTIGO_LARGE_ACV_RANK__C, MINTIGO_LARGE_ACV_SCORE__C, FORTUNE_1000_COMPANY__C
           , INTENT_FORTUNE_500_PLUS__C, CHURN_DATE__C, ISPARTNER, SHIP_TO_NUM__C, NEXT_CONTRACT_NUMBER__C, LASTUPDATEDATEBYIV__C, BILL_TO_NUM__C, APTTUS_CONFIG2__TAXEXEMPT__C
           , APTTUS_BILLING__EXCLUDEFROMDUNNING__C, APTTUS_CONFIG2__BILLINGDAYOFMONTH__C, MAX_RENEWAL_UPLIFT__C, NUMBER_OF_ACCEPTED_PROPOSALS__C, ACTIVE_MSSA_NUMBER__C
           , APTTUS_BILLING__READYFORINVOICEDATE__C, ACCOUNT_PRIORITY__C, AMS_FTE__C, APTS_ACCOUNT_OWNER_PHONE__C, APTS_ACCOUNT_OWNER_EMAIL__C, APTS_ACCOUNT_OWNER_NAME__C
           , DEAL_DESK_RENEWAL_OPS_NOTES__C, AMS_ASSIST_REQUESTS__C, AMS_FTE__C__FL, TOTAL_ATR__C, RENEWAL_PROCESSED__C, CONGA_CUSTOMER__C, WILL_NOT_RENEW__C
           , TYPE_APPROVAL_PENDING__C, HOLD_TYPE_VALUE_TO_UPDATE_AFTER_APPROVAL__C, DSCORGPKG__DISCOVERORG_CREATED_ON__C, GEO__C, SEGMENT__C, CURRENCY_CONVERSION_RATE__C
           , CONGA_ACCOUNT_ID__C, INSIDEVIEW_REFERESH_NUMBER__C, INSIDEVIEW_ACT_NUMBER__C, PARENT_COMPANY_NAME__C, AT_RISK__C, OVERALL_SCORE__C, COVID_IMPACT__C
           , RENEWAL_PROBABILITY__C, NPS__C, ACCOUNT_FLAG__C, NPS__C__ST, COVID_IMPACT__C__ST, CSM_FORECAST__C, DNBOPTIMIZER__DNBCOMPANYRECORD__C
           , DNBOPTIMIZER__DNB_D_U_N_S_NUMBER__C, DNB_MATCH_SCORE__C, TRANSITION_DATE__C, ANAPLAN_INSIGHT_ANNUAL_REVENUE__C, ANAPLAN_INSIGHT_NUMBER_OF_EMPLOYEES__C
           , AMS_MANAGER__C, TARGET_ANNUAL_INFLUENCED_REVENUE__C, PREVIOUS_ACCOUNT_OWNER_NAME__C, NEW_ACCOUNT_OWNER__C, MANAGED__C, C1_18_DIGIT_SFDC_ID__C
           , ACCOUNT_SOURCE_CUSTOMER__C, ACCOUNTNUMBER, DOZISF__ZOOMINFO_ID__C, DOZISF__ZOOMINFO_LAST_UPDATED__C, DOZISF__ZOOMINFO_FIRST_UPDATED__C
           , PI_CROSS_SELL_SCORE_CONGA_CLM__C, PI_CROSS_SELL_RANK_CONGA_CLM__C, PI_CROSS_SELL_RANK_CONGA_DOCGEN__C, PI_CROSS_SELL_RANK_CONGA_SIGN__C
           , EXECUTIVE_SPONSOR_USER__C, GTM_PLAN__C, PI_CROSS_SELL_SCORECONGA_SIGN__C, PI_CROSS_SELL_SCORE_CONGA_DOCGEN__C, INDUSTRY_SOLUTION_ACCELERATORS__C
           , C1_NEXT_RENEWAL__C, C1_ACCOUNT_CONGA_SIGN_RANK__C, C1_TM_DIVISIONID__C, C1_ACCOUNT_CONGA_COMPOSER_RANK__C, C1_RED_CARE__C, ACCOUNT_ESCALATION_STATUS__C
           , C1_LICENSE_UTILIZATION__C, C1_INTACCT_CUSTOMER_ID__C, C1_ACTIVE_SIGN_MRR__C, C1_ACTIVE_AI_MRR__C, C1_ACCOUNT_CONGA_GRID_RANK__C
           , C1_ACCOUNT_WRITTEN_OFF_TO_BAD_DEBT__C, C1_LEGACY_DIVISION_ID__C, C1_LEGACY_CURRENT_RESELLER_ID__C, C1_ACTIVE_CONTRACTS_MRR__C, C1_ACTIVE_COLLABORATE_MRR__C
           , C1_CUSTOMER_SINCE_DATE_FORMULA__C, C1_ACCOUNT_RANK__C, C1_SBQQ_RENEWALPRICINGMETHOD__C, C1_CURRENT_RESELLER__C, C1_RENEWAL_UPLIFT_CAP__C
           , C1_COMPOSER_LEVEL_1_CERTS__C, C1_HANDLE_WITH_CARE__C, ACCOUNT_ESCALATION_DATE__C, C1_CONTRACTS_CERTS__C, C1_ENGAGIO_STATUS__C, C1_ACCOUNT_COLLABORATE_RANK__C
           , C1_LOGO_ON_WEBSITE__C, C1_ACTIVE_GRID_MRR__C, C1_RED_CARE_OUTCOME__C, C1_HANDLE_WITH_CARE_COMMENT__C, ESCALATION_OWNER__C, C1_COMPOSER_AUTOMATION_CERTS__C
           , C1_ACCOUNT_COURIER_RANK__C, C1_SALESFORCE_INSTANCE__C, C1_CUSTOMER_SUCCESS_MANAGER__C, C1_ACTIVE_ORCHESTRATE_MRR__C, ESCALATION_EXECUTIVE_OWNER__C
           , C1_ACCOUNT_SERVICES_AND_SUPPORT_RANK__C, C1_COMPOSER_LEVEL_2_CERTS__C, C1_OWNER__C, C1_SALESFORCE_ORG_ID_15__C, C1_SF_USERS_TIER__C, C1_CSM_COMMERCIAL_TERMS__C
           , C1_CUSTOMER_SENTIMENT__C, C1_ENGAGIO_ENGAGEMENTMINUTESLAST3MONTHS__C, C1_ACCOUNT_TYPE__C, C1_LEGACY_TERRITORY_MANAGER__C, C1_ACCOUNT_ID__C, C1_HAVE_DOCUSIGN__C
           , C1_ACTIVE_COMPOSER_MRR__C, C1_ENGAGIO_ENGAGEMENTMINUTESLAST7DAYS__C, ESCALATION_CLOSURE_CRITERIA__C, CONGA_INTEGRATION_STATUS__C, C1_TM_RENEWALS_MANAGERID__C
           , C1_ACCOUNT_DELINQUENT_FLAG__C, C1_LEGACY_OWNER__C, C1_ACCOUNT_BATCH_RANK__C, C1_CUSTOMER_HEALTH_FX__C, C1_ACTIVE_COURIER_MRR__C, C1_MINTIGO_HASH__C
           , MATCHED_ACCOUNT__C, C1_RED_CARE_STATUS__C, C1_LEGACY_GEO_ID__C, C1_CUSTOMER_LIKELY_TO__C, C1_ACTIVE_AUTOMATION_MRR__C, C1_OFF_SHORE_OPT_OUT__C
           , C1_MINTIGO_UPDATE_DATETIME__C, C1_GRID_CERTS__C, ACCOUNT_ESCALATION_TYPE__C, C1_INTENT_DOCUMENT_AUTOMATION__C, C1_SIGN_CERTS__C, C1_LEGACY_REGION_ID__C
           , C1_CURRENT_IMPLEMENTATION_PARTNERID__C, C1_ACCOUNT_NAME__C, C1_SUPPORT_LEVEL__C, C1_TEST_ACCOUNT__C, TOTAL_OPPORTUNITIES1__C, C1_LEGACY_SEGMENT_ID__C
           , C1_LEGACY_CURRENT_IMPLEMENTATION_PARTNER__C, C1_ACCOUNT_ORCHESTRATE_RANK__C, C1_PRIMARY_ADOPTION_BLOCKER__C, C1_RED_CARETXT__C, C1_GOLD_LIST_ACCOUNTS__C
           , ESCALATION_SUMMARY__C, C1_LEGACY_TERRITORY_ID__C, C1_SPECIAL_LEGAL_TERMS__C, C1_CS_DIVISION_STAMP__C, C1_ADVANCED_CONTRACTS_CERTS__C, ACCOUNT_ESCALATED_BY__C
           , C1_CUSTOMER_NEEDS__C, REASON_FOR_ACCOUNT_ESCALATION__C, ACCOUNT_LEVEL_PS_OWNER__C, C1_SALESFORCE_USERS__C, C1_LEGACY_CUSTOMER_SUCCESS_MANAGER__C
           , ESCALATION_ACTION_PLAN__C, C1_ACTIVE_MRR_2__C, C1_SALESFORCE_ACCOUNT_ID__C, C1_MINTIGO_TARGETING_PRIORITY__C, DE_ESCALATION_CRITERIA__C, TOTAL_EXPECTED_REVENUE__C
           , A1_SURVIVOR_ACCOUNT_ID__C, ISEXCLUDEDFROMREALIGN, C1_ACTIVE_SUPPORT_MRR__C, C1_BURDENED_MRR__C, C1_CONTRACTS_FOR_SF_CERTS__C, C1_LEGACY_RENEWALS_MANAGER__C
           , C1_SALESFORCE_ACCOUNT_USERS__C, DID_NOT_SURVIVE__C, C1_TM_TERRITORY_MANAGERID__C, C1_INTENT_AUTOMATED_CONTRACT_MANAGEMENT__C, C1_ACTIVE_CONTRACTS_FOR_SF_MRR__C
           , C1_PURCHASING_METHOD__C, C1_BILLABLE_TIME_CURRENT_SUBSCRIPTION__C, C1_SITE_RECORD_EXTERNAL_ID__C, RENEWAL_MODE__C, PI_CROSS_SELL_RANK_APTTUS_CLM__C
           , PI_CROSS_SELL_RANK_APTTUS_QTC__C, PI_CROSS_SELL_SCORE_APTTUS_CLM__C, PI_CROSS_SELL_RANK_APTTUS_CPQ__C, PI_CROSS_SELL_SCORE_APTTUS_QTC__C
           , PI_CROSS_SELL_SCORE_APTTUS_CPQ__C, C1_PARTNERTARGETANNUALINFLUENCED_REVENUE__C
           -- 20201/01/07
           , NULL AS APTTUS_BILLING__ACTIVE__C     
-- change -- remove older NULL AS from column
-- change -- add columns from the previous snap iteration as NULL AS 
	  , SNAP_LOAD_AT
FROM
	APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1
;		

-- change -- check counts to insure that the recently replaced snap now has all rows
drop table APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_PRIOR;
alter TABLE APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1 rename to APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_PRIOR;
-- change first snap to be the recently replaced 
alter table APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1604733784246_1609927633683 rename to APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1;
select count(*) from APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1;

--*****DROP VIEW APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_HISTORY ;

-- make changes below and then rebuild the history
CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_HISTORY  
COMMENT = 'Union ACCOUNT_A1 snapshots to make complete history'
AS 
WITH the_union AS (
	SELECT ACCOUNTSOURCE, ACCOUNT_ASSIGNED_ENGINEER__C, ACCOUNT_HISTORY_COMMENTS__C, ACCOUNT_LEGAL_NAME__C, ACCOUNT_REGION__C, ACV__C, AMS_SURVEY__C, ANNUALREVENUE
           , AVERAGE_ACV__C, BDR_ASSIGNED__C, BILLINGCITY, BILLINGCOUNTRY, BILLINGCOUNTRYCODE, BILLINGPOSTALCODE, BILLINGSTATE, BILLINGSTATECODE, BILLINGSTREET
           , BILLING_AP_EMAIL__C, BILLING_CONTACT__C, CLOUDINGOAGENT__BAS__C, CLOUDINGOAGENT__SAS__C, CONTRACT_MANAGEMENT_POSITIONS__C, CREATEDBYID, CREATEDDATE
           , CREATED_BY_AUTOMATION__C, CREDIT_CHECK_NOTES__C, CREDIT_CHECK_OVERRIDE__C, CREDIT_CHECK__C, CREDIT_HOLD__C, CREDIT_LIMIT__C, CRM_DYNAMICS__C, CRM_SALESFORCE__C
           , CURRENCYISOCODE, CUSTOMER_DOCUMENTATION__C, CUSTOMER_MANAGER__C, CUSTOMER_SEGMENT__C, CUSTOMER_SENTIMENT__C, CUSTOMER_SUPPORT_TRANSITION__C, DESCRIPTION
           , DSCORGPKG__DELETEDFROMDISCOVERORG__C, DSCORGPKG__DISCOVERORG_FIRST_UPDATE__C, DSCORGPKG__DISCOVERORG_FULLCOUNTRYNAME__C, DSCORGPKG__DISCOVERORG_ID__C
           , DSCORGPKG__DISCOVERORG_LASTUPDATE__C, DSCORGPKG__DISCOVERORG_STATE_FULL_NAME__C, DSCORGPKG__DO_3YR_EMPLOYEES_GROWTH__C, DSCORGPKG__DO_3YR_SALES_GROWTH__C
           , DSCORGPKG__EXCLUDE_UPDATE__C, DSCORGPKG__FORTUNE_RANK__C, DSCORGPKG__ITORGCHART__C, DSCORGPKG__IT_BUDGET__C, DSCORGPKG__IT_EMPLOYEES__C, DSCORGPKG__LEAD_SOURCE__C
           , DSCORGPKG__NAICS_CODES__C, DSCORGPKG__OWNERSHIP__C, DSCORGPKG__SIC_CODES__C, DUPLICATE_GROUP_ID__C, DYNAMICS_GUID__C, D_U_N_S_NUMBER__C, EFXID__C
           , EMPTORIS_SWAP_TYPE__C, EMPTORIS_SWAP__C, ENGAGIO__ENGAGEDPEOPLE__C, ENGAGIO__ENGAGEMENTMINUTESLAST3MONTHS__C, ENGAGIO__ENGAGEMENTMINUTESLAST7DAYS__C
           , ENGAGIO__FIRSTENGAGEMENTDATE__C, ENGAGIO__MQADATE__C, ENGAGIO__NUMBEROFPEOPLE__C, ENGAGIO__STATUS__C, ENGAGIO__WEBVISITSLAST3MONTHS__C, ERP__C, EXECUTIVE_SPONSOR__C
           , FAX, FFERPCORE__ISBILLINGADDRESSVALIDATED__C, FFERPCORE__ISSHIPPINGADDRESSVALIDATED__C, FFERPCORE__MATERIALIZEDBILLINGADDRESSVALIDATED__C
           , FFERPCORE__MATERIALIZEDSHIPPINGADDRESSVALIDATED__C, FISCAL_YEAR_END__C, FORTUNE_1000_RANK__C, GLOBAL_ULTIMATE_GROUPING_ID__C, GLOBAL_ULTIMATE_PARENT_COMPANY_ID__C
           , GLOBAL_ULTIMATE_PARENT_COMPANY__C, GLOBAL_ULTIMATE_PARENT__C, HIRING_CONTRACT_MANAGEMENT_POSITIONS__C, HOLDING_COMPANY__C, ID, INDUSTRY, INDUSTRY_FOCUS__C
           , INDUSTRY__C, INSIDEVIEW_ID__C, INTENT_AUTOMATED_CONTRACT_MANAGEMENT__C, INTENT_BUSINESS_SALES_ENABLEMENT__C, INTENT_BUSINESS_SALES_SALES_PRODUCTIVITY__C
           , INTENT_COMPLIANCE_GOVERNANCE_CLM__C, INTENT_SALES_CONTRACT_NEGOTIATIONS__C, INTENT_SALES_CPQ__C, INTENT_SALES_PROPOSALS_QUOTES__C
           , INTENT_SALES_PROPOSAL_QUOTE_GENERATION__C, ISDELETED, IV__INSIDEVIEW_CREATED__C, IV__INSIDEVIEW_DATE_LAST_UPDATED__C, IV__INSIDEVIEW_USER_LAST_UPDATED__C
           , LASTACTIVITYDATE, LASTMODIFIEDBYID, LASTMODIFIEDDATE, LASTREFERENCEDDATE, LASTVIEWEDDATE, LAST_CREDIT_CHECKED__C, LATEST_ACCOUNT_STATUS_CHANGE_DATE__C
           , LATEST_ACCOUNT_STATUS__C, LEGACY_OWNER_NAME__C, MANAGED_SERVICES_ENGINEER__C, MANAGED_SERVICES_EXPIRATION__C, MANAGED_SERVICES_HOURS__C, MANAGED_SERVICES_NOTES__C
           , MANAGED_SERVICES_PACKAGE__C, MANAGED_SERVICES_START_DATE__C, MASTERRECORDID, MASTER_FLAG__C, MASTER_ID_ADDRESS__C, MASTER_ID__C, MATCHEDSTATUS__C
           , MINTIGO_ACCOUNT_RANK_CLM__C, MINTIGO_ACCOUNT_RANK_CPQ__C, MINTIGO_ACCOUNT_RANK_QTC__C, MINTIGO_HASH__C, MINTIGO_SCORE_CLM__C, MINTIGO_SCORE_CPQ__C
           , MINTIGO_SCORE_QTC__C, MINTIGO_UPDATE_DATETIME__C, NAICS_CODE__C, NAICS_DESCRIPTION__C, NAME, NS_CUSTOMER_ID__C, NUMBEROFEMPLOYEES, OF_OPEN_OPPORTUNITITES__C
           , ORIGINAL_CONTRACT_DATE__C, OVERALL_HEALTH__C, OWNERID, OWNERSHIP, PARENTID, PARTNER_STATUS__C, PARTNER_TIER__C, PARTNER_TYPE__C, PAYMENT_TERMS__C, PHONE, PHOTOURL
           , PLAYBOOKS_NEXT_STEP_DUE_DATE__C, PLAYBOOKS_PLAY_NAME__C, PLAYBOOKS_PLAY_STATUS__C, PLAYBOOKS_STEP_NUMBER__C, PREMIER_SUPPORT_EXPIRATION__C
           , PREMIER_SUPPORT_START_DATE__C, PRIMARY_MS_CONTACT__C, PRODUCTS__C, PRODUCT_VALUES__C, PRODUCT__C, PSE__ADD_BEIS_TO_EXISTING_BATCHES__C, PURCHASE_ORDER__C
           , QUICK_NOTES_AE_UPDATED_ON__C, QUICK_NOTES_AE__C, QUICK_NOTES_BDR__C, RATING, REASON_NOT_IN_REFERENCE_PROGRAM__C, RECORDTYPEID, REFERENCEABLE_CUSTOMER__C
           , REFERENCE_PROGRAM__C, REGIONAL_COVERAGE__C, RENEWAL_DATE__C, RENEWAL_MANAGER__C, SALES_ENGINEER__C, SALES_FOCUS_ACCOUNT__C, SEGMENTATION__C, SHIPPINGCITY
           , SHIPPINGCOUNTRY, SHIPPINGCOUNTRYCODE, SHIPPINGPOSTALCODE, SHIPPINGSTATE, SHIPPINGSTATECODE, SHIPPINGSTREET, SIC, SICDESC, SOLUTION__C, SPECIALIZATION_NOTES__C
           , SPECIAL_ATTENTION_LABEL__C, STATUS__C, SUBSCRIPTION_ATR__C, SUBSCRIPTION_STATUS__C, SUB_INDUSTRY__C, SUB_REGION__C, SUPPORT_ATR__C, SUPPORT_LEVEL_NOTES__C
           , SUPPORT_LEVEL__C, SUPPORT_SERVICE_DETAILS__C, SYSTEMMODSTAMP, TARGET_ACCOUNT__C, TCVV__C, TECHNICAL_SUPPORT__C, TICKERSYMBOL, TOTAL_CERTIFIED_PROFESSIONALS_CLM__C
           , TOTAL_CERTIFIED_PROFESSIONALS_CPQ__C, TOTAL_NUMBER_OF_CERTIFICATIONS__C, TOTAL_OPPORTUNITIES__C, TYPE, ULTIMATE_DUNS__C, VERTICAL__C, WEBSITE, WON_OPPORTUNITIES__C
           , X18_DIGIT_OLD_SFDC_ID__C, X18_DIGIT_SFDC_ID__C, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, HAS_DEFAULT_SHIPPING_ACR__C
           , HAS_DEFAULT_BILLING_ACR__C, INTEGRATION_STATUS__C, ACV_POTENTIAL__C, SPECIAL_ATTENTION__C, DSCORGPKG__EXTERNAL_DISCOVERORG_ID__C, PLATFORM__C, ISCUSTOMERPORTAL
           , DSCORGPKG__FISCAL_YEAR_END__C, ISMIGRATED__C, NO_BDR_CONTACT__C, COMPANY_PARENT_ID__C, INSIDEVIEW_ULTIMATE_PARENT_COMPANY__C, MINTIGO_CLM_BUYING_STAGE__C
           , MINTIGO_CPQ_BUYING_STAGE__C, MINTIGO_QTC_BUYING_STAGE__C, TB_ACCOUNT__C, MINTIGO_LARGE_ACV_RANK__C, MINTIGO_LARGE_ACV_SCORE__C, FORTUNE_1000_COMPANY__C
           , INTENT_FORTUNE_500_PLUS__C, CHURN_DATE__C, ISPARTNER, SHIP_TO_NUM__C, NEXT_CONTRACT_NUMBER__C, LASTUPDATEDATEBYIV__C, BILL_TO_NUM__C, APTTUS_CONFIG2__TAXEXEMPT__C
           , APTTUS_BILLING__EXCLUDEFROMDUNNING__C, APTTUS_CONFIG2__BILLINGDAYOFMONTH__C, MAX_RENEWAL_UPLIFT__C, NUMBER_OF_ACCEPTED_PROPOSALS__C, ACTIVE_MSSA_NUMBER__C
           , APTTUS_BILLING__READYFORINVOICEDATE__C, ACCOUNT_PRIORITY__C, AMS_FTE__C, APTS_ACCOUNT_OWNER_PHONE__C, APTS_ACCOUNT_OWNER_EMAIL__C, APTS_ACCOUNT_OWNER_NAME__C
           , DEAL_DESK_RENEWAL_OPS_NOTES__C, AMS_ASSIST_REQUESTS__C, AMS_FTE__C__FL, TOTAL_ATR__C, RENEWAL_PROCESSED__C, CONGA_CUSTOMER__C, WILL_NOT_RENEW__C
           , TYPE_APPROVAL_PENDING__C, HOLD_TYPE_VALUE_TO_UPDATE_AFTER_APPROVAL__C, DSCORGPKG__DISCOVERORG_CREATED_ON__C, GEO__C, SEGMENT__C, CURRENCY_CONVERSION_RATE__C
           , CONGA_ACCOUNT_ID__C, INSIDEVIEW_REFERESH_NUMBER__C, INSIDEVIEW_ACT_NUMBER__C, PARENT_COMPANY_NAME__C, AT_RISK__C, OVERALL_SCORE__C, COVID_IMPACT__C
           , RENEWAL_PROBABILITY__C, NPS__C, ACCOUNT_FLAG__C, NPS__C__ST, COVID_IMPACT__C__ST, CSM_FORECAST__C, DNBOPTIMIZER__DNBCOMPANYRECORD__C
           , DNBOPTIMIZER__DNB_D_U_N_S_NUMBER__C, DNB_MATCH_SCORE__C, TRANSITION_DATE__C, ANAPLAN_INSIGHT_ANNUAL_REVENUE__C, ANAPLAN_INSIGHT_NUMBER_OF_EMPLOYEES__C
           , AMS_MANAGER__C, TARGET_ANNUAL_INFLUENCED_REVENUE__C, PREVIOUS_ACCOUNT_OWNER_NAME__C, NEW_ACCOUNT_OWNER__C, MANAGED__C, C1_18_DIGIT_SFDC_ID__C
           , ACCOUNT_SOURCE_CUSTOMER__C, ACCOUNTNUMBER, DOZISF__ZOOMINFO_ID__C, DOZISF__ZOOMINFO_LAST_UPDATED__C, DOZISF__ZOOMINFO_FIRST_UPDATED__C
           , PI_CROSS_SELL_SCORE_CONGA_CLM__C, PI_CROSS_SELL_RANK_CONGA_CLM__C, PI_CROSS_SELL_RANK_CONGA_DOCGEN__C, PI_CROSS_SELL_RANK_CONGA_SIGN__C
           , EXECUTIVE_SPONSOR_USER__C, GTM_PLAN__C, PI_CROSS_SELL_SCORECONGA_SIGN__C, PI_CROSS_SELL_SCORE_CONGA_DOCGEN__C, INDUSTRY_SOLUTION_ACCELERATORS__C
           , C1_NEXT_RENEWAL__C, C1_ACCOUNT_CONGA_SIGN_RANK__C, C1_TM_DIVISIONID__C, C1_ACCOUNT_CONGA_COMPOSER_RANK__C, C1_RED_CARE__C, ACCOUNT_ESCALATION_STATUS__C
           , C1_LICENSE_UTILIZATION__C, C1_INTACCT_CUSTOMER_ID__C, C1_ACTIVE_SIGN_MRR__C, C1_ACTIVE_AI_MRR__C, C1_ACCOUNT_CONGA_GRID_RANK__C
           , C1_ACCOUNT_WRITTEN_OFF_TO_BAD_DEBT__C, C1_LEGACY_DIVISION_ID__C, C1_LEGACY_CURRENT_RESELLER_ID__C, C1_ACTIVE_CONTRACTS_MRR__C, C1_ACTIVE_COLLABORATE_MRR__C
           , C1_CUSTOMER_SINCE_DATE_FORMULA__C, C1_ACCOUNT_RANK__C, C1_SBQQ_RENEWALPRICINGMETHOD__C, C1_CURRENT_RESELLER__C, C1_RENEWAL_UPLIFT_CAP__C
           , C1_COMPOSER_LEVEL_1_CERTS__C, C1_HANDLE_WITH_CARE__C, ACCOUNT_ESCALATION_DATE__C, C1_CONTRACTS_CERTS__C, C1_ENGAGIO_STATUS__C, C1_ACCOUNT_COLLABORATE_RANK__C
           , C1_LOGO_ON_WEBSITE__C, C1_ACTIVE_GRID_MRR__C, C1_RED_CARE_OUTCOME__C, C1_HANDLE_WITH_CARE_COMMENT__C, ESCALATION_OWNER__C, C1_COMPOSER_AUTOMATION_CERTS__C
           , C1_ACCOUNT_COURIER_RANK__C, C1_SALESFORCE_INSTANCE__C, C1_CUSTOMER_SUCCESS_MANAGER__C, C1_ACTIVE_ORCHESTRATE_MRR__C, ESCALATION_EXECUTIVE_OWNER__C
           , C1_ACCOUNT_SERVICES_AND_SUPPORT_RANK__C, C1_COMPOSER_LEVEL_2_CERTS__C, C1_OWNER__C, C1_SALESFORCE_ORG_ID_15__C, C1_SF_USERS_TIER__C, C1_CSM_COMMERCIAL_TERMS__C
           , C1_CUSTOMER_SENTIMENT__C, C1_ENGAGIO_ENGAGEMENTMINUTESLAST3MONTHS__C, C1_ACCOUNT_TYPE__C, C1_LEGACY_TERRITORY_MANAGER__C, C1_ACCOUNT_ID__C, C1_HAVE_DOCUSIGN__C
           , C1_ACTIVE_COMPOSER_MRR__C, C1_ENGAGIO_ENGAGEMENTMINUTESLAST7DAYS__C, ESCALATION_CLOSURE_CRITERIA__C, CONGA_INTEGRATION_STATUS__C, C1_TM_RENEWALS_MANAGERID__C
           , C1_ACCOUNT_DELINQUENT_FLAG__C, C1_LEGACY_OWNER__C, C1_ACCOUNT_BATCH_RANK__C, C1_CUSTOMER_HEALTH_FX__C, C1_ACTIVE_COURIER_MRR__C, C1_MINTIGO_HASH__C
           , MATCHED_ACCOUNT__C, C1_RED_CARE_STATUS__C, C1_LEGACY_GEO_ID__C, C1_CUSTOMER_LIKELY_TO__C, C1_ACTIVE_AUTOMATION_MRR__C, C1_OFF_SHORE_OPT_OUT__C
           , C1_MINTIGO_UPDATE_DATETIME__C, C1_GRID_CERTS__C, ACCOUNT_ESCALATION_TYPE__C, C1_INTENT_DOCUMENT_AUTOMATION__C, C1_SIGN_CERTS__C, C1_LEGACY_REGION_ID__C
           , C1_CURRENT_IMPLEMENTATION_PARTNERID__C, C1_ACCOUNT_NAME__C, C1_SUPPORT_LEVEL__C, C1_TEST_ACCOUNT__C, TOTAL_OPPORTUNITIES1__C, C1_LEGACY_SEGMENT_ID__C
           , C1_LEGACY_CURRENT_IMPLEMENTATION_PARTNER__C, C1_ACCOUNT_ORCHESTRATE_RANK__C, C1_PRIMARY_ADOPTION_BLOCKER__C, C1_RED_CARETXT__C, C1_GOLD_LIST_ACCOUNTS__C
           , ESCALATION_SUMMARY__C, C1_LEGACY_TERRITORY_ID__C, C1_SPECIAL_LEGAL_TERMS__C, C1_CS_DIVISION_STAMP__C, C1_ADVANCED_CONTRACTS_CERTS__C, ACCOUNT_ESCALATED_BY__C
           , C1_CUSTOMER_NEEDS__C, REASON_FOR_ACCOUNT_ESCALATION__C, ACCOUNT_LEVEL_PS_OWNER__C, C1_SALESFORCE_USERS__C, C1_LEGACY_CUSTOMER_SUCCESS_MANAGER__C
           , ESCALATION_ACTION_PLAN__C, C1_ACTIVE_MRR_2__C, C1_SALESFORCE_ACCOUNT_ID__C, C1_MINTIGO_TARGETING_PRIORITY__C, DE_ESCALATION_CRITERIA__C, TOTAL_EXPECTED_REVENUE__C
           , A1_SURVIVOR_ACCOUNT_ID__C, ISEXCLUDEDFROMREALIGN, C1_ACTIVE_SUPPORT_MRR__C, C1_BURDENED_MRR__C, C1_CONTRACTS_FOR_SF_CERTS__C, C1_LEGACY_RENEWALS_MANAGER__C
           , C1_SALESFORCE_ACCOUNT_USERS__C, DID_NOT_SURVIVE__C, C1_TM_TERRITORY_MANAGERID__C, C1_INTENT_AUTOMATED_CONTRACT_MANAGEMENT__C, C1_ACTIVE_CONTRACTS_FOR_SF_MRR__C
           , C1_PURCHASING_METHOD__C, C1_BILLABLE_TIME_CURRENT_SUBSCRIPTION__C, C1_SITE_RECORD_EXTERNAL_ID__C, RENEWAL_MODE__C, PI_CROSS_SELL_RANK_APTTUS_CLM__C
           , PI_CROSS_SELL_RANK_APTTUS_QTC__C, PI_CROSS_SELL_SCORE_APTTUS_CLM__C, PI_CROSS_SELL_RANK_APTTUS_CPQ__C, PI_CROSS_SELL_SCORE_APTTUS_QTC__C
           , PI_CROSS_SELL_SCORE_APTTUS_CPQ__C, C1_PARTNERTARGETANNUALINFLUENCED_REVENUE__C
           -- 20201/01/07
           , APTTUS_BILLING__ACTIVE__C  
           -- 2021/01/08 
           , BILLINGLONGITUDE
           , BILLINGLATITUDE
           , BILLINGGEOCODEACCURACY
-- change -- add latest columns  
		, SNAP_LOAD_AT
	FROM
-- change -- update to most recent snap	
		APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1604733784246_1610100423680
union
	SELECT ACCOUNTSOURCE, ACCOUNT_ASSIGNED_ENGINEER__C, ACCOUNT_HISTORY_COMMENTS__C, ACCOUNT_LEGAL_NAME__C, ACCOUNT_REGION__C, ACV__C, AMS_SURVEY__C, ANNUALREVENUE
           , AVERAGE_ACV__C, BDR_ASSIGNED__C, BILLINGCITY, BILLINGCOUNTRY, BILLINGCOUNTRYCODE, BILLINGPOSTALCODE, BILLINGSTATE, BILLINGSTATECODE, BILLINGSTREET
           , BILLING_AP_EMAIL__C, BILLING_CONTACT__C, CLOUDINGOAGENT__BAS__C, CLOUDINGOAGENT__SAS__C, CONTRACT_MANAGEMENT_POSITIONS__C, CREATEDBYID, CREATEDDATE
           , CREATED_BY_AUTOMATION__C, CREDIT_CHECK_NOTES__C, CREDIT_CHECK_OVERRIDE__C, CREDIT_CHECK__C, CREDIT_HOLD__C, CREDIT_LIMIT__C, CRM_DYNAMICS__C, CRM_SALESFORCE__C
           , CURRENCYISOCODE, CUSTOMER_DOCUMENTATION__C, CUSTOMER_MANAGER__C, CUSTOMER_SEGMENT__C, CUSTOMER_SENTIMENT__C, CUSTOMER_SUPPORT_TRANSITION__C, DESCRIPTION
           , DSCORGPKG__DELETEDFROMDISCOVERORG__C, DSCORGPKG__DISCOVERORG_FIRST_UPDATE__C, DSCORGPKG__DISCOVERORG_FULLCOUNTRYNAME__C, DSCORGPKG__DISCOVERORG_ID__C
           , DSCORGPKG__DISCOVERORG_LASTUPDATE__C, DSCORGPKG__DISCOVERORG_STATE_FULL_NAME__C, DSCORGPKG__DO_3YR_EMPLOYEES_GROWTH__C, DSCORGPKG__DO_3YR_SALES_GROWTH__C
           , DSCORGPKG__EXCLUDE_UPDATE__C, DSCORGPKG__FORTUNE_RANK__C, DSCORGPKG__ITORGCHART__C, DSCORGPKG__IT_BUDGET__C, DSCORGPKG__IT_EMPLOYEES__C, DSCORGPKG__LEAD_SOURCE__C
           , DSCORGPKG__NAICS_CODES__C, DSCORGPKG__OWNERSHIP__C, DSCORGPKG__SIC_CODES__C, DUPLICATE_GROUP_ID__C, DYNAMICS_GUID__C, D_U_N_S_NUMBER__C, EFXID__C
           , EMPTORIS_SWAP_TYPE__C, EMPTORIS_SWAP__C, ENGAGIO__ENGAGEDPEOPLE__C, ENGAGIO__ENGAGEMENTMINUTESLAST3MONTHS__C, ENGAGIO__ENGAGEMENTMINUTESLAST7DAYS__C
           , ENGAGIO__FIRSTENGAGEMENTDATE__C, ENGAGIO__MQADATE__C, ENGAGIO__NUMBEROFPEOPLE__C, ENGAGIO__STATUS__C, ENGAGIO__WEBVISITSLAST3MONTHS__C, ERP__C, EXECUTIVE_SPONSOR__C
           , FAX, FFERPCORE__ISBILLINGADDRESSVALIDATED__C, FFERPCORE__ISSHIPPINGADDRESSVALIDATED__C, FFERPCORE__MATERIALIZEDBILLINGADDRESSVALIDATED__C
           , FFERPCORE__MATERIALIZEDSHIPPINGADDRESSVALIDATED__C, FISCAL_YEAR_END__C, FORTUNE_1000_RANK__C, GLOBAL_ULTIMATE_GROUPING_ID__C, GLOBAL_ULTIMATE_PARENT_COMPANY_ID__C
           , GLOBAL_ULTIMATE_PARENT_COMPANY__C, GLOBAL_ULTIMATE_PARENT__C, HIRING_CONTRACT_MANAGEMENT_POSITIONS__C, HOLDING_COMPANY__C, ID, INDUSTRY, INDUSTRY_FOCUS__C
           , INDUSTRY__C, INSIDEVIEW_ID__C, INTENT_AUTOMATED_CONTRACT_MANAGEMENT__C, INTENT_BUSINESS_SALES_ENABLEMENT__C, INTENT_BUSINESS_SALES_SALES_PRODUCTIVITY__C
           , INTENT_COMPLIANCE_GOVERNANCE_CLM__C, INTENT_SALES_CONTRACT_NEGOTIATIONS__C, INTENT_SALES_CPQ__C, INTENT_SALES_PROPOSALS_QUOTES__C
           , INTENT_SALES_PROPOSAL_QUOTE_GENERATION__C, ISDELETED, IV__INSIDEVIEW_CREATED__C, IV__INSIDEVIEW_DATE_LAST_UPDATED__C, IV__INSIDEVIEW_USER_LAST_UPDATED__C
           , LASTACTIVITYDATE, LASTMODIFIEDBYID, LASTMODIFIEDDATE, LASTREFERENCEDDATE, LASTVIEWEDDATE, LAST_CREDIT_CHECKED__C, LATEST_ACCOUNT_STATUS_CHANGE_DATE__C
           , LATEST_ACCOUNT_STATUS__C, LEGACY_OWNER_NAME__C, MANAGED_SERVICES_ENGINEER__C, MANAGED_SERVICES_EXPIRATION__C, MANAGED_SERVICES_HOURS__C, MANAGED_SERVICES_NOTES__C
           , MANAGED_SERVICES_PACKAGE__C, MANAGED_SERVICES_START_DATE__C, MASTERRECORDID, MASTER_FLAG__C, MASTER_ID_ADDRESS__C, MASTER_ID__C, MATCHEDSTATUS__C
           , MINTIGO_ACCOUNT_RANK_CLM__C, MINTIGO_ACCOUNT_RANK_CPQ__C, MINTIGO_ACCOUNT_RANK_QTC__C, MINTIGO_HASH__C, MINTIGO_SCORE_CLM__C, MINTIGO_SCORE_CPQ__C
           , MINTIGO_SCORE_QTC__C, MINTIGO_UPDATE_DATETIME__C, NAICS_CODE__C, NAICS_DESCRIPTION__C, NAME, NS_CUSTOMER_ID__C, NUMBEROFEMPLOYEES, OF_OPEN_OPPORTUNITITES__C
           , ORIGINAL_CONTRACT_DATE__C, OVERALL_HEALTH__C, OWNERID, OWNERSHIP, PARENTID, PARTNER_STATUS__C, PARTNER_TIER__C, PARTNER_TYPE__C, PAYMENT_TERMS__C, PHONE, PHOTOURL
           , PLAYBOOKS_NEXT_STEP_DUE_DATE__C, PLAYBOOKS_PLAY_NAME__C, PLAYBOOKS_PLAY_STATUS__C, PLAYBOOKS_STEP_NUMBER__C, PREMIER_SUPPORT_EXPIRATION__C
           , PREMIER_SUPPORT_START_DATE__C, PRIMARY_MS_CONTACT__C, PRODUCTS__C, PRODUCT_VALUES__C, PRODUCT__C, PSE__ADD_BEIS_TO_EXISTING_BATCHES__C, PURCHASE_ORDER__C
           , QUICK_NOTES_AE_UPDATED_ON__C, QUICK_NOTES_AE__C, QUICK_NOTES_BDR__C, RATING, REASON_NOT_IN_REFERENCE_PROGRAM__C, RECORDTYPEID, REFERENCEABLE_CUSTOMER__C
           , REFERENCE_PROGRAM__C, REGIONAL_COVERAGE__C, RENEWAL_DATE__C, RENEWAL_MANAGER__C, SALES_ENGINEER__C, SALES_FOCUS_ACCOUNT__C, SEGMENTATION__C, SHIPPINGCITY
           , SHIPPINGCOUNTRY, SHIPPINGCOUNTRYCODE, SHIPPINGPOSTALCODE, SHIPPINGSTATE, SHIPPINGSTATECODE, SHIPPINGSTREET, SIC, SICDESC, SOLUTION__C, SPECIALIZATION_NOTES__C
           , SPECIAL_ATTENTION_LABEL__C, STATUS__C, SUBSCRIPTION_ATR__C, SUBSCRIPTION_STATUS__C, SUB_INDUSTRY__C, SUB_REGION__C, SUPPORT_ATR__C, SUPPORT_LEVEL_NOTES__C
           , SUPPORT_LEVEL__C, SUPPORT_SERVICE_DETAILS__C, SYSTEMMODSTAMP, TARGET_ACCOUNT__C, TCVV__C, TECHNICAL_SUPPORT__C, TICKERSYMBOL, TOTAL_CERTIFIED_PROFESSIONALS_CLM__C
           , TOTAL_CERTIFIED_PROFESSIONALS_CPQ__C, TOTAL_NUMBER_OF_CERTIFICATIONS__C, TOTAL_OPPORTUNITIES__C, TYPE, ULTIMATE_DUNS__C, VERTICAL__C, WEBSITE, WON_OPPORTUNITIES__C
           , X18_DIGIT_OLD_SFDC_ID__C, X18_DIGIT_SFDC_ID__C, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, HAS_DEFAULT_SHIPPING_ACR__C
           , HAS_DEFAULT_BILLING_ACR__C, INTEGRATION_STATUS__C, ACV_POTENTIAL__C, SPECIAL_ATTENTION__C, DSCORGPKG__EXTERNAL_DISCOVERORG_ID__C, PLATFORM__C, ISCUSTOMERPORTAL
           , DSCORGPKG__FISCAL_YEAR_END__C, ISMIGRATED__C, NO_BDR_CONTACT__C, COMPANY_PARENT_ID__C, INSIDEVIEW_ULTIMATE_PARENT_COMPANY__C, MINTIGO_CLM_BUYING_STAGE__C
           , MINTIGO_CPQ_BUYING_STAGE__C, MINTIGO_QTC_BUYING_STAGE__C, TB_ACCOUNT__C, MINTIGO_LARGE_ACV_RANK__C, MINTIGO_LARGE_ACV_SCORE__C, FORTUNE_1000_COMPANY__C
           , INTENT_FORTUNE_500_PLUS__C, CHURN_DATE__C, ISPARTNER, SHIP_TO_NUM__C, NEXT_CONTRACT_NUMBER__C, LASTUPDATEDATEBYIV__C, BILL_TO_NUM__C, APTTUS_CONFIG2__TAXEXEMPT__C
           , APTTUS_BILLING__EXCLUDEFROMDUNNING__C, APTTUS_CONFIG2__BILLINGDAYOFMONTH__C, MAX_RENEWAL_UPLIFT__C, NUMBER_OF_ACCEPTED_PROPOSALS__C, ACTIVE_MSSA_NUMBER__C
           , APTTUS_BILLING__READYFORINVOICEDATE__C, ACCOUNT_PRIORITY__C, AMS_FTE__C, APTS_ACCOUNT_OWNER_PHONE__C, APTS_ACCOUNT_OWNER_EMAIL__C, APTS_ACCOUNT_OWNER_NAME__C
           , DEAL_DESK_RENEWAL_OPS_NOTES__C, AMS_ASSIST_REQUESTS__C, AMS_FTE__C__FL, TOTAL_ATR__C, RENEWAL_PROCESSED__C, CONGA_CUSTOMER__C, WILL_NOT_RENEW__C
           , TYPE_APPROVAL_PENDING__C, HOLD_TYPE_VALUE_TO_UPDATE_AFTER_APPROVAL__C, DSCORGPKG__DISCOVERORG_CREATED_ON__C, GEO__C, SEGMENT__C, CURRENCY_CONVERSION_RATE__C
           , CONGA_ACCOUNT_ID__C, INSIDEVIEW_REFERESH_NUMBER__C, INSIDEVIEW_ACT_NUMBER__C, PARENT_COMPANY_NAME__C, AT_RISK__C, OVERALL_SCORE__C, COVID_IMPACT__C
           , RENEWAL_PROBABILITY__C, NPS__C, ACCOUNT_FLAG__C, NPS__C__ST, COVID_IMPACT__C__ST, CSM_FORECAST__C, DNBOPTIMIZER__DNBCOMPANYRECORD__C
           , DNBOPTIMIZER__DNB_D_U_N_S_NUMBER__C, DNB_MATCH_SCORE__C, TRANSITION_DATE__C, ANAPLAN_INSIGHT_ANNUAL_REVENUE__C, ANAPLAN_INSIGHT_NUMBER_OF_EMPLOYEES__C
           , AMS_MANAGER__C, TARGET_ANNUAL_INFLUENCED_REVENUE__C, PREVIOUS_ACCOUNT_OWNER_NAME__C, NEW_ACCOUNT_OWNER__C, MANAGED__C, C1_18_DIGIT_SFDC_ID__C
           , ACCOUNT_SOURCE_CUSTOMER__C, ACCOUNTNUMBER, DOZISF__ZOOMINFO_ID__C, DOZISF__ZOOMINFO_LAST_UPDATED__C, DOZISF__ZOOMINFO_FIRST_UPDATED__C
           , PI_CROSS_SELL_SCORE_CONGA_CLM__C, PI_CROSS_SELL_RANK_CONGA_CLM__C, PI_CROSS_SELL_RANK_CONGA_DOCGEN__C, PI_CROSS_SELL_RANK_CONGA_SIGN__C
           , EXECUTIVE_SPONSOR_USER__C, GTM_PLAN__C, PI_CROSS_SELL_SCORECONGA_SIGN__C, PI_CROSS_SELL_SCORE_CONGA_DOCGEN__C, INDUSTRY_SOLUTION_ACCELERATORS__C
           , C1_NEXT_RENEWAL__C, C1_ACCOUNT_CONGA_SIGN_RANK__C, C1_TM_DIVISIONID__C, C1_ACCOUNT_CONGA_COMPOSER_RANK__C, C1_RED_CARE__C, ACCOUNT_ESCALATION_STATUS__C
           , C1_LICENSE_UTILIZATION__C, C1_INTACCT_CUSTOMER_ID__C, C1_ACTIVE_SIGN_MRR__C, C1_ACTIVE_AI_MRR__C, C1_ACCOUNT_CONGA_GRID_RANK__C
           , C1_ACCOUNT_WRITTEN_OFF_TO_BAD_DEBT__C, C1_LEGACY_DIVISION_ID__C, C1_LEGACY_CURRENT_RESELLER_ID__C, C1_ACTIVE_CONTRACTS_MRR__C, C1_ACTIVE_COLLABORATE_MRR__C
           , C1_CUSTOMER_SINCE_DATE_FORMULA__C, C1_ACCOUNT_RANK__C, C1_SBQQ_RENEWALPRICINGMETHOD__C, C1_CURRENT_RESELLER__C, C1_RENEWAL_UPLIFT_CAP__C
           , C1_COMPOSER_LEVEL_1_CERTS__C, C1_HANDLE_WITH_CARE__C, ACCOUNT_ESCALATION_DATE__C, C1_CONTRACTS_CERTS__C, C1_ENGAGIO_STATUS__C, C1_ACCOUNT_COLLABORATE_RANK__C
           , C1_LOGO_ON_WEBSITE__C, C1_ACTIVE_GRID_MRR__C, C1_RED_CARE_OUTCOME__C, C1_HANDLE_WITH_CARE_COMMENT__C, ESCALATION_OWNER__C, C1_COMPOSER_AUTOMATION_CERTS__C
           , C1_ACCOUNT_COURIER_RANK__C, C1_SALESFORCE_INSTANCE__C, C1_CUSTOMER_SUCCESS_MANAGER__C, C1_ACTIVE_ORCHESTRATE_MRR__C, ESCALATION_EXECUTIVE_OWNER__C
           , C1_ACCOUNT_SERVICES_AND_SUPPORT_RANK__C, C1_COMPOSER_LEVEL_2_CERTS__C, C1_OWNER__C, C1_SALESFORCE_ORG_ID_15__C, C1_SF_USERS_TIER__C, C1_CSM_COMMERCIAL_TERMS__C
           , C1_CUSTOMER_SENTIMENT__C, C1_ENGAGIO_ENGAGEMENTMINUTESLAST3MONTHS__C, C1_ACCOUNT_TYPE__C, C1_LEGACY_TERRITORY_MANAGER__C, C1_ACCOUNT_ID__C, C1_HAVE_DOCUSIGN__C
           , C1_ACTIVE_COMPOSER_MRR__C, C1_ENGAGIO_ENGAGEMENTMINUTESLAST7DAYS__C, ESCALATION_CLOSURE_CRITERIA__C, CONGA_INTEGRATION_STATUS__C, C1_TM_RENEWALS_MANAGERID__C
           , C1_ACCOUNT_DELINQUENT_FLAG__C, C1_LEGACY_OWNER__C, C1_ACCOUNT_BATCH_RANK__C, C1_CUSTOMER_HEALTH_FX__C, C1_ACTIVE_COURIER_MRR__C, C1_MINTIGO_HASH__C
           , MATCHED_ACCOUNT__C, C1_RED_CARE_STATUS__C, C1_LEGACY_GEO_ID__C, C1_CUSTOMER_LIKELY_TO__C, C1_ACTIVE_AUTOMATION_MRR__C, C1_OFF_SHORE_OPT_OUT__C
           , C1_MINTIGO_UPDATE_DATETIME__C, C1_GRID_CERTS__C, ACCOUNT_ESCALATION_TYPE__C, C1_INTENT_DOCUMENT_AUTOMATION__C, C1_SIGN_CERTS__C, C1_LEGACY_REGION_ID__C
           , C1_CURRENT_IMPLEMENTATION_PARTNERID__C, C1_ACCOUNT_NAME__C, C1_SUPPORT_LEVEL__C, C1_TEST_ACCOUNT__C, TOTAL_OPPORTUNITIES1__C, C1_LEGACY_SEGMENT_ID__C
           , C1_LEGACY_CURRENT_IMPLEMENTATION_PARTNER__C, C1_ACCOUNT_ORCHESTRATE_RANK__C, C1_PRIMARY_ADOPTION_BLOCKER__C, C1_RED_CARETXT__C, C1_GOLD_LIST_ACCOUNTS__C
           , ESCALATION_SUMMARY__C, C1_LEGACY_TERRITORY_ID__C, C1_SPECIAL_LEGAL_TERMS__C, C1_CS_DIVISION_STAMP__C, C1_ADVANCED_CONTRACTS_CERTS__C, ACCOUNT_ESCALATED_BY__C
           , C1_CUSTOMER_NEEDS__C, REASON_FOR_ACCOUNT_ESCALATION__C, ACCOUNT_LEVEL_PS_OWNER__C, C1_SALESFORCE_USERS__C, C1_LEGACY_CUSTOMER_SUCCESS_MANAGER__C
           , ESCALATION_ACTION_PLAN__C, C1_ACTIVE_MRR_2__C, C1_SALESFORCE_ACCOUNT_ID__C, C1_MINTIGO_TARGETING_PRIORITY__C, DE_ESCALATION_CRITERIA__C, TOTAL_EXPECTED_REVENUE__C
           , A1_SURVIVOR_ACCOUNT_ID__C, ISEXCLUDEDFROMREALIGN, C1_ACTIVE_SUPPORT_MRR__C, C1_BURDENED_MRR__C, C1_CONTRACTS_FOR_SF_CERTS__C, C1_LEGACY_RENEWALS_MANAGER__C
           , C1_SALESFORCE_ACCOUNT_USERS__C, DID_NOT_SURVIVE__C, C1_TM_TERRITORY_MANAGERID__C, C1_INTENT_AUTOMATED_CONTRACT_MANAGEMENT__C, C1_ACTIVE_CONTRACTS_FOR_SF_MRR__C
           , C1_PURCHASING_METHOD__C, C1_BILLABLE_TIME_CURRENT_SUBSCRIPTION__C, C1_SITE_RECORD_EXTERNAL_ID__C, RENEWAL_MODE__C, PI_CROSS_SELL_RANK_APTTUS_CLM__C
           , PI_CROSS_SELL_RANK_APTTUS_QTC__C, PI_CROSS_SELL_SCORE_APTTUS_CLM__C, PI_CROSS_SELL_RANK_APTTUS_CPQ__C, PI_CROSS_SELL_SCORE_APTTUS_QTC__C
           , PI_CROSS_SELL_SCORE_APTTUS_CPQ__C, C1_PARTNERTARGETANNUALINFLUENCED_REVENUE__C
           -- 20201/01/07
           , APTTUS_BILLING__ACTIVE__C  
           -- 2021/01/08 
           , NULL AS BILLINGLONGITUDE
           , NULL AS BILLINGLATITUDE
           , NULL AS BILLINGGEOCODEACCURACY            
-- change -- remove NULL AS from previous round
-- change -- ADD newest Columns as NULL AS  
          , SNAP_LOAD_AT
	FROM
		APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_SNAP_1
)
, the_unique AS (
	SELECT ID
         , _SDC_EXTRACTED_AT 
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY ID
         , _SDC_EXTRACTED_AT 
)
	SELECT A.*, dateadd(day, -1, to_date(A."_SDC_EXTRACTED_AT")) AS ACTIVITY_DATE
	FROM                 the_union A
	INNER JOIN           the_unique B
	             ON  A.ID = B.ID
	             AND A._SDC_EXTRACTED_AT = B._SDC_EXTRACTED_AT
	             AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;

-- RUN duplicate detector to be sure you haven't created duplicates in History View
SELECT COUNT(*) 
     , ID
     , _SDC_EXTRACTED_AT     
FROM APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_HISTORY
group by ID
     , _SDC_EXTRACTED_AT 
having count(*) > 1     
-- 0 needs to always come out as zero
;

select count(distinct ID)
FROM APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_HISTORY
--  267111
;

select count(distinct ID, _SDC_EXTRACTED_AT)
FROM APTTUS_DW.SNAPSHOTS.ACCOUNT_A1_HISTORY
--  587092
; 