CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.ASSET_C1_HISTORY  
COMMENT = 'Union ASSET_C1 snapshots to make complete history'
AS 
WITH the_union AS (
SELECT
	ACCOUNTID
	, ACCOUNTING_STAGE__C
	, ACQUIRED__C
	, ASSETLEVEL
	, AVERAGE_MRRFX__C
	, BILLING_PARTY__C
	, CONTACTID
	, CREATEDBYID
	, CREATEDDATE
	, CRMC_ORG_ASSET_ID__C
	, DESCRIPTION
	, END_DATE__C
	, ENTITLEMENT_STATUS__C
	, ENTITY_CODE__C
	, ENVIRONMENTID__C
	, HAS_FEB_LEAP_YEAR_DAY__C
	, HAS_LEAP_YEAR_DAY__C
	, ID
	, INDIRECT_ASSET__C
	, INSTALLDATE
	, ISCOMPETITORPRODUCT
	, ISDELETED
	, ISINTERNAL
	, LASTMODIFIEDBYID
	, LASTMODIFIEDDATE
	, MRR_ASSET_MRR__C
	, "NAME"
	, OLI_ID__C
	, OPPTY_RECORD_TYPE__C
	, ORDER_RECEIVED__C
	, ORGID18__C
	, ORG_ID__C
	, OWNERID
	, PRICE
	, PRODUCT2ID
	, PRODUCTCODE
	, PRODUCT_FAMILY__C
	, PRODUCT_ID__C
	, PROVISIONING_PROVIDER__C
	, PROVISIONING_STATUS__C
	, PURCHASEDATE
	, QUANTITY
	, RECORDTYPEID
	, RELATED_OPPTY__C
	, RESELLER__C
	, REVENUE_CATEGORY__C
	, ROOTASSETID
	, SALESFORCE_ACCOUNT__C
	, SALESFORCE_INSTANCE__C
	, SALESFORCE_ORG__C
	, SALES_OPS_APPROVED__C
	, SFDC_ORG_ID_18__C
	, SFDC_ORG_ID__C
	, START_DATE__C
	, STATUS
	, SYSTEMMODSTAMP
	, TOTAL_PROVISIONED_BY_RESELLER__C
	, TOTAL_REMAINING_TO_RESELLER__C
	, TYPE__C
	, USAGEENDDATE
	, "_SDC_BATCHED_AT"
	, "_SDC_EXTRACTED_AT"
	, "_SDC_RECEIVED_AT"
	, "_SDC_SEQUENCE"
	, "_SDC_TABLE_VERSION"
	, LASTREFERENCEDDATE
	, LASTVIEWEDDATE
	, SNAP_LOAD_AT
FROM
	APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1595529536375_1600187700766
UNION
SELECT
	ACCOUNTID
	, ACCOUNTING_STAGE__C
	, ACQUIRED__C
	, ASSETLEVEL
	, AVERAGE_MRRFX__C
	, BILLING_PARTY__C
	, CONTACTID
	, CREATEDBYID
	, CREATEDDATE
	, CRMC_ORG_ASSET_ID__C
	, DESCRIPTION
	, END_DATE__C
	, ENTITLEMENT_STATUS__C
	, ENTITY_CODE__C
	, ENVIRONMENTID__C
	, HAS_FEB_LEAP_YEAR_DAY__C
	, HAS_LEAP_YEAR_DAY__C
	, ID
	, INDIRECT_ASSET__C
	, INSTALLDATE
	, ISCOMPETITORPRODUCT
	, ISDELETED
	, ISINTERNAL
	, LASTMODIFIEDBYID
	, LASTMODIFIEDDATE
	, MRR_ASSET_MRR__C
	, "NAME"
	, OLI_ID__C
	, OPPTY_RECORD_TYPE__C
	, ORDER_RECEIVED__C
	, ORGID18__C
	, ORG_ID__C
	, OWNERID
	, PRICE
	, PRODUCT2ID
	, PRODUCTCODE
	, PRODUCT_FAMILY__C
	, PRODUCT_ID__C
	, PROVISIONING_PROVIDER__C
	, PROVISIONING_STATUS__C
	, PURCHASEDATE
	, QUANTITY
	, RECORDTYPEID
	, RELATED_OPPTY__C
	, RESELLER__C
	, REVENUE_CATEGORY__C
	, ROOTASSETID
	, SALESFORCE_ACCOUNT__C
	, SALESFORCE_INSTANCE__C
	, SALESFORCE_ORG__C
	, SALES_OPS_APPROVED__C
	, SFDC_ORG_ID_18__C
	, SFDC_ORG_ID__C
	, START_DATE__C
	, STATUS
	, SYSTEMMODSTAMP
	, TOTAL_PROVISIONED_BY_RESELLER__C
	, TOTAL_REMAINING_TO_RESELLER__C
	, TYPE__C
	, USAGEENDDATE
	, "_SDC_BATCHED_AT"
	, "_SDC_EXTRACTED_AT"
	, "_SDC_RECEIVED_AT"
	, "_SDC_SEQUENCE"
	, "_SDC_TABLE_VERSION"
	, LASTREFERENCEDDATE
	, LASTVIEWEDDATE
	, SNAP_LOAD_AT
FROM
	APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1
)	
, the_unique AS (
	SELECT ID
         , _SDC_EXTRACTED_AT 
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY ID
         , _SDC_EXTRACTED_AT 
)
	SELECT A.*
	     , to_date(SYSTEMMODSTAMP) AS ACTIVITY_DATE
	     , dateadd(day, -1, to_date(A."_SDC_EXTRACTED_AT")) AS EXTRACT_DATE
	     , dateadd(day, -1, to_date(A."SNAP_LOAD_AT")) AS REPORTING_DATE	     
	FROM                 the_union A
	INNER JOIN           the_unique B
	             ON  A.ID = B.ID
	             AND A._SDC_EXTRACTED_AT = B._SDC_EXTRACTED_AT
	             AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;

