SELECT CURRENT_ROLE();

Select TABLE_CATALOG||'.'||TABLE_SCHEMA||'.'||TABLE_NAME, MAX(ORDINAL_POSITION)
 FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME LIKE 'ASSET_C1_SNAP%'
 GROUP by TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
 order by 1
; 

with get_last as(
        Select MAX(ORDINAL_POSITION) as LAST_COL
         FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_NAME = 'ASSET_C1_SNAP_1'
)
Select TABLE_CATALOG||'.'||TABLE_SCHEMA||'.'||TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME
 FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME LIKE 'ASSET_C1_SNAP%'
   AND ORDINAL_POSITION > ((SELECT LAST_COL from get_last)-1)
   AND COLUMN_NAME <> 'SNAP_LOAD_AT'
ORDER by 1, 2
;  

Select TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION
FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE 'ASSET_C1_SNAP%'
ORDER BY ORDINAL_POSITION, TABLE_NAME 
;

select count(*) from APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1;
select count(*) from APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1604748388985_1604764934714;
select count(*) from APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1604748388985_1609927513997;
select count(*) from APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1604748388985_1610013913184;

-- CHANGE -- uncommend insert and update table name to previous snap
-- CHANGE -- manage columns near bottom
INSERT INTO APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1604748388985_1609927513997
      (ACCOUNTID, ACCOUNTING_STAGE__C, ACQUIRED__C, ASSETLEVEL, AVERAGE_MRRFX__C, BILLING_PARTY__C
     , CONTACTID, CREATEDBYID, CREATEDDATE, CRMC_ORG_ASSET_ID__C, DESCRIPTION, END_DATE__C
     , ENTITLEMENT_STATUS__C, ENTITY_CODE__C, ENVIRONMENTID__C, HAS_FEB_LEAP_YEAR_DAY__C
     , HAS_LEAP_YEAR_DAY__C, ID, INDIRECT_ASSET__C, INSTALLDATE, ISCOMPETITORPRODUCT, ISDELETED
     , ISINTERNAL, LASTMODIFIEDBYID, LASTMODIFIEDDATE, MRR_ASSET_MRR__C, NAME, OLI_ID__C
     , OPPTY_RECORD_TYPE__C, ORDER_RECEIVED__C, ORGID18__C, ORG_ID__C, OWNERID, PRICE, PRODUCT2ID
     , PRODUCTCODE, PRODUCT_FAMILY__C, PRODUCT_ID__C, PROVISIONING_PROVIDER__C, PROVISIONING_STATUS__C
     , PURCHASEDATE, QUANTITY, RECORDTYPEID, RELATED_OPPTY__C, RESELLER__C, REVENUE_CATEGORY__C
     , ROOTASSETID, SALESFORCE_ACCOUNT__C, SALESFORCE_INSTANCE__C, SALESFORCE_ORG__C, SALES_OPS_APPROVED__C
     , SFDC_ORG_ID_18__C, SFDC_ORG_ID__C, START_DATE__C, STATUS, SYSTEMMODSTAMP, TOTAL_PROVISIONED_BY_RESELLER__C
     , TOTAL_REMAINING_TO_RESELLER__C, TYPE__C, USAGEENDDATE, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT
     , _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, LASTREFERENCEDDATE, LASTVIEWEDDATE
     -- 2021/01/06
     , SBQQ__BUNDLE__C, SBQQ__COMPONENTDISCOUNTEDBYPACKAGE__C, SBQQ__FROMSERVICECLOUD__C
     , SBQQ__BUNDLED__C, SBQQ__ROOTID__C
     --
     , SNAP_LOAD_AT) 
SELECT ACCOUNTID, ACCOUNTING_STAGE__C, ACQUIRED__C, ASSETLEVEL, AVERAGE_MRRFX__C, BILLING_PARTY__C
     , CONTACTID, CREATEDBYID, CREATEDDATE, CRMC_ORG_ASSET_ID__C, DESCRIPTION, END_DATE__C
     , ENTITLEMENT_STATUS__C, ENTITY_CODE__C, ENVIRONMENTID__C, HAS_FEB_LEAP_YEAR_DAY__C
     , HAS_LEAP_YEAR_DAY__C, ID, INDIRECT_ASSET__C, INSTALLDATE, ISCOMPETITORPRODUCT, ISDELETED
     , ISINTERNAL, LASTMODIFIEDBYID, LASTMODIFIEDDATE, MRR_ASSET_MRR__C, NAME, OLI_ID__C
     , OPPTY_RECORD_TYPE__C, ORDER_RECEIVED__C, ORGID18__C, ORG_ID__C, OWNERID, PRICE, PRODUCT2ID
     , PRODUCTCODE, PRODUCT_FAMILY__C, PRODUCT_ID__C, PROVISIONING_PROVIDER__C, PROVISIONING_STATUS__C
     , PURCHASEDATE, QUANTITY, RECORDTYPEID, RELATED_OPPTY__C, RESELLER__C, REVENUE_CATEGORY__C
     , ROOTASSETID, SALESFORCE_ACCOUNT__C, SALESFORCE_INSTANCE__C, SALESFORCE_ORG__C, SALES_OPS_APPROVED__C
     , SFDC_ORG_ID_18__C, SFDC_ORG_ID__C, START_DATE__C, STATUS, SYSTEMMODSTAMP, TOTAL_PROVISIONED_BY_RESELLER__C
     , TOTAL_REMAINING_TO_RESELLER__C, TYPE__C, USAGEENDDATE, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT
     , _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, LASTREFERENCEDDATE, LASTVIEWEDDATE
     , NULL AS SBQQ__BUNDLE__C, NULL AS SBQQ__COMPONENTDISCOUNTEDBYPACKAGE__C, NULL AS SBQQ__FROMSERVICECLOUD__C
     , NULL AS SBQQ__BUNDLED__C, NULL AS SBQQ__ROOTID__C     
-- change -- remove older NULL AS from column
-- change -- add columns from the previous snap iteration as NULL AS 
     , SNAP_LOAD_AT 
FROM APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1;

-- change -- check counts to insure that the recently replaced snap now has all rows
DROP TABLE APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_PRIOR;
ALTER TABLE APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1 rename to APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_PRIOR;
-- change first snap to be the recently replaced 
alter table APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1604748388985_1609927513997 rename to APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1;
select count(*) from APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1;

-- make changes below and then rebuild the history
CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.ASSET_C1_HISTORY  
COMMENT = 'Union ASSET_C1 snapshots to make complete history'
AS 
WITH the_union AS (
SELECT ACCOUNTID, ACCOUNTING_STAGE__C, ACQUIRED__C, ASSETLEVEL, AVERAGE_MRRFX__C, BILLING_PARTY__C
     , CONTACTID, CREATEDBYID, CREATEDDATE, CRMC_ORG_ASSET_ID__C, DESCRIPTION, END_DATE__C
     , ENTITLEMENT_STATUS__C, ENTITY_CODE__C, ENVIRONMENTID__C, HAS_FEB_LEAP_YEAR_DAY__C
     , HAS_LEAP_YEAR_DAY__C, ID, INDIRECT_ASSET__C, INSTALLDATE, ISCOMPETITORPRODUCT, ISDELETED
     , ISINTERNAL, LASTMODIFIEDBYID, LASTMODIFIEDDATE, MRR_ASSET_MRR__C, NAME, OLI_ID__C
     , OPPTY_RECORD_TYPE__C, ORDER_RECEIVED__C, ORGID18__C, ORG_ID__C, OWNERID, PRICE, PRODUCT2ID
     , PRODUCTCODE, PRODUCT_FAMILY__C, PRODUCT_ID__C, PROVISIONING_PROVIDER__C, PROVISIONING_STATUS__C
     , PURCHASEDATE, QUANTITY, RECORDTYPEID, RELATED_OPPTY__C, RESELLER__C, REVENUE_CATEGORY__C
     , ROOTASSETID, SALESFORCE_ACCOUNT__C, SALESFORCE_INSTANCE__C, SALESFORCE_ORG__C, SALES_OPS_APPROVED__C
     , SFDC_ORG_ID_18__C, SFDC_ORG_ID__C, START_DATE__C, STATUS, SYSTEMMODSTAMP, TOTAL_PROVISIONED_BY_RESELLER__C
     , TOTAL_REMAINING_TO_RESELLER__C, TYPE__C, USAGEENDDATE, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT
     , _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, LASTREFERENCEDDATE, LASTVIEWEDDATE
     -- update 1
     , SBQQ__BUNDLE__C, SBQQ__COMPONENTDISCOUNTEDBYPACKAGE__C, SBQQ__FROMSERVICECLOUD__C
     , SBQQ__BUNDLED__C, SBQQ__ROOTID__C 
     -- update 2021/01/07   
     , SBQQ__LISTPRICE__C, SBQQ__PRICINGMETHOD__C, SBQQ__SUBSCRIPTIONSTARTDATE__C, SBQQ__OPTIONLEVEL__C
     , SBQQ__OPTIONTYPE__C, SBQQ__REQUIREDBYSUBSCRIPTION__C, SBQQ__REQUIREDBYPRODUCT__C, SBQQ__QUOTELINE__C
     , SBQQ__COMBINEKEY__C, SBQQ__NUMBER__C, SBQQ__REGULARPRICE__C, SBQQ__PRODUCTOPTION__C, SBQQ__SUBSCRIPTIONENDDATE__C
     , SBQQ__DYNAMICOPTIONID__C, SBQQ__LATESTQUOTELINE__C	
-- change -- add latest columns  
	, SNAP_LOAD_AT
FROM
-- change -- update to most recent snap	
        APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1604748388985_1610013913184
UNION
SELECT ACCOUNTID, ACCOUNTING_STAGE__C, ACQUIRED__C, ASSETLEVEL, AVERAGE_MRRFX__C, BILLING_PARTY__C
     , CONTACTID, CREATEDBYID, CREATEDDATE, CRMC_ORG_ASSET_ID__C, DESCRIPTION, END_DATE__C
     , ENTITLEMENT_STATUS__C, ENTITY_CODE__C, ENVIRONMENTID__C, HAS_FEB_LEAP_YEAR_DAY__C
     , HAS_LEAP_YEAR_DAY__C, ID, INDIRECT_ASSET__C, INSTALLDATE, ISCOMPETITORPRODUCT, ISDELETED
     , ISINTERNAL, LASTMODIFIEDBYID, LASTMODIFIEDDATE, MRR_ASSET_MRR__C, NAME, OLI_ID__C
     , OPPTY_RECORD_TYPE__C, ORDER_RECEIVED__C, ORGID18__C, ORG_ID__C, OWNERID, PRICE, PRODUCT2ID
     , PRODUCTCODE, PRODUCT_FAMILY__C, PRODUCT_ID__C, PROVISIONING_PROVIDER__C, PROVISIONING_STATUS__C
     , PURCHASEDATE, QUANTITY, RECORDTYPEID, RELATED_OPPTY__C, RESELLER__C, REVENUE_CATEGORY__C
     , ROOTASSETID, SALESFORCE_ACCOUNT__C, SALESFORCE_INSTANCE__C, SALESFORCE_ORG__C, SALES_OPS_APPROVED__C
     , SFDC_ORG_ID_18__C, SFDC_ORG_ID__C, START_DATE__C, STATUS, SYSTEMMODSTAMP, TOTAL_PROVISIONED_BY_RESELLER__C
     , TOTAL_REMAINING_TO_RESELLER__C, TYPE__C, USAGEENDDATE, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT
     , _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, LASTREFERENCEDDATE, LASTVIEWEDDATE
     -- update 1
     , SBQQ__BUNDLE__C, SBQQ__COMPONENTDISCOUNTEDBYPACKAGE__C, SBQQ__FROMSERVICECLOUD__C
     , SBQQ__BUNDLED__C, SBQQ__ROOTID__C 
     -- update 2021/01/07   
     , NULL AS SBQQ__LISTPRICE__C, NULL AS SBQQ__PRICINGMETHOD__C, NULL AS SBQQ__SUBSCRIPTIONSTARTDATE__C, NULL AS SBQQ__OPTIONLEVEL__C
     , NULL AS SBQQ__OPTIONTYPE__C, NULL AS SBQQ__REQUIREDBYSUBSCRIPTION__C, NULL AS SBQQ__REQUIREDBYPRODUCT__C, NULL AS SBQQ__QUOTELINE__C
     , NULL AS SBQQ__COMBINEKEY__C, NULL AS SBQQ__NUMBER__C, NULL AS SBQQ__REGULARPRICE__C, NULL AS SBQQ__PRODUCTOPTION__C, NULL AS SBQQ__SUBSCRIPTIONENDDATE__C
     , NULL AS SBQQ__DYNAMICOPTIONID__C, NULL AS SBQQ__LATESTQUOTELINE__C
-- change -- remove NULL AS from previous round
-- change -- ADD newest Columns as NULL AS  
	, SNAP_LOAD_AT
FROM
	APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_1
)	
, the_unique AS (
	SELECT ID
         , _SDC_EXTRACTED_AT 
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY ID
         , _SDC_EXTRACTED_AT 
)
	SELECT A.*
	     , to_date(SYSTEMMODSTAMP) AS ACTIVITY_DATE
	     , dateadd(day, -1, to_date(A."_SDC_EXTRACTED_AT")) AS EXTRACT_DATE
	     , dateadd(day, -1, to_date(A."SNAP_LOAD_AT")) AS REPORTING_DATE	     
	FROM                 the_union A
	INNER JOIN           the_unique B
	             ON  A.ID = B.ID
	             AND A._SDC_EXTRACTED_AT = B._SDC_EXTRACTED_AT
	             AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;

-- RUN duplicate detector to be sure you haven't created duplicates in History View
SELECT count(*)
     , ID
     , _SDC_EXTRACTED_AT 
FROM APTTUS_DW.SNAPSHOTS.ASSET_C1_HISTORY
group by ID
       , _SDC_EXTRACTED_AT 
having count(*) > 1
 -- 0
;
select count(distinct ID)
FROM APTTUS_DW.SNAPSHOTS.ASSET_C1_HISTORY
 -- 157807
;
select count(distinct ID, _SDC_EXTRACTED_AT)
FROM APTTUS_DW.SNAPSHOTS.ASSET_C1_HISTORY
 -- 542389
;