SELECT CURRENT_ROLE();

Select TABLE_CATALOG||'.'||TABLE_SCHEMA||'.'||TABLE_NAME, MAX(ORDINAL_POSITION)
 FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME LIKE 'ASSETLINEITEM_SNAP%'
 GROUP by TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
 order by 1
; 

with get_last as(
        Select MAX(ORDINAL_POSITION) as LAST_COL
         FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_NAME = 'ASSETLINEITEM_SNAP_1'
)
Select TABLE_CATALOG||'.'||TABLE_SCHEMA||'.'||TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME
 FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME LIKE 'ASSETLINEITEM_SNAP%'
   AND ORDINAL_POSITION > ((SELECT LAST_COL from get_last)-1)
   AND COLUMN_NAME <> 'SNAP_LOAD_AT'
;  

Select TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION
FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE 'ASSETLINEITEM_SNAP%'
ORDER BY ORDINAL_POSITION, TABLE_NAME 
;

select count(*) from APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1;
select count(*) from APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1604728034695_1606319140742;
select count(*) from APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1604728034695_1606319140742;


-- CHANGE -- uncommend insert and update table name to previous snap
-- CHANGE -- manage columns near bottom
INSERT INTO APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1604728034695_1606319140742
     ( ACV__C, APTTUS_CONFIG2__ACCOUNTID__C, APTTUS_CONFIG2__ADJUSTEDPRICE__C, APTTUS_CONFIG2__ALLOWEDACTIONS__C
     , APTTUS_CONFIG2__ASSETNUMBER__C, APTTUS_CONFIG2__ASSETSTATUS__C, APTTUS_CONFIG2__ASSETTCV__C, APTTUS_CONFIG2__ATTRIBUTEVALUEID__C
     , APTTUS_CONFIG2__AUTORENEWALTYPE__C, APTTUS_CONFIG2__AUTORENEW__C, APTTUS_CONFIG2__AVAILABLEBALANCE__C, APTTUS_CONFIG2__BASECOST__C
     , APTTUS_CONFIG2__BASEEXTENDEDCOST__C, APTTUS_CONFIG2__BASEEXTENDEDPRICE__C, APTTUS_CONFIG2__BASEPRICEMETHOD__C, APTTUS_CONFIG2__BASEPRICE__C
     , APTTUS_CONFIG2__BILLINGENDDATE__C, APTTUS_CONFIG2__BILLINGFREQUENCY__C, APTTUS_CONFIG2__BILLINGPREFERENCEID__C, APTTUS_CONFIG2__BILLINGRULE__C
     , APTTUS_CONFIG2__BILLINGSTARTDATE__C, APTTUS_CONFIG2__BILLTOACCOUNTID__C, APTTUS_CONFIG2__BUNDLEASSETID__C, APTTUS_CONFIG2__BUSINESSLINEITEMID__C
     , APTTUS_CONFIG2__BUSINESSOBJECTID__C, APTTUS_CONFIG2__BUSINESSOBJECTTYPE__C, APTTUS_CONFIG2__CANCELLEDDATE__C, APTTUS_CONFIG2__CHARGETYPE__C
     , APTTUS_CONFIG2__COMMENTS__C, APTTUS_CONFIG2__CURRENTCONTRACTSTARTDATE__C, APTTUS_CONFIG2__CURRENTCONTRACTTERM__C
     , APTTUS_CONFIG2__CURRENTCONTRACTUNITPRICE__C, APTTUS_CONFIG2__CURRENTCONTRACTVALUE__C, APTTUS_CONFIG2__DELTAPRICE__C
     , APTTUS_CONFIG2__DELTAQUANTITY__C, APTTUS_CONFIG2__DESCRIPTION__C, APTTUS_CONFIG2__ENDDATE__C, APTTUS_CONFIG2__EXTENDEDCOST__C
     , APTTUS_CONFIG2__EXTENDEDPRICE__C, APTTUS_CONFIG2__FREQUENCY__C, APTTUS_CONFIG2__HASATTRIBUTES__C, APTTUS_CONFIG2__HASOPTIONS__C
     , APTTUS_CONFIG2__HIDEINVOICEDISPLAY__C, APTTUS_CONFIG2__ISINACTIVE__C, APTTUS_CONFIG2__ISOPTIONROLLUPLINE__C, APTTUS_CONFIG2__ISPRIMARYLINE__C
     , APTTUS_CONFIG2__ISPRIMARYRAMPLINE__C, APTTUS_CONFIG2__ISPRIMARYSERVICE__C, APTTUS_CONFIG2__ISREADONLY__C, APTTUS_CONFIG2__ISRENEWALPENDING__C
     , APTTUS_CONFIG2__ISRENEWED__C, APTTUS_CONFIG2__ISUSAGETIERMODIFIABLE__C, APTTUS_CONFIG2__ITEMSEQUENCE__C, APTTUS_CONFIG2__LASTRENEWENDDATE__C
     , APTTUS_CONFIG2__LINENUMBER__C, APTTUS_CONFIG2__LINETYPE__C, APTTUS_CONFIG2__LISTPRICE__C, APTTUS_CONFIG2__MUSTUPGRADE__C, APTTUS_CONFIG2__NETPRICE__C
     , APTTUS_CONFIG2__NETUNITPRICE__C, APTTUS_CONFIG2__OPTIONCOST__C, APTTUS_CONFIG2__OPTIONID__C, APTTUS_CONFIG2__OPTIONPRICE__C
     , APTTUS_CONFIG2__ORIGINALSTARTDATE__C, APTTUS_CONFIG2__PARENTASSETID__C, APTTUS_CONFIG2__PARENTBUNDLENUMBER__C, APTTUS_CONFIG2__PRICEGROUP__C
     , APTTUS_CONFIG2__PRICEINCLUDEDINBUNDLE__C, APTTUS_CONFIG2__PRICELISTID__C, APTTUS_CONFIG2__PRICELISTITEMID__C, APTTUS_CONFIG2__PRICEMETHOD__C
     , APTTUS_CONFIG2__PRICETYPE__C, APTTUS_CONFIG2__PRICEUOM__C, APTTUS_CONFIG2__PRIMARYLINENUMBER__C, APTTUS_CONFIG2__PRODUCTID__C
     , APTTUS_CONFIG2__PRODUCTTYPE__C, APTTUS_CONFIG2__QUANTITY__C, APTTUS_CONFIG2__RENEWALFREQUENCY__C, APTTUS_CONFIG2__RENEWALTERM__C
     , APTTUS_CONFIG2__SELLINGFREQUENCY__C, APTTUS_CONFIG2__SELLINGTERM__C, APTTUS_CONFIG2__SELLINGUOM__C, APTTUS_CONFIG2__SHIPTOACCOUNTID__C
     , APTTUS_CONFIG2__STARTDATE__C, APTTUS_CONFIG2__TAXABLE__C, APTTUS_CONFIG2__TAXINCLUSIVE__C, APTTUS_CONFIG2__TERM__C, APTTUS_CONFIG2__TOTALBALANCE__C
     , APTTUS_QPCONFIG__PROPOSALID__C, APTTUS_QPCONFIG__PROPOSALLINEITEMID__C, BUNDLE_END_DATE_PAST_DUE__C, CREATEDBYID, CREATEDDATE, CURRENCYISOCODE
     , DELETE_FLAG__C, ID, ISDELETED, LASTMODIFIEDBYID, LASTMODIFIEDDATE, NAME, ORDER_FORM__C, OWNERID, PRODUCT_FAMILY__C
     , SYSTEMMODSTAMP, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, PROJECT_COLORADO_UPDATE__C, TURBO_ENGINE_CLASS__C
     , SNAP_LOAD_AT) 
SELECT ACV__C, APTTUS_CONFIG2__ACCOUNTID__C, APTTUS_CONFIG2__ADJUSTEDPRICE__C, APTTUS_CONFIG2__ALLOWEDACTIONS__C
     , APTTUS_CONFIG2__ASSETNUMBER__C, APTTUS_CONFIG2__ASSETSTATUS__C, APTTUS_CONFIG2__ASSETTCV__C, APTTUS_CONFIG2__ATTRIBUTEVALUEID__C
     , APTTUS_CONFIG2__AUTORENEWALTYPE__C, APTTUS_CONFIG2__AUTORENEW__C, APTTUS_CONFIG2__AVAILABLEBALANCE__C, APTTUS_CONFIG2__BASECOST__C
     , APTTUS_CONFIG2__BASEEXTENDEDCOST__C, APTTUS_CONFIG2__BASEEXTENDEDPRICE__C, APTTUS_CONFIG2__BASEPRICEMETHOD__C, APTTUS_CONFIG2__BASEPRICE__C
     , APTTUS_CONFIG2__BILLINGENDDATE__C, APTTUS_CONFIG2__BILLINGFREQUENCY__C, APTTUS_CONFIG2__BILLINGPREFERENCEID__C, APTTUS_CONFIG2__BILLINGRULE__C
     , APTTUS_CONFIG2__BILLINGSTARTDATE__C, APTTUS_CONFIG2__BILLTOACCOUNTID__C, APTTUS_CONFIG2__BUNDLEASSETID__C, APTTUS_CONFIG2__BUSINESSLINEITEMID__C
     , APTTUS_CONFIG2__BUSINESSOBJECTID__C, APTTUS_CONFIG2__BUSINESSOBJECTTYPE__C, APTTUS_CONFIG2__CANCELLEDDATE__C, APTTUS_CONFIG2__CHARGETYPE__C
     , APTTUS_CONFIG2__COMMENTS__C, APTTUS_CONFIG2__CURRENTCONTRACTSTARTDATE__C, APTTUS_CONFIG2__CURRENTCONTRACTTERM__C
     , APTTUS_CONFIG2__CURRENTCONTRACTUNITPRICE__C, APTTUS_CONFIG2__CURRENTCONTRACTVALUE__C, APTTUS_CONFIG2__DELTAPRICE__C
     , APTTUS_CONFIG2__DELTAQUANTITY__C, APTTUS_CONFIG2__DESCRIPTION__C, APTTUS_CONFIG2__ENDDATE__C, APTTUS_CONFIG2__EXTENDEDCOST__C
     , APTTUS_CONFIG2__EXTENDEDPRICE__C, APTTUS_CONFIG2__FREQUENCY__C, APTTUS_CONFIG2__HASATTRIBUTES__C, APTTUS_CONFIG2__HASOPTIONS__C
     , APTTUS_CONFIG2__HIDEINVOICEDISPLAY__C, APTTUS_CONFIG2__ISINACTIVE__C, APTTUS_CONFIG2__ISOPTIONROLLUPLINE__C, APTTUS_CONFIG2__ISPRIMARYLINE__C
     , APTTUS_CONFIG2__ISPRIMARYRAMPLINE__C, APTTUS_CONFIG2__ISPRIMARYSERVICE__C, APTTUS_CONFIG2__ISREADONLY__C, APTTUS_CONFIG2__ISRENEWALPENDING__C
     , APTTUS_CONFIG2__ISRENEWED__C, APTTUS_CONFIG2__ISUSAGETIERMODIFIABLE__C, APTTUS_CONFIG2__ITEMSEQUENCE__C, APTTUS_CONFIG2__LASTRENEWENDDATE__C
     , APTTUS_CONFIG2__LINENUMBER__C, APTTUS_CONFIG2__LINETYPE__C, APTTUS_CONFIG2__LISTPRICE__C, APTTUS_CONFIG2__MUSTUPGRADE__C, APTTUS_CONFIG2__NETPRICE__C
     , APTTUS_CONFIG2__NETUNITPRICE__C, APTTUS_CONFIG2__OPTIONCOST__C, APTTUS_CONFIG2__OPTIONID__C, APTTUS_CONFIG2__OPTIONPRICE__C
     , APTTUS_CONFIG2__ORIGINALSTARTDATE__C, APTTUS_CONFIG2__PARENTASSETID__C, APTTUS_CONFIG2__PARENTBUNDLENUMBER__C, APTTUS_CONFIG2__PRICEGROUP__C
     , APTTUS_CONFIG2__PRICEINCLUDEDINBUNDLE__C, APTTUS_CONFIG2__PRICELISTID__C, APTTUS_CONFIG2__PRICELISTITEMID__C, APTTUS_CONFIG2__PRICEMETHOD__C
     , APTTUS_CONFIG2__PRICETYPE__C, APTTUS_CONFIG2__PRICEUOM__C, APTTUS_CONFIG2__PRIMARYLINENUMBER__C, APTTUS_CONFIG2__PRODUCTID__C
     , APTTUS_CONFIG2__PRODUCTTYPE__C, APTTUS_CONFIG2__QUANTITY__C, APTTUS_CONFIG2__RENEWALFREQUENCY__C, APTTUS_CONFIG2__RENEWALTERM__C
     , APTTUS_CONFIG2__SELLINGFREQUENCY__C, APTTUS_CONFIG2__SELLINGTERM__C, APTTUS_CONFIG2__SELLINGUOM__C, APTTUS_CONFIG2__SHIPTOACCOUNTID__C
     , APTTUS_CONFIG2__STARTDATE__C, APTTUS_CONFIG2__TAXABLE__C, APTTUS_CONFIG2__TAXINCLUSIVE__C, APTTUS_CONFIG2__TERM__C, APTTUS_CONFIG2__TOTALBALANCE__C
     , APTTUS_QPCONFIG__PROPOSALID__C, APTTUS_QPCONFIG__PROPOSALLINEITEMID__C, BUNDLE_END_DATE_PAST_DUE__C, CREATEDBYID, CREATEDDATE, CURRENCYISOCODE
     , DELETE_FLAG__C, ID, ISDELETED, LASTMODIFIEDBYID, LASTMODIFIEDDATE, NAME, ORDER_FORM__C, OWNERID, PRODUCT_FAMILY__C
     , SYSTEMMODSTAMP, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, PROJECT_COLORADO_UPDATE__C, TURBO_ENGINE_CLASS__C
-- change -- remove older NULL AS from column
-- change -- add columns from the previous snap iteration as NULL AS 
     , SNAP_LOAD_AT 
FROM APTTUS_DW.SNAPSHOTS.APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1;

-- change -- check counts to insure that the recently replaced snap now has all rows
D*ROP TABLE APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1;
-- change first snap to be the recently replaced 
a*lter table APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1604728034695_1606319140742 rename to APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1;
select count(*) from APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1;

-- make changes below and then rebuild the history
CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_HISTORY  
COMMENT = 'Union ASSETLINEITEM snapshots to make complete history'
AS 
WITH the_union AS (
SELECT
	ACV__C, APTTUS_CONFIG2__ACCOUNTID__C, APTTUS_CONFIG2__ADJUSTEDPRICE__C, APTTUS_CONFIG2__ALLOWEDACTIONS__C
     , APTTUS_CONFIG2__ASSETNUMBER__C, APTTUS_CONFIG2__ASSETSTATUS__C, APTTUS_CONFIG2__ASSETTCV__C, APTTUS_CONFIG2__ATTRIBUTEVALUEID__C
     , APTTUS_CONFIG2__AUTORENEWALTYPE__C, APTTUS_CONFIG2__AUTORENEW__C, APTTUS_CONFIG2__AVAILABLEBALANCE__C, APTTUS_CONFIG2__BASECOST__C
     , APTTUS_CONFIG2__BASEEXTENDEDCOST__C, APTTUS_CONFIG2__BASEEXTENDEDPRICE__C, APTTUS_CONFIG2__BASEPRICEMETHOD__C, APTTUS_CONFIG2__BASEPRICE__C
     , APTTUS_CONFIG2__BILLINGENDDATE__C, APTTUS_CONFIG2__BILLINGFREQUENCY__C, APTTUS_CONFIG2__BILLINGPREFERENCEID__C, APTTUS_CONFIG2__BILLINGRULE__C
     , APTTUS_CONFIG2__BILLINGSTARTDATE__C, APTTUS_CONFIG2__BILLTOACCOUNTID__C, APTTUS_CONFIG2__BUNDLEASSETID__C, APTTUS_CONFIG2__BUSINESSLINEITEMID__C
     , APTTUS_CONFIG2__BUSINESSOBJECTID__C, APTTUS_CONFIG2__BUSINESSOBJECTTYPE__C, APTTUS_CONFIG2__CANCELLEDDATE__C, APTTUS_CONFIG2__CHARGETYPE__C
     , APTTUS_CONFIG2__COMMENTS__C, APTTUS_CONFIG2__CURRENTCONTRACTSTARTDATE__C, APTTUS_CONFIG2__CURRENTCONTRACTTERM__C
     , APTTUS_CONFIG2__CURRENTCONTRACTUNITPRICE__C, APTTUS_CONFIG2__CURRENTCONTRACTVALUE__C, APTTUS_CONFIG2__DELTAPRICE__C
     , APTTUS_CONFIG2__DELTAQUANTITY__C, APTTUS_CONFIG2__DESCRIPTION__C, APTTUS_CONFIG2__ENDDATE__C, APTTUS_CONFIG2__EXTENDEDCOST__C
     , APTTUS_CONFIG2__EXTENDEDPRICE__C, APTTUS_CONFIG2__FREQUENCY__C, APTTUS_CONFIG2__HASATTRIBUTES__C, APTTUS_CONFIG2__HASOPTIONS__C
     , APTTUS_CONFIG2__HIDEINVOICEDISPLAY__C, APTTUS_CONFIG2__ISINACTIVE__C, APTTUS_CONFIG2__ISOPTIONROLLUPLINE__C, APTTUS_CONFIG2__ISPRIMARYLINE__C
     , APTTUS_CONFIG2__ISPRIMARYRAMPLINE__C, APTTUS_CONFIG2__ISPRIMARYSERVICE__C, APTTUS_CONFIG2__ISREADONLY__C, APTTUS_CONFIG2__ISRENEWALPENDING__C
     , APTTUS_CONFIG2__ISRENEWED__C, APTTUS_CONFIG2__ISUSAGETIERMODIFIABLE__C, APTTUS_CONFIG2__ITEMSEQUENCE__C, APTTUS_CONFIG2__LASTRENEWENDDATE__C
     , APTTUS_CONFIG2__LINENUMBER__C, APTTUS_CONFIG2__LINETYPE__C, APTTUS_CONFIG2__LISTPRICE__C, APTTUS_CONFIG2__MUSTUPGRADE__C, APTTUS_CONFIG2__NETPRICE__C
     , APTTUS_CONFIG2__NETUNITPRICE__C, APTTUS_CONFIG2__OPTIONCOST__C, APTTUS_CONFIG2__OPTIONID__C, APTTUS_CONFIG2__OPTIONPRICE__C
     , APTTUS_CONFIG2__ORIGINALSTARTDATE__C, APTTUS_CONFIG2__PARENTASSETID__C, APTTUS_CONFIG2__PARENTBUNDLENUMBER__C, APTTUS_CONFIG2__PRICEGROUP__C
     , APTTUS_CONFIG2__PRICEINCLUDEDINBUNDLE__C, APTTUS_CONFIG2__PRICELISTID__C, APTTUS_CONFIG2__PRICELISTITEMID__C, APTTUS_CONFIG2__PRICEMETHOD__C
     , APTTUS_CONFIG2__PRICETYPE__C, APTTUS_CONFIG2__PRICEUOM__C, APTTUS_CONFIG2__PRIMARYLINENUMBER__C, APTTUS_CONFIG2__PRODUCTID__C
     , APTTUS_CONFIG2__PRODUCTTYPE__C, APTTUS_CONFIG2__QUANTITY__C, APTTUS_CONFIG2__RENEWALFREQUENCY__C, APTTUS_CONFIG2__RENEWALTERM__C
     , APTTUS_CONFIG2__SELLINGFREQUENCY__C, APTTUS_CONFIG2__SELLINGTERM__C, APTTUS_CONFIG2__SELLINGUOM__C, APTTUS_CONFIG2__SHIPTOACCOUNTID__C
     , APTTUS_CONFIG2__STARTDATE__C, APTTUS_CONFIG2__TAXABLE__C, APTTUS_CONFIG2__TAXINCLUSIVE__C, APTTUS_CONFIG2__TERM__C, APTTUS_CONFIG2__TOTALBALANCE__C
     , APTTUS_QPCONFIG__PROPOSALID__C, APTTUS_QPCONFIG__PROPOSALLINEITEMID__C, BUNDLE_END_DATE_PAST_DUE__C, CREATEDBYID, CREATEDDATE, CURRENCYISOCODE
     , DELETE_FLAG__C, ID, ISDELETED, LASTMODIFIEDBYID, LASTMODIFIEDDATE, NAME, ORDER_FORM__C, OWNERID, PRODUCT_FAMILY__C
     , SYSTEMMODSTAMP, "_SDC_BATCHED_AT", "_SDC_EXTRACTED_AT", "_SDC_RECEIVED_AT", "_SDC_SEQUENCE", "_SDC_TABLE_VERSION", PROJECT_COLORADO_UPDATE__C, TURBO_ENGINE_CLASS__C
-- change -- add latest columns  
	, SNAP_LOAD_AT
FROM
-- change -- update to most recent snap	
        APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1604728034695_1606319140742
/* add union when it arrives
UNION
SELECT
	ACV__C, APTTUS_CONFIG2__ACCOUNTID__C, APTTUS_CONFIG2__ADJUSTEDPRICE__C, APTTUS_CONFIG2__ALLOWEDACTIONS__C
     , APTTUS_CONFIG2__ASSETNUMBER__C, APTTUS_CONFIG2__ASSETSTATUS__C, APTTUS_CONFIG2__ASSETTCV__C, APTTUS_CONFIG2__ATTRIBUTEVALUEID__C
     , APTTUS_CONFIG2__AUTORENEWALTYPE__C, APTTUS_CONFIG2__AUTORENEW__C, APTTUS_CONFIG2__AVAILABLEBALANCE__C, APTTUS_CONFIG2__BASECOST__C
     , APTTUS_CONFIG2__BASEEXTENDEDCOST__C, APTTUS_CONFIG2__BASEEXTENDEDPRICE__C, APTTUS_CONFIG2__BASEPRICEMETHOD__C, APTTUS_CONFIG2__BASEPRICE__C
     , APTTUS_CONFIG2__BILLINGENDDATE__C, APTTUS_CONFIG2__BILLINGFREQUENCY__C, APTTUS_CONFIG2__BILLINGPREFERENCEID__C, APTTUS_CONFIG2__BILLINGRULE__C
     , APTTUS_CONFIG2__BILLINGSTARTDATE__C, APTTUS_CONFIG2__BILLTOACCOUNTID__C, APTTUS_CONFIG2__BUNDLEASSETID__C, APTTUS_CONFIG2__BUSINESSLINEITEMID__C
     , APTTUS_CONFIG2__BUSINESSOBJECTID__C, APTTUS_CONFIG2__BUSINESSOBJECTTYPE__C, APTTUS_CONFIG2__CANCELLEDDATE__C, APTTUS_CONFIG2__CHARGETYPE__C
     , APTTUS_CONFIG2__COMMENTS__C, APTTUS_CONFIG2__CURRENTCONTRACTSTARTDATE__C, APTTUS_CONFIG2__CURRENTCONTRACTTERM__C
     , APTTUS_CONFIG2__CURRENTCONTRACTUNITPRICE__C, APTTUS_CONFIG2__CURRENTCONTRACTVALUE__C, APTTUS_CONFIG2__DELTAPRICE__C
     , APTTUS_CONFIG2__DELTAQUANTITY__C, APTTUS_CONFIG2__DESCRIPTION__C, APTTUS_CONFIG2__ENDDATE__C, APTTUS_CONFIG2__EXTENDEDCOST__C
     , APTTUS_CONFIG2__EXTENDEDPRICE__C, APTTUS_CONFIG2__FREQUENCY__C, APTTUS_CONFIG2__HASATTRIBUTES__C, APTTUS_CONFIG2__HASOPTIONS__C
     , APTTUS_CONFIG2__HIDEINVOICEDISPLAY__C, APTTUS_CONFIG2__ISINACTIVE__C, APTTUS_CONFIG2__ISOPTIONROLLUPLINE__C, APTTUS_CONFIG2__ISPRIMARYLINE__C
     , APTTUS_CONFIG2__ISPRIMARYRAMPLINE__C, APTTUS_CONFIG2__ISPRIMARYSERVICE__C, APTTUS_CONFIG2__ISREADONLY__C, APTTUS_CONFIG2__ISRENEWALPENDING__C
     , APTTUS_CONFIG2__ISRENEWED__C, APTTUS_CONFIG2__ISUSAGETIERMODIFIABLE__C, APTTUS_CONFIG2__ITEMSEQUENCE__C, APTTUS_CONFIG2__LASTRENEWENDDATE__C
     , APTTUS_CONFIG2__LINENUMBER__C, APTTUS_CONFIG2__LINETYPE__C, APTTUS_CONFIG2__LISTPRICE__C, APTTUS_CONFIG2__MUSTUPGRADE__C, APTTUS_CONFIG2__NETPRICE__C
     , APTTUS_CONFIG2__NETUNITPRICE__C, APTTUS_CONFIG2__OPTIONCOST__C, APTTUS_CONFIG2__OPTIONID__C, APTTUS_CONFIG2__OPTIONPRICE__C
     , APTTUS_CONFIG2__ORIGINALSTARTDATE__C, APTTUS_CONFIG2__PARENTASSETID__C, APTTUS_CONFIG2__PARENTBUNDLENUMBER__C, APTTUS_CONFIG2__PRICEGROUP__C
     , APTTUS_CONFIG2__PRICEINCLUDEDINBUNDLE__C, APTTUS_CONFIG2__PRICELISTID__C, APTTUS_CONFIG2__PRICELISTITEMID__C, APTTUS_CONFIG2__PRICEMETHOD__C
     , APTTUS_CONFIG2__PRICETYPE__C, APTTUS_CONFIG2__PRICEUOM__C, APTTUS_CONFIG2__PRIMARYLINENUMBER__C, APTTUS_CONFIG2__PRODUCTID__C
     , APTTUS_CONFIG2__PRODUCTTYPE__C, APTTUS_CONFIG2__QUANTITY__C, APTTUS_CONFIG2__RENEWALFREQUENCY__C, APTTUS_CONFIG2__RENEWALTERM__C
     , APTTUS_CONFIG2__SELLINGFREQUENCY__C, APTTUS_CONFIG2__SELLINGTERM__C, APTTUS_CONFIG2__SELLINGUOM__C, APTTUS_CONFIG2__SHIPTOACCOUNTID__C
     , APTTUS_CONFIG2__STARTDATE__C, APTTUS_CONFIG2__TAXABLE__C, APTTUS_CONFIG2__TAXINCLUSIVE__C, APTTUS_CONFIG2__TERM__C, APTTUS_CONFIG2__TOTALBALANCE__C
     , APTTUS_QPCONFIG__PROPOSALID__C, APTTUS_QPCONFIG__PROPOSALLINEITEMID__C, BUNDLE_END_DATE_PAST_DUE__C, CREATEDBYID, CREATEDDATE, CURRENCYISOCODE
     , DELETE_FLAG__C, ID, ISDELETED, LASTMODIFIEDBYID, LASTMODIFIEDDATE, NAME, ORDER_FORM__C, OWNERID, PRODUCT_FAMILY__C
     , SYSTEMMODSTAMP, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, PROJECT_COLORADO_UPDATE__C, TURBO_ENGINE_CLASS__C
-- change -- remove NULL AS from previous round
-- change -- ADD newest Columns as NULL AS  
	, SNAP_LOAD_AT
FROM
	APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_SNAP_1
*/	
)	
, the_unique AS (
	SELECT ID
         , _SDC_EXTRACTED_AT 
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY ID
         , _SDC_EXTRACTED_AT 
)
	SELECT A.*
	     , to_date(SYSTEMMODSTAMP) AS ACTIVITY_DATE
	     , dateadd(day, -1, to_date(A."_SDC_EXTRACTED_AT")) AS EXTRACT_DATE
	     , dateadd(day, -1, to_date(A."SNAP_LOAD_AT")) AS REPORTING_DATE	     
	FROM                 the_union A
	INNER JOIN           the_unique B
	             ON  A.ID = B.ID
	             AND A._SDC_EXTRACTED_AT = B._SDC_EXTRACTED_AT
	             AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;

-- RUN duplicate detector to be sure you haven't created duplicates in History View
SELECT count(*)
     , ID
     , _SDC_EXTRACTED_AT 
FROM APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_HISTORY
group by ID
       , _SDC_EXTRACTED_AT 
having count(*) > 1
 -- 0
;
select count(distinct ID)
FROM APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_HISTORY
 -- 10153 
;
select count(distinct ID, _SDC_EXTRACTED_AT)
FROM APTTUS_DW.SNAPSHOTS.ASSETLINEITEM_HISTORY
 -- 10153 
;

