--DROP VIEW APTTUS_DW.SNAPSHOTS.FMA_VALUES_HISTORY ;

CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.FMA_VALUES_HISTORY  
COMMENT = 'Union FMA_VALUE snapshots to make complete history'
AS 
WITH the_union AS (
	SELECT
		CREATEDBYID
		, CREATEDDATE
		, ID
		, ISDELETED
		, LASTMODIFIEDBYID
		, LASTMODIFIEDDATE
		, "NAME"
		, SFFMA__FEATUREPARAMETER__C
		, SFFMA__LICENSE__C
		, SFFMA__VALUE__C
		, SYSTEMMODSTAMP
		, "_SDC_BATCHED_AT"
		, "_SDC_EXTRACTED_AT"
		, "_SDC_RECEIVED_AT"
		, "_SDC_SEQUENCE"
		, "_SDC_TABLE_VERSION"
		, SNAP_LOAD_AT
	        , to_date(SYSTEMMODSTAMP) AS ACTIVITY_DATE		
	FROM
		APTTUS_DW.SNAPSHOTS.FMA_VALUES_SNAP_1595012858504_1600187503192
UNION
    SELECT
		CREATEDBYID
		, CREATEDDATE
		, ID
		, ISDELETED
		, LASTMODIFIEDBYID
		, LASTMODIFIEDDATE
		, "NAME"
		, SFFMA__FEATUREPARAMETER__C
		, SFFMA__LICENSE__C
		, SFFMA__VALUE__C
		, SYSTEMMODSTAMP
		, "_SDC_BATCHED_AT"
		, "_SDC_EXTRACTED_AT"
		, "_SDC_RECEIVED_AT"
		, "_SDC_SEQUENCE"
		, "_SDC_TABLE_VERSION"
		, SNAP_LOAD_AT
		, to_date(SYSTEMMODSTAMP) AS ACTIVITY_DATE
	FROM
		APTTUS_DW.SNAPSHOTS.FMA_VALUES_SNAP_1
)
, the_unique AS (
	SELECT SFFMA__LICENSE__C
         , SFFMA__FEATUREPARAMETER__C
         , ACTIVITY_DATE
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY SFFMA__LICENSE__C
         , SFFMA__FEATUREPARAMETER__C
         , ACTIVITY_DATE
)
	SELECT A.*
	     , to_date(A."_SDC_EXTRACTED_AT") AS EXTRACT_DATE
	     , to_date(A."SNAP_LOAD_AT") AS REPORTING_DATE
	FROM                 the_union A
	INNER JOIN           the_unique B
	             ON  A.SFFMA__LICENSE__C = B.SFFMA__LICENSE__C
	             AND A.SFFMA__FEATUREPARAMETER__C = B.SFFMA__FEATUREPARAMETER__C
	             AND A.ACTIVITY_DATE = B.ACTIVITY_DATE
	             AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;


