--DROP VIEW APTTUS_DW.SNAPSHOTS.FMA_VALUES_HISTORY ;

CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.FMA_VALUES_HISTORY  
COMMENT = 'Union FMA_VALUE snapshots to make complete history'
AS 
WITH the_union AS (
    SELECT
		CREATEDBYID
		, CREATEDDATE
		, ID
		, ISDELETED
		, LASTMODIFIEDBYID
		, LASTMODIFIEDDATE
		, "NAME"
		, SFFMA__FEATUREPARAMETER__C
		, SFFMA__LICENSE__C
		, SFFMA__VALUE__C
		, SYSTEMMODSTAMP
		, "_SDC_BATCHED_AT"
		, "_SDC_EXTRACTED_AT"
		, "_SDC_RECEIVED_AT"
		, "_SDC_SEQUENCE"
		, "_SDC_TABLE_VERSION"
		, SNAP_LOAD_AT
	FROM
		APTTUS_DW.SNAPSHOTS.FMA_VALUES_SNAP_1595012858504
union	
	SELECT
		CREATEDBYID
		, CREATEDDATE
		, ID
		, ISDELETED
		, LASTMODIFIEDBYID
		, LASTMODIFIEDDATE
		, "NAME"
		, SFFMA__FEATUREPARAMETER__C
		, SFFMA__LICENSE__C
		, SFFMA__VALUE__C
		, SYSTEMMODSTAMP
		, "_SDC_BATCHED_AT"
		, "_SDC_EXTRACTED_AT"
		, "_SDC_RECEIVED_AT"
		, "_SDC_SEQUENCE"
		, "_SDC_TABLE_VERSION"
		, SNAP_LOAD_AT
	FROM
		APTTUS_DW.SNAPSHOTS.FMA_VALUES_SNAP_1
)
, the_unique AS (
	SELECT SFFMA__LICENSE__C
         , SFFMA__FEATUREPARAMETER__C
         , _SDC_EXTRACTED_AT
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY SFFMA__LICENSE__C
         , SFFMA__FEATUREPARAMETER__C
         , _SDC_EXTRACTED_AT
)
	SELECT A.*, dateadd(day, -1, to_date(A."_SDC_EXTRACTED_AT")) AS ACTIVITY_DATE
	FROM                 the_union A
	INNER JOIN           the_unique B
	             ON  A.SFFMA__LICENSE__C = B.SFFMA__LICENSE__C
	             AND A.SFFMA__FEATUREPARAMETER__C = B.SFFMA__FEATUREPARAMETER__C
	             AND A._SDC_EXTRACTED_AT = B._SDC_EXTRACTED_AT
	             AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;
