--DROP VIEW APTTUS_DW.SNAPSHOTS.LMA_LICENSE_CLMCPQ_HISTORY ;

CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.LMA_LICENSE_CLMCPQ_HISTORY  
COMMENT = 'Union LMA_LICENSE_CLNCPQ snapshots to make complete history'
AS 
WITH the_union AS (
SELECT
	ACCOUNTID__C
	, ACCOUNT_NAME__C
	, ADMIN_USERS__C
	, AUTHOR_USERS__C
	, AUTO_RENEW__C
	, COMPLY_USERS__C
	, CREATEDBYID
	, CREATEDDATE
	, CURRENCYISOCODE
	, CUSTOM_LAST_MODIFIED_DATE__C
	, ID
	, ISDELETED
	, IS_APTTUS_CUSTOMER__C
	, LASTMODIFIEDBYID
	, LASTMODIFIEDDATE
	, LASTREFERENCEDDATE
	, LASTVIEWEDDATE
	, NAME
	, OEM__C
	, OTHER_USERS_DESCRIPTION__C
	, OTHER_USERS__C
	, OWNERID
	, RECORDTYPEID
	, RELEASE_NAME__C
	, RENEWAL_PROVISIONS__C
	, SFLMA__ACCOUNT__C
	, SFLMA__CONTACT__C
	, SFLMA__EXPIRATION_DATE__C
	, SFLMA__EXPIRATION__C
	, SFLMA__HELP__C
	, SFLMA__INSTALL_DATE__C
	, SFLMA__IS_SANDBOX__C
	, SFLMA__LEAD__C
	, SFLMA__LICENSED_SEATS__C
	, SFLMA__LICENSE_STATUS__C
	, SFLMA__LICENSE_TYPE__C
	, SFLMA__ORG_INSTANCE__C
	, SFLMA__ORG_STATUS_FORMULA__C
	, SFLMA__ORG_STATUS__C
	, SFLMA__ORG_TRIAL_EXPIRATION__C
	, SFLMA__ORG_TYPE__C
	, SFLMA__PACKAGE_LICENSE_ID__C
	, SFLMA__PACKAGE_VERSION__C
	, SFLMA__PROXY_USER__C
	, SFLMA__SEATS__C
	, SFLMA__STATUS__C
	, SFLMA__SUBSCRIBER_ORG_ID__C
	, SFLMA__SUBSCRIBER_ORG_IS_SANDBOX__C
	, SFLMA__TRIAL_EXPIRATION_DATE__C
	, SFLMA__USED_LICENSES__C
	, SYSTEMMODSTAMP
	, TDO_NAME__C
	, TOTAL_USERS_ROLLUP__C
	, WIZARD_USERS__C
	, _SDC_BATCHED_AT
	, _SDC_EXTRACTED_AT
	, _SDC_RECEIVED_AT
	, _SDC_SEQUENCE
	, _SDC_TABLE_VERSION
	, LASTACTIVITYDATE
	, ACCOUNT_NAME_TEXT__C
	, STATUS_DATE__C
	, ACCOUNT_ID__C
	, SFLMA__PACKAGE__C
	, SFLMA__ORG_EDITION__C
	, PACKAGE_NAME__C
	, PACKAGE_VERSION_NAME__C
	, X18_DIGIT_ACCOUNT_ID__C
	, X18_DIGIT_NEW_SFDC_ID__C
	, SFDC_OEM_EMBEDDED_SEATS__C
	, SNAP_LOAD_AT
FROM
	LMA_LICENSE_CLMCPQ_SNAP_1600188187559_1601667030465
/* No union yet
UNION
SELECT
	ACCOUNTID__C
	, ACCOUNT_NAME__C
	, ADMIN_USERS__C
	, AUTHOR_USERS__C
	, AUTO_RENEW__C
	, COMPLY_USERS__C
	, CREATEDBYID
	, CREATEDDATE
	, CURRENCYISOCODE
	, CUSTOM_LAST_MODIFIED_DATE__C
	, ID
	, ISDELETED
	, IS_APTTUS_CUSTOMER__C
	, LASTMODIFIEDBYID
	, LASTMODIFIEDDATE
	, LASTREFERENCEDDATE
	, LASTVIEWEDDATE
	, NAME
	, OEM__C
	, OTHER_USERS_DESCRIPTION__C
	, OTHER_USERS__C
	, OWNERID
	, RECORDTYPEID
	, RELEASE_NAME__C
	, RENEWAL_PROVISIONS__C
	, SFLMA__ACCOUNT__C
	, SFLMA__CONTACT__C
	, SFLMA__EXPIRATION_DATE__C
	, SFLMA__EXPIRATION__C
	, SFLMA__HELP__C
	, SFLMA__INSTALL_DATE__C
	, SFLMA__IS_SANDBOX__C
	, SFLMA__LEAD__C
	, SFLMA__LICENSED_SEATS__C
	, SFLMA__LICENSE_STATUS__C
	, SFLMA__LICENSE_TYPE__C
	, SFLMA__ORG_INSTANCE__C
	, SFLMA__ORG_STATUS_FORMULA__C
	, SFLMA__ORG_STATUS__C
	, SFLMA__ORG_TRIAL_EXPIRATION__C
	, SFLMA__ORG_TYPE__C
	, SFLMA__PACKAGE_LICENSE_ID__C
	, SFLMA__PACKAGE_VERSION__C
	, SFLMA__PROXY_USER__C
	, SFLMA__SEATS__C
	, SFLMA__STATUS__C
	, SFLMA__SUBSCRIBER_ORG_ID__C
	, SFLMA__SUBSCRIBER_ORG_IS_SANDBOX__C
	, SFLMA__TRIAL_EXPIRATION_DATE__C
	, SFLMA__USED_LICENSES__C
	, SYSTEMMODSTAMP
	, TDO_NAME__C
	, TOTAL_USERS_ROLLUP__C
	, WIZARD_USERS__C
	, _SDC_BATCHED_AT
	, _SDC_EXTRACTED_AT
	, _SDC_RECEIVED_AT
	, _SDC_SEQUENCE
	, _SDC_TABLE_VERSION
	, LASTACTIVITYDATE
	, ACCOUNT_NAME_TEXT__C
	, STATUS_DATE__C
	, ACCOUNT_ID__C
	, SFLMA__PACKAGE__C
	, SFLMA__ORG_EDITION__C
	, PACKAGE_NAME__C
	, PACKAGE_VERSION_NAME__C
	, X18_DIGIT_ACCOUNT_ID__C
	, X18_DIGIT_NEW_SFDC_ID__C
	, SFDC_OEM_EMBEDDED_SEATS__C
	, SNAP_LOAD_AT
FROM
	LMA_LICENSE_CLMCPQ_SNAP_1
*/
)
, the_unique AS (
	SELECT ID
         , _SDC_EXTRACTED_AT 
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY ID
         , _SDC_EXTRACTED_AT 
)
	SELECT A.*
	     , to_date(SYSTEMMODSTAMP) AS ACTIVITY_DATE
	     , dateadd(day, -1, to_date(A."_SDC_EXTRACTED_AT")) AS EXTRACT_DATE
	     , dateadd(day, -1, to_date(A."SNAP_LOAD_AT")) AS REPORTING_DATE	
	FROM                 the_union A
	INNER JOIN           the_unique B
	             ON  A.ID = B.ID
	             AND A._SDC_EXTRACTED_AT = B._SDC_EXTRACTED_AT
	             AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;


