--DROP VIEW APTTUS_DW.SNAPSHOTS.FMA_VALUES_HISTORY ;

CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_HISTORY  
COMMENT = 'Union LMA_LICENSE_C1 snapshots to make complete history'
AS 
WITH the_union AS (
SELECT
	ACCOUNT_SUSPENDED__C
	, BA_EMAIL__C
	, BA__C
	, COMPANY_FROM_LEAD__C
	, CONGA_EDITION__C
	, CREATEDBYID
	, CREATEDDATE
	, CUSTOMER_ORG_ID__C
	, EXPIRATION_DATE__C
	, ID
	, INSTALL_DATE_CHECK__C
	, ISDELETED
	, LASTMODIFIEDBYID
	, LASTMODIFIEDDATE
	, LEAD_COMPANY__C
	, LEAD_EMAIL__C
	, LICENSE_CHECK__C
	, "NAME"
	, OWNERID
	, PACKAGE_NAMEFX__C
	, PRODUCTION__C
	, QUIK_CUSTOMER_ID__C
	, RECORDTYPEID
	, RECORD_URL__C
	, SALESFORCE_ORGID__C
	, SFLMA__ACCOUNT__C
	, SFLMA__CONTACT__C
	, SFLMA__EXPIRATION_DATE__C
	, SFLMA__EXPIRATION__C
	, SFLMA__HELP__C
	, SFLMA__INSTALL_DATE__C
	, SFLMA__INSTANCE__C
	, SFLMA__IS_SANDBOX__C
	, SFLMA__LAST_MODIFIED__C
	, SFLMA__LEAD__C
	, SFLMA__LICENSED_SEATS__C
	, SFLMA__LICENSE_STATUS__C
	, SFLMA__LICENSE_TYPE__C
	, SFLMA__ORG_EDITION__C
	, SFLMA__ORG_INSTANCE__C
	, SFLMA__ORG_STATUS_FORMULA__C
	, SFLMA__ORG_STATUS__C
	, SFLMA__ORG_TRIAL_EXPIRATION__C
	, SFLMA__ORG_TYPE__C
	, SFLMA__PACKAGE_LICENSE_ID__C
	, SFLMA__PACKAGE_VERSION_NUMBER__C
	, SFLMA__PACKAGE_VERSION__C
	, SFLMA__PACKAGE__C
	, SFLMA__PROXY_USER__C
	, SFLMA__SEATS__C
	, SFLMA__STATUS__C
	, SFLMA__SUBSCRIBER_ORG_ID__C
	, SFLMA__SUBSCRIBER_ORG_IS_SANDBOX__C
	, SFLMA__TRIAL_EXPIRATION_DATE__C
	, SFLMA__USED_LICENSES__C
	, SFLMA__VERSION_NUMBER__C
	, SUSPEND_ACCOUNT__C
	, SYSTEMMODSTAMP
	, UNINSTALL_DATE__C
	, "_SDC_BATCHED_AT"
	, "_SDC_EXTRACTED_AT"
	, "_SDC_RECEIVED_AT"
	, "_SDC_SEQUENCE"
	, "_SDC_TABLE_VERSION"
	, SNAP_LOAD_AT
FROM
	APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_SNAP_1595011981947_1600187624271
UNION
	SELECT
		ACCOUNT_SUSPENDED__C
		, BA_EMAIL__C
		, BA__C
		, COMPANY_FROM_LEAD__C
		, CONGA_EDITION__C
		, CREATEDBYID
		, CREATEDDATE
		, CUSTOMER_ORG_ID__C
		, EXPIRATION_DATE__C
		, ID
		, INSTALL_DATE_CHECK__C
		, ISDELETED
		, LASTMODIFIEDBYID
		, LASTMODIFIEDDATE
		, LEAD_COMPANY__C
		, LEAD_EMAIL__C
		, LICENSE_CHECK__C
		, "NAME"
		, OWNERID
		, PACKAGE_NAMEFX__C
		, PRODUCTION__C
		, QUIK_CUSTOMER_ID__C
		, RECORDTYPEID
		, RECORD_URL__C
		, SALESFORCE_ORGID__C
		, SFLMA__ACCOUNT__C
		, SFLMA__CONTACT__C
		, SFLMA__EXPIRATION_DATE__C
		, SFLMA__EXPIRATION__C
		, SFLMA__HELP__C
		, SFLMA__INSTALL_DATE__C
		, SFLMA__INSTANCE__C
		, SFLMA__IS_SANDBOX__C
		, SFLMA__LAST_MODIFIED__C
		, SFLMA__LEAD__C
		, SFLMA__LICENSED_SEATS__C
		, SFLMA__LICENSE_STATUS__C
		, SFLMA__LICENSE_TYPE__C
		, SFLMA__ORG_EDITION__C
		, SFLMA__ORG_INSTANCE__C
		, SFLMA__ORG_STATUS_FORMULA__C
		, SFLMA__ORG_STATUS__C
		, SFLMA__ORG_TRIAL_EXPIRATION__C
		, SFLMA__ORG_TYPE__C
		, SFLMA__PACKAGE_LICENSE_ID__C
		, SFLMA__PACKAGE_VERSION_NUMBER__C
		, SFLMA__PACKAGE_VERSION__C
		, SFLMA__PACKAGE__C
		, SFLMA__PROXY_USER__C
		, SFLMA__SEATS__C
		, SFLMA__STATUS__C
		, SFLMA__SUBSCRIBER_ORG_ID__C
		, SFLMA__SUBSCRIBER_ORG_IS_SANDBOX__C
		, SFLMA__TRIAL_EXPIRATION_DATE__C
		, SFLMA__USED_LICENSES__C
		, SFLMA__VERSION_NUMBER__C
		, SUSPEND_ACCOUNT__C
		, SYSTEMMODSTAMP
		, UNINSTALL_DATE__C
		, "_SDC_BATCHED_AT"
		, "_SDC_EXTRACTED_AT"
		, "_SDC_RECEIVED_AT"
		, "_SDC_SEQUENCE"
		, "_SDC_TABLE_VERSION"
		, SNAP_LOAD_AT
	FROM
		APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_SNAP_1
UNION
	SELECT
		ACCOUNT_SUSPENDED__C
		, BA_EMAIL__C
		, BA__C
		, COMPANY_FROM_LEAD__C
		, CONGA_EDITION__C
		, CREATEDBYID
		, CREATEDDATE
		, CUSTOMER_ORG_ID__C
		, EXPIRATION_DATE__C
		, ID
		, INSTALL_DATE_CHECK__C
		, ISDELETED
		, LASTMODIFIEDBYID
		, LASTMODIFIEDDATE
		, LEAD_COMPANY__C
		, LEAD_EMAIL__C
		, LICENSE_CHECK__C
		, "NAME"
		, OWNERID
		, PACKAGE_NAMEFX__C
		, PRODUCTION__C
		, QUIK_CUSTOMER_ID__C
		, RECORDTYPEID
		, RECORD_URL__C
		, SALESFORCE_ORGID__C
		, SFLMA__ACCOUNT__C
		, SFLMA__CONTACT__C
		, SFLMA__EXPIRATION_DATE__C
		, SFLMA__EXPIRATION__C
		, SFLMA__HELP__C
		, SFLMA__INSTALL_DATE__C
		, SFLMA__INSTANCE__C
		, SFLMA__IS_SANDBOX__C
		, SFLMA__LAST_MODIFIED__C
		, SFLMA__LEAD__C
		, SFLMA__LICENSED_SEATS__C
		, SFLMA__LICENSE_STATUS__C
		, SFLMA__LICENSE_TYPE__C
		, SFLMA__ORG_EDITION__C
		, SFLMA__ORG_INSTANCE__C
		, SFLMA__ORG_STATUS_FORMULA__C
		, SFLMA__ORG_STATUS__C
		, SFLMA__ORG_TRIAL_EXPIRATION__C
		, SFLMA__ORG_TYPE__C
		, SFLMA__PACKAGE_LICENSE_ID__C
		, SFLMA__PACKAGE_VERSION_NUMBER__C
		, SFLMA__PACKAGE_VERSION__C
		, SFLMA__PACKAGE__C
		, SFLMA__PROXY_USER__C
		, SFLMA__SEATS__C
		, SFLMA__STATUS__C
		, SFLMA__SUBSCRIBER_ORG_ID__C
		, SFLMA__SUBSCRIBER_ORG_IS_SANDBOX__C
		, SFLMA__TRIAL_EXPIRATION_DATE__C
		, SFLMA__USED_LICENSES__C
		, SFLMA__VERSION_NUMBER__C
		, SUSPEND_ACCOUNT__C
		, SYSTEMMODSTAMP
		, UNINSTALL_DATE__C
		, "_SDC_BATCHED_AT"
		, "_SDC_EXTRACTED_AT"
		, "_SDC_RECEIVED_AT"
		, "_SDC_SEQUENCE"
		, "_SDC_TABLE_VERSION"
		, SNAP_LOAD_AT
	FROM	APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_FROMREDSHIFT	
)
, the_unique AS (
	SELECT ID
         , _SDC_EXTRACTED_AT 
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY ID
         , _SDC_EXTRACTED_AT 
)
	SELECT A.*
	     , to_date(SYSTEMMODSTAMP) AS ACTIVITY_DATE
	     , dateadd(day, -1, to_date(A."_SDC_EXTRACTED_AT")) AS EXTRACT_DATE
	     , dateadd(day, -1, to_date(A."SNAP_LOAD_AT")) AS REPORTING_DATE	
	FROM                 the_union A
	INNER JOIN           the_unique B
	             ON  A.ID = B.ID
	             AND A._SDC_EXTRACTED_AT = B._SDC_EXTRACTED_AT
	             AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;


