SELECT CURRENT_ROLE();

Select TABLE_CATALOG||'.'||TABLE_SCHEMA||'.'||TABLE_NAME, MAX(ORDINAL_POSITION)
 FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME LIKE 'PRODUCT2_C1_SNAP%'
 GROUP by TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME
 order by 1
; 

with get_last as(
        Select MAX(ORDINAL_POSITION) as LAST_COL
         FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_NAME = 'PRODUCT2_C1_SNAP_1'
)
Select TABLE_CATALOG||'.'||TABLE_SCHEMA||'.'||TABLE_NAME, ORDINAL_POSITION, COLUMN_NAME
 FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME LIKE 'PRODUCT2_C1_SNAP%'
   AND ORDINAL_POSITION > ((SELECT LAST_COL from get_last)-1)
   AND COLUMN_NAME <> 'SNAP_LOAD_AT'
ORDER BY 1, 2   
; 

Select TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION
FROM APTTUS_DW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE 'PRODUCT2_C1_SNAP%'
ORDER BY ORDINAL_POSITION, TABLE_NAME 
;

select count(*) from APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1;
select count(*) from APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1604740678944_1609927454497;
select count(*) from APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1604740678944_1610013853179;

-- CHANGE -- uncommend insert and update table name to previous snap
-- CHANGE -- manage columns near bottom
INSERT INTO APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1604740678944_1609927454497 
      (AVA_SFCORE__TAX_CODE__C, CANUSEREVENUESCHEDULE, CATALOG_GROUP__C, CC_REPORTS__C, CC_UNIT_PRICE__C, CREATEDBYID, CREATEDDATE, CRMC_ORG_PRODUCT_ID__C, DESCRIPTION, ENTITY__C, EXCLUDE_FROM_MRR__C, FAMILY, FY16_REVENUE_TYPE__C, HOURLY_RATE__C, HOURS__C, IA_CRM__BILLING_METHOD__C, IA_CRM__BILLING_TEMPLATE__C, IA_CRM__COST_METHOD__C, IA_CRM__DESCRIPTION_ON_SALES_TRANSACTIONS__C, IA_CRM__FLAT_FIXED_AMOUNT_FREQUENCY__C, IA_CRM__INTACCT_ENTITY_ID__C, IA_CRM__INTACCT_ENTITY__C, IA_CRM__INTACCT_SYNC_ERRORS__C, IA_CRM__INTACCT_SYNC_STATUS_IMAGE__C, IA_CRM__INTACCT_SYNC_STATUS__C, IA_CRM__ITEM_TYPE__C, IA_CRM__MRR__C, IA_CRM__SFDC_PRODUCT_ID__C, IA_CRM__STANDARD_COST__C, IA_CRM__SYNCED_WITH_INTACCT_DATE__C, IA_CRM__SYNC_WITH_INTACCT__C, IA_CRM__TAXABLE__C, IA_CRM__UNIT_OF_MEASURE__C, ID, ISACTIVE, ISDELETED, IS_PACK__C, LASTMODIFIEDBYID, LASTMODIFIEDDATE, LICENSE_TYPE__C, LINE_EDITOR_DESCRIPTION__C, LOB__C, NAME, PRODUCTCODE, PRODUCT_LINE__C, REMOVE_MONTHLY_CPQ_SCREEN__C, REQUIRES_SERVICES__C, SANDBOX_SYNC_EXTERNAL_ID__C, SERVICE_EVENT_MRR__C
      , SYSTEMMODSTAMP, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, LASTREFERENCEDDATE, LASTVIEWEDDATE
      -- 2021/01/05
      , SBQQ__EXCLUDEFROMOPPORTUNITY__C, SBQQ__PRICINGMETHODEDITABLE__C, SBQQ__DEFAULTPRICINGTABLE__C, SBQQ__HIDDEN__C, SBQQ__RECONFIGURATIONDISABLED__C
        , SBQQ__ENABLELARGECONFIGURATION__C, SBQQ__PRICINGMETHOD__C, SBQQ__OPTIONAL__C, SBQQ__NEWQUOTEGROUP__C, SBQQ__BLOCKPRICINGFIELD__C
        , SBQQ__SUBSCRIPTIONTYPE__C, SBQQ__EXCLUDEFROMMAINTENANCE__C, SBQQ__QUANTITYEDITABLE__C, SBQQ__TAXCODE__C, SBQQ__HASCONFIGURATIONATTRIBUTES__C
        , SBQQ__INCLUDEINMAINTENANCE__C, SBQQ__EXTERNALLYCONFIGURABLE__C, SBQQ__ASSETAMENDMENTBEHAVIOR__C, SBQQ__HIDEPRICEINSEARCHRESULTS__C
        , SBQQ__TAXABLE__C, SBQQ__SUBSCRIPTIONBASE__C, SBQQ__ASSETCONVERSION__C, SBQQ__DESCRIPTIONLOCKED__C, SBQQ__PRICEEDITABLE__C
        , SBQQ__DEFAULTQUANTITY__C, SBQQ__OPTIONSELECTIONMETHOD__C, SBQQ__NONPARTNERDISCOUNTABLE__C, SBQQ__SUBSCRIPTIONPRICING__C
        , SBQQ__SUBSCRIPTIONPERCENT__C, SBQQ__CUSTOMCONFIGURATIONREQUIRED__C, SBQQ__COSTEDITABLE__C, SBQQ__ALLOCATEPOTONORDERS__C
        , SBQQ__COMPONENT__C, SBQQ__NONDISCOUNTABLE__C
-- 2021/01/07
--, SBQQ__SUBSCRIPTIONTERM__C, SBQQ__SORTORDER__C
-- add new columns as they appear
      , SNAP_LOAD_AT)
SELECT AVA_SFCORE__TAX_CODE__C, CANUSEREVENUESCHEDULE, CATALOG_GROUP__C, CC_REPORTS__C, CC_UNIT_PRICE__C, CREATEDBYID, CREATEDDATE, CRMC_ORG_PRODUCT_ID__C, DESCRIPTION, ENTITY__C, EXCLUDE_FROM_MRR__C, FAMILY, FY16_REVENUE_TYPE__C, HOURLY_RATE__C, HOURS__C, IA_CRM__BILLING_METHOD__C, IA_CRM__BILLING_TEMPLATE__C, IA_CRM__COST_METHOD__C, IA_CRM__DESCRIPTION_ON_SALES_TRANSACTIONS__C, IA_CRM__FLAT_FIXED_AMOUNT_FREQUENCY__C, IA_CRM__INTACCT_ENTITY_ID__C, IA_CRM__INTACCT_ENTITY__C, IA_CRM__INTACCT_SYNC_ERRORS__C, IA_CRM__INTACCT_SYNC_STATUS_IMAGE__C, IA_CRM__INTACCT_SYNC_STATUS__C, IA_CRM__ITEM_TYPE__C, IA_CRM__MRR__C, IA_CRM__SFDC_PRODUCT_ID__C, IA_CRM__STANDARD_COST__C, IA_CRM__SYNCED_WITH_INTACCT_DATE__C, IA_CRM__SYNC_WITH_INTACCT__C, IA_CRM__TAXABLE__C, IA_CRM__UNIT_OF_MEASURE__C, ID, ISACTIVE, ISDELETED, IS_PACK__C, LASTMODIFIEDBYID, LASTMODIFIEDDATE, LICENSE_TYPE__C, LINE_EDITOR_DESCRIPTION__C, LOB__C, NAME, PRODUCTCODE, PRODUCT_LINE__C, REMOVE_MONTHLY_CPQ_SCREEN__C, REQUIRES_SERVICES__C, SANDBOX_SYNC_EXTERNAL_ID__C, SERVICE_EVENT_MRR__C
     , SYSTEMMODSTAMP, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, LASTREFERENCEDDATE, LASTVIEWEDDATE
      -- 2021/01/05
      , NULL AS SBQQ__EXCLUDEFROMOPPORTUNITY__C, NULL AS SBQQ__PRICINGMETHODEDITABLE__C, NULL AS SBQQ__DEFAULTPRICINGTABLE__C, NULL AS SBQQ__HIDDEN__C
      , NULL AS SBQQ__RECONFIGURATIONDISABLED__C
      , NULL AS SBQQ__ENABLELARGECONFIGURATION__C, NULL AS SBQQ__PRICINGMETHOD__C, NULL AS SBQQ__OPTIONAL__C, NULL AS SBQQ__NEWQUOTEGROUP__C
      , NULL AS SBQQ__BLOCKPRICINGFIELD__C
      , NULL AS SBQQ__SUBSCRIPTIONTYPE__C, NULL AS SBQQ__EXCLUDEFROMMAINTENANCE__C, NULL AS SBQQ__QUANTITYEDITABLE__C
      , NULL AS SBQQ__TAXCODE__C, NULL AS SBQQ__HASCONFIGURATIONATTRIBUTES__C
      , NULL AS SBQQ__INCLUDEINMAINTENANCE__C, NULL AS SBQQ__EXTERNALLYCONFIGURABLE__C, NULL AS SBQQ__ASSETAMENDMENTBEHAVIOR__C
      , NULL AS SBQQ__HIDEPRICEINSEARCHRESULTS__C
      , NULL AS SBQQ__TAXABLE__C, NULL AS SBQQ__SUBSCRIPTIONBASE__C, NULL AS SBQQ__ASSETCONVERSION__C, NULL AS SBQQ__DESCRIPTIONLOCKED__C
      , NULL AS SBQQ__PRICEEDITABLE__C
      , NULL AS SBQQ__DEFAULTQUANTITY__C, NULL AS SBQQ__OPTIONSELECTIONMETHOD__C, NULL AS SBQQ__NONPARTNERDISCOUNTABLE__C
      , NULL AS SBQQ__SUBSCRIPTIONPRICING__C
      , NULL AS SBQQ__SUBSCRIPTIONPERCENT__C, NULL AS SBQQ__CUSTOMCONFIGURATIONREQUIRED__C, NULL AS SBQQ__COSTEDITABLE__C
      , NULL AS SBQQ__ALLOCATEPOTONORDERS__C
      , NULL AS SBQQ__COMPONENT__C, NULL AS SBQQ__NONDISCOUNTABLE__C
-- change -- remove older NULL AS from column
-- change -- add columns from the previous snap iteration as NULL AS 
     , SNAP_LOAD_AT 
FROM APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1;

-- change -- check counts to insure that the recently replaced snap now has all rows
DROP TABLE APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_PRIOR;
alter table APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1 rename to PRODUCT2_C1_SNAP_PRIOR;
-- change first snap to be the recently replaced 
alter table APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1604740678944_1609927454497 rename to PRODUCT2_C1_SNAP_1;
select count(*) from APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1;

--please don't -- DROP VIEW APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_HISTORY ;
-- make changes below and then rebuild the history
CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_HISTORY 
COMMENT = 'Union PRODUCT2_C1 snapshots to make complete history' 
AS
WITH the_union AS (
SELECT
	AVA_SFCORE__TAX_CODE__C, CANUSEREVENUESCHEDULE, CATALOG_GROUP__C, CC_REPORTS__C, CC_UNIT_PRICE__C, CREATEDBYID, CREATEDDATE, CRMC_ORG_PRODUCT_ID__C, DESCRIPTION, ENTITY__C, EXCLUDE_FROM_MRR__C, FAMILY, FY16_REVENUE_TYPE__C, HOURLY_RATE__C, HOURS__C, IA_CRM__BILLING_METHOD__C, IA_CRM__BILLING_TEMPLATE__C, IA_CRM__COST_METHOD__C, IA_CRM__DESCRIPTION_ON_SALES_TRANSACTIONS__C, IA_CRM__FLAT_FIXED_AMOUNT_FREQUENCY__C, IA_CRM__INTACCT_ENTITY_ID__C, IA_CRM__INTACCT_ENTITY__C, IA_CRM__INTACCT_SYNC_ERRORS__C, IA_CRM__INTACCT_SYNC_STATUS_IMAGE__C, IA_CRM__INTACCT_SYNC_STATUS__C, IA_CRM__ITEM_TYPE__C, IA_CRM__MRR__C, IA_CRM__SFDC_PRODUCT_ID__C, IA_CRM__STANDARD_COST__C, IA_CRM__SYNCED_WITH_INTACCT_DATE__C, IA_CRM__SYNC_WITH_INTACCT__C, IA_CRM__TAXABLE__C, IA_CRM__UNIT_OF_MEASURE__C, ID, ISACTIVE, ISDELETED, IS_PACK__C, LASTMODIFIEDBYID, LASTMODIFIEDDATE, LICENSE_TYPE__C, LINE_EDITOR_DESCRIPTION__C, LOB__C, NAME, PRODUCTCODE, PRODUCT_LINE__C, REMOVE_MONTHLY_CPQ_SCREEN__C, REQUIRES_SERVICES__C, SANDBOX_SYNC_EXTERNAL_ID__C, SERVICE_EVENT_MRR__C
      , SYSTEMMODSTAMP, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, LASTREFERENCEDDATE, LASTVIEWEDDATE
      -- 2021/01/05
      , SBQQ__EXCLUDEFROMOPPORTUNITY__C, SBQQ__PRICINGMETHODEDITABLE__C, SBQQ__DEFAULTPRICINGTABLE__C, SBQQ__HIDDEN__C, SBQQ__RECONFIGURATIONDISABLED__C
        , SBQQ__ENABLELARGECONFIGURATION__C, SBQQ__PRICINGMETHOD__C, SBQQ__OPTIONAL__C, SBQQ__NEWQUOTEGROUP__C, SBQQ__BLOCKPRICINGFIELD__C
        , SBQQ__SUBSCRIPTIONTYPE__C, SBQQ__EXCLUDEFROMMAINTENANCE__C, SBQQ__QUANTITYEDITABLE__C, SBQQ__TAXCODE__C, SBQQ__HASCONFIGURATIONATTRIBUTES__C
        , SBQQ__INCLUDEINMAINTENANCE__C, SBQQ__EXTERNALLYCONFIGURABLE__C, SBQQ__ASSETAMENDMENTBEHAVIOR__C, SBQQ__HIDEPRICEINSEARCHRESULTS__C
        , SBQQ__TAXABLE__C, SBQQ__SUBSCRIPTIONBASE__C, SBQQ__ASSETCONVERSION__C, SBQQ__DESCRIPTIONLOCKED__C, SBQQ__PRICEEDITABLE__C
        , SBQQ__DEFAULTQUANTITY__C, SBQQ__OPTIONSELECTIONMETHOD__C, SBQQ__NONPARTNERDISCOUNTABLE__C, SBQQ__SUBSCRIPTIONPRICING__C
        , SBQQ__SUBSCRIPTIONPERCENT__C, SBQQ__CUSTOMCONFIGURATIONREQUIRED__C, SBQQ__COSTEDITABLE__C, SBQQ__ALLOCATEPOTONORDERS__C
        , SBQQ__COMPONENT__C, SBQQ__NONDISCOUNTABLE__C
-- 2021/01/07
       , SBQQ__SUBSCRIPTIONTERM__C, SBQQ__SORTORDER__C
-- change -- add latest columns  
	, SNAP_LOAD_AT
FROM
-- change -- update to most recent snap	
	APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1604740678944_1610013853179
UNION
SELECT
AVA_SFCORE__TAX_CODE__C, CANUSEREVENUESCHEDULE, CATALOG_GROUP__C, CC_REPORTS__C, CC_UNIT_PRICE__C, CREATEDBYID, CREATEDDATE, CRMC_ORG_PRODUCT_ID__C, DESCRIPTION, ENTITY__C, EXCLUDE_FROM_MRR__C, FAMILY, FY16_REVENUE_TYPE__C, HOURLY_RATE__C, HOURS__C, IA_CRM__BILLING_METHOD__C, IA_CRM__BILLING_TEMPLATE__C, IA_CRM__COST_METHOD__C, IA_CRM__DESCRIPTION_ON_SALES_TRANSACTIONS__C, IA_CRM__FLAT_FIXED_AMOUNT_FREQUENCY__C, IA_CRM__INTACCT_ENTITY_ID__C, IA_CRM__INTACCT_ENTITY__C, IA_CRM__INTACCT_SYNC_ERRORS__C, IA_CRM__INTACCT_SYNC_STATUS_IMAGE__C, IA_CRM__INTACCT_SYNC_STATUS__C, IA_CRM__ITEM_TYPE__C, IA_CRM__MRR__C, IA_CRM__SFDC_PRODUCT_ID__C, IA_CRM__STANDARD_COST__C, IA_CRM__SYNCED_WITH_INTACCT_DATE__C, IA_CRM__SYNC_WITH_INTACCT__C, IA_CRM__TAXABLE__C, IA_CRM__UNIT_OF_MEASURE__C, ID, ISACTIVE, ISDELETED, IS_PACK__C, LASTMODIFIEDBYID, LASTMODIFIEDDATE, LICENSE_TYPE__C, LINE_EDITOR_DESCRIPTION__C, LOB__C, NAME, PRODUCTCODE, PRODUCT_LINE__C, REMOVE_MONTHLY_CPQ_SCREEN__C, REQUIRES_SERVICES__C, SANDBOX_SYNC_EXTERNAL_ID__C, SERVICE_EVENT_MRR__C
      , SYSTEMMODSTAMP, _SDC_BATCHED_AT, _SDC_EXTRACTED_AT, _SDC_RECEIVED_AT, _SDC_SEQUENCE, _SDC_TABLE_VERSION, LASTREFERENCEDDATE, LASTVIEWEDDATE
      -- 2021/01/05
      , SBQQ__EXCLUDEFROMOPPORTUNITY__C, SBQQ__PRICINGMETHODEDITABLE__C, SBQQ__DEFAULTPRICINGTABLE__C, SBQQ__HIDDEN__C, SBQQ__RECONFIGURATIONDISABLED__C
        , SBQQ__ENABLELARGECONFIGURATION__C, SBQQ__PRICINGMETHOD__C, SBQQ__OPTIONAL__C, SBQQ__NEWQUOTEGROUP__C, SBQQ__BLOCKPRICINGFIELD__C
        , SBQQ__SUBSCRIPTIONTYPE__C, SBQQ__EXCLUDEFROMMAINTENANCE__C, SBQQ__QUANTITYEDITABLE__C, SBQQ__TAXCODE__C, SBQQ__HASCONFIGURATIONATTRIBUTES__C
        , SBQQ__INCLUDEINMAINTENANCE__C, SBQQ__EXTERNALLYCONFIGURABLE__C, SBQQ__ASSETAMENDMENTBEHAVIOR__C, SBQQ__HIDEPRICEINSEARCHRESULTS__C
        , SBQQ__TAXABLE__C, SBQQ__SUBSCRIPTIONBASE__C, SBQQ__ASSETCONVERSION__C, SBQQ__DESCRIPTIONLOCKED__C, SBQQ__PRICEEDITABLE__C
        , SBQQ__DEFAULTQUANTITY__C, SBQQ__OPTIONSELECTIONMETHOD__C, SBQQ__NONPARTNERDISCOUNTABLE__C, SBQQ__SUBSCRIPTIONPRICING__C
        , SBQQ__SUBSCRIPTIONPERCENT__C, SBQQ__CUSTOMCONFIGURATIONREQUIRED__C, SBQQ__COSTEDITABLE__C, SBQQ__ALLOCATEPOTONORDERS__C
        , SBQQ__COMPONENT__C, SBQQ__NONDISCOUNTABLE__C
-- 2021/01/07
       , NULL AS SBQQ__SUBSCRIPTIONTERM__C, NULL AS SBQQ__SORTORDER__C
-- change -- remove NULL AS from previous round
-- change -- ADD newest Columns as NULL AS  	
	, SNAP_LOAD_AT
FROM
	APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP_1
)
, the_unique AS (
	SELECT ID
         , _SDC_EXTRACTED_AT 
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY ID
         , _SDC_EXTRACTED_AT 
)
	SELECT A.*
	     , to_date(SYSTEMMODSTAMP) AS ACTIVITY_DATE
	     , dateadd(day, -1, to_date(A."_SDC_EXTRACTED_AT")) AS EXTRACT_DATE
	     , dateadd(day, -1, to_date(A."SNAP_LOAD_AT")) AS REPORTING_DATE	
	FROM                 the_union A
	INNER JOIN           the_unique B
	             ON  A.ID = B.ID
	             AND A._SDC_EXTRACTED_AT = B._SDC_EXTRACTED_AT
	             AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;	

SELECT count(*)
     , ID
     , _SDC_EXTRACTED_AT 
FROM APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_HISTORY
group by ID
       , _SDC_EXTRACTED_AT 
having count(*) > 1
-- 0 needs to always come out as zero
;

select count(distinct ID)
FROM APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_HISTORY
--  642
;

select count(distinct ID, _SDC_EXTRACTED_AT)
FROM APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_HISTORY
--  2533
;


