CREATE OR REPLACE VIEW APTTUS_DW.SNAPSHOTS.PROPOSAL_LINEITEM_A1_HISTORY 
COMMENT = 'Union PROPOSAL_LINEITEM_A1 snapshots to make complete history' 
AS
WITH the_union AS (
        SELECT ACV_VALUE__C, APTS_IS_PS_TRAINING_PRODUCT__C, APTS_IS_SUBSCRIPTION_PRODUCT__C, APTS_IS_SUPPORT_PRODUCT__C, APTTUS_PROPOSAL__DESCRIPTION__C, APTTUS_PROPOSAL__EXT_NET_PRICE__C, APTTUS_PROPOSAL__EXT_PRICE__C, APTTUS_PROPOSAL__PRODUCT__C, APTTUS_PROPOSAL__PROPOSAL__C, APTTUS_PROPOSAL__UNIT_NET_PRICE__C, APTTUS_QPAPPROV__APPROVAL_STATUS__C, APTTUS_QPCONFIG__ADJUSTEDPRICE__C, APTTUS_QPCONFIG__ADJUSTMENTAMOUNT__C, APTTUS_QPCONFIG__ADJUSTMENTTYPE__C, APTTUS_QPCONFIG__ASSETLINEITEMID__C, APTTUS_QPCONFIG__ATTRIBUTEVALUEID__C, APTTUS_QPCONFIG__AUTOACTIVATEORDER__C
        , APTTUS_QPCONFIG__AUTOCREATEBILL__C, APTTUS_QPCONFIG__AUTOCREATEREVENUE__C, APTTUS_QPCONFIG__AUTORENEWALTERM__C, APTTUS_QPCONFIG__AUTORENEWALTYPE__C, APTTUS_QPCONFIG__AUTORENEW__C, APTTUS_QPCONFIG__BASECOSTOVERRIDE__C, APTTUS_QPCONFIG__BASECOST__C, APTTUS_QPCONFIG__BASEEXTENDEDCOST__C, APTTUS_QPCONFIG__BASEEXTENDEDPRICE__C, APTTUS_QPCONFIG__BASEPRICEMETHOD__C, APTTUS_QPCONFIG__BASEPRICEOVERRIDE__C, APTTUS_QPCONFIG__BASEPRICE__C, APTTUS_QPCONFIG__BILLINGFREQUENCY__C, APTTUS_QPCONFIG__BILLINGPREFERENCEID__C, APTTUS_QPCONFIG__BILLINGRULE__C, APTTUS_QPCONFIG__BILLTOACCOUNTID__C
        , APTTUS_QPCONFIG__CHARGETYPE__C, APTTUS_QPCONFIG__CLASSIFICATIONHIERARCHY__C, APTTUS_QPCONFIG__CLASSIFICATIONID__C, APTTUS_QPCONFIG__COMMENTS__C, APTTUS_QPCONFIG__CONFIGURATIONID__C, APTTUS_QPCONFIG__CONTRACTNUMBERS__C, APTTUS_QPCONFIG__COST__C, APTTUS_QPCONFIG__DELTAPRICE__C, APTTUS_QPCONFIG__DELTAQUANTITY__C, APTTUS_QPCONFIG__DERIVEDFROMID__C, APTTUS_QPCONFIG__ENDDATE__C, APTTUS_QPCONFIG__EXTENDEDCOST__C, APTTUS_QPCONFIG__EXTENDEDPRICE__C, APTTUS_QPCONFIG__EXTENDEDQUANTITY__C, APTTUS_QPCONFIG__FLATOPTIONPRICE__C, APTTUS_QPCONFIG__FREQUENCY__C, APTTUS_QPCONFIG__FULFILLMENTSTATUS__C
        , APTTUS_QPCONFIG__GROUPADJUSTMENTPERCENT__C, APTTUS_QPCONFIG__HASATTRIBUTES__C, APTTUS_QPCONFIG__HASINCENTIVES__C, APTTUS_QPCONFIG__HASOPTIONS__C, APTTUS_QPCONFIG__HIDEINVOICEDISPLAY__C, APTTUS_QPCONFIG__ISASSETPRICING__C, APTTUS_QPCONFIG__ISCUSTOMPRICING__C, APTTUS_QPCONFIG__ISOPTIONAL__C, APTTUS_QPCONFIG__ISOPTIONROLLUPLINE__C, APTTUS_QPCONFIG__ISPRIMARYLINE__C, APTTUS_QPCONFIG__ISPRIMARYRAMPLINE__C, APTTUS_QPCONFIG__ISUSAGETIERMODIFIABLE__C, APTTUS_QPCONFIG__ITEMSEQUENCE__C, APTTUS_QPCONFIG__LINENUMBER__C, APTTUS_QPCONFIG__LINESTATUS__C, APTTUS_QPCONFIG__LINETYPE__C, APTTUS_QPCONFIG__LISTPRICE__C
        , APTTUS_QPCONFIG__NETADJUSTMENTPERCENT__C, APTTUS_QPCONFIG__NETPRICE__C, APTTUS_QPCONFIG__NETUNITPRICE__C, APTTUS_QPCONFIG__OPTIONCOST__C, APTTUS_QPCONFIG__OPTIONID__C, APTTUS_QPCONFIG__OPTIONPRICE__C, APTTUS_QPCONFIG__PARENTBUNDLENUMBER__C, APTTUS_QPCONFIG__PRICEADJUSTMENT__C, APTTUS_QPCONFIG__PRICEGROUP__C, APTTUS_QPCONFIG__PRICEINCLUDEDINBUNDLE__C, APTTUS_QPCONFIG__PRICELISTID__C, APTTUS_QPCONFIG__PRICELISTITEMID__C, APTTUS_QPCONFIG__PRICEMETHOD__C, APTTUS_QPCONFIG__PRICETYPE__C, APTTUS_QPCONFIG__PRICEUOM__C, APTTUS_QPCONFIG__PRIMARYLINENUMBER__C, APTTUS_QPCONFIG__PRODUCTOPTIONID__C
        , APTTUS_QPCONFIG__QUANTITY2__C, APTTUS_QPCONFIG__SELLINGFREQUENCY__C, APTTUS_QPCONFIG__SELLINGTERM__C, APTTUS_QPCONFIG__SELLINGUOM__C, APTTUS_QPCONFIG__SHIPTOACCOUNTID__C, APTTUS_QPCONFIG__STARTDATE__C, APTTUS_QPCONFIG__SUMMARYGROUPID__C, APTTUS_QPCONFIG__TAXABLE__C, APTTUS_QPCONFIG__TAXINCLUSIVE__C, APTTUS_QPCONFIG__TERM__C, APTTUS_QPCONFIG__TOTALQUANTITY__C, APTTUS_QPCONFIG__UOM__C, BUDGETARY_PRODUCT_NAME__C, CREATEDBYID, CREATEDDATE, CURRENCYISOCODE, END_DATE__C, ID, ISDELETED, LASTMODIFIEDBYID, LASTMODIFIEDDATE, LINE_SEQUENCE__C, "NAME", NET_MARGIN__C, PRODUCT_FAMILY__C
        , PRODUCT_PRICE_FOR_SANDBOX__C, RENEWAL_UPLIFT_AMOUNT__C, SELECTED_ATTRIBUTE_VALUE_FOR_PRODUCT__C, START_DATE__C, SYSTEMMODSTAMP, TURBO_ENGINE_CLASS__C, YEAR_1__C, YEAR_2__C, YEAR_3__C, YEAR_4__C, YEAR_5__C, YEAR_TOTAL_NOT_ROLL_UP_FLAG__C
        , "_SDC_BATCHED_AT", "_SDC_EXTRACTED_AT", "_SDC_RECEIVED_AT", "_SDC_SEQUENCE", "_SDC_TABLE_VERSION"
-- change -- add latest columns  
       , SNAP_LOAD_AT
-- change -- update to most recent snap 
        FROM APTTUS_DW.SNAPSHOTS.PROPOSAL_LINEITEM_A1_SNAP_1604727288019_1609891467124
/* UNION
SELECT

-- change -- ADD newest Columns as NULL AS    
       , SNAP_LOAD_AT
FROM
       APTTUS_DW.SNAPSHOTS.PROPOSAL_LINEITEM_A1_SNAP_1 */
)
, the_unique AS (
       SELECT ID
         , _SDC_EXTRACTED_AT 
         , MAX(SNAP_LOAD_AT) AS SNAP_LOAD_AT
    FROM the_union  
    GROUP BY ID
         , _SDC_EXTRACTED_AT 
)
       SELECT A.*
            , to_date(SYSTEMMODSTAMP) AS ACTIVITY_DATE
            , dateadd(day, -1, to_date(A."_SDC_EXTRACTED_AT")) AS EXTRACT_DATE
            , dateadd(day, -1, to_date(A."SNAP_LOAD_AT")) AS REPORTING_DATE    
       FROM                 the_union A
       INNER JOIN           the_unique B
                    ON  A.ID = B.ID
                    AND A._SDC_EXTRACTED_AT = B._SDC_EXTRACTED_AT
                    AND A.SNAP_LOAD_AT = B.SNAP_LOAD_AT
;
