

show tasks IN SCHEMA SNAPSHOTS;

alter task APTTUS_DW.SNAPSHOTS.ACCOUNT_C1_SNAP resume; 
alter task APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP resume; 
alter task APTTUS_DW.SNAPSHOTS.FMA_VALUES_SNAP resume; 
alter task APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_SNAP resume;  
alter task APTTUS_DW.SNAPSHOTS.LMA_LICENSE_CLMCPQ_SNAP resume; 
alter task APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C1_SNAP resume; 
alter task APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_HISTORYSNAP resume; 
alter task APTTUS_DW.SNAPSHOTS.PRODUCT2_C1_SNAP resume; 

show tasks IN SCHEMA PRODUCT;
SHOW procedures IN SCHEMA PRODUCT;

alter task APTTUS_DW.PRODUCT.FILL_COLLABORATE_MONTHLY_ACTIVITY resume; 
alter task APTTUS_DW.PRODUCT.FILL_COMPOSER_MONTHLY_ACTIVITY resume; 
alter task APTTUS_DW.PRODUCT.FILL_CONTRACTS_MONTHLY_ACTIVITY resume; 
alter task APTTUS_DW.PRODUCT.FILL_FMA_DAILY_ACTIVITY resume; 
alter task APTTUS_DW.PRODUCT.FILL_FMA_MONTHLY_ACTIVITY resume; 
alter task APTTUS_DW.PRODUCT.FILL_LMA_LICENSE_MONTHLY resume; 
alter task APTTUS_DW.PRODUCT.FILL_MONTHLY_ACTIVITY_SCORES resume; 
alter task APTTUS_DW.PRODUCT.FILL_SIGN_MONTHLY_ACTIVITY resume; 

