select ID
     , createddate
     , SYSTEMMODSTAMP
     , LASTMODIFIEDDATE
     , _SDC_BATCHED_AT
     , _SDC_EXTRACTED_AT
     , _SDC_RECEIVED_AT
     , _SDC_SEQUENCE
     , _SDC_TABLE_VERSION     
from  APTTUS_DW.SF_CONGA1_0.SFLMA__LICENSE__C
order by SYSTEMMODSTAMP desc,  
        _SDC_EXTRACTED_AT desc
;

SELECT MAX(SYSTEMMODSTAMP)
from  APTTUS_DW.SF_CONGA1_0.SFLMA__LICENSE__C;

SELECT MAX(_SDC_EXTRACTED_AT)
from  APTTUS_DW.SF_CONGA1_0.SFLMA__LICENSE__C;

select ID
     , createddate
     , SYSTEMMODSTAMP
     , LASTMODIFIEDDATE
     , _SDC_BATCHED_AT
     , _SDC_EXTRACTED_AT
     , _SDC_RECEIVED_AT
     , _SDC_SEQUENCE
     , _SDC_TABLE_VERSION     
from  APTTUS_DW.SNAPSHOTS.OPPORTUNITY_SNAP_1
order by SYSTEMMODSTAMP desc,  
         _SDC_EXTRACTED_AT desc
;

SELECT MAX(SYSTEMMODSTAMP) FROM APTTUS_DW.SF_CONGA1_0.OPPORTUNITY_SNAP_1596552099072;

--UPDATE APTTUS_DW.DATA_LINEAGE_DICTIONARY.SNAPSHOT_CONTROL
   set START_AFTER_SYSTEMMODSTAMP = (SELECT MAX(SYSTEMMODSTAMP) FROM APTTUS_DW.SF_CONGA1_0.OPPORTUNITY_SNAP_1596552099072)
     , LAST_SDC_EXTRACTED_AT = (SELECT MAX(_SDC_EXTRACTED_AT) FROM APTTUS_DW.SF_CONGA1_0.OPPORTUNITY_SNAP_1596552099072)
     , LAST_SNAPSHOT_START = (CONVERT_TIMEZONE('UTC',current_timestamp()))
     , CURRENT_SDC_TABLE_VERSION = (SELECT MAX(_SDC_TABLE_VERSION) FROM APTTUS_DW.SF_CONGA1_0.OPPORTUNITY_SNAP_1596552099072)
   WHERE OUT_CATALOG = 'APTTUS_DW'
     and OUT_SCHEMA = 'SNAPSHOTS'
     and OUT_OBJECT_NAME = '_SNAP_'
     and OUT_OBJECT_TYPE = 'Snap Table'
  ;

SELECT MAX(SYSTEMMODSTAMP), MAX(_SDC_EXTRACTED_AT), MAX(_SDC_TABLE_VERSION)
FROM APTTUS_DW.SNAPSHOTS.ASSET_C1_SNAP_;

show tasks in schema SF_CONGA1_0; 
alter task APTTUS_DW.SF_CONGA1_0.C1_OPPORTUNITY_HIST suspend; --resume
--alter task APTTUS_DW.SNAPSHOTS.LMA_LICENSE_C1_SNAP resume;

--create table APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C1_SNAP_1 
as
select distinct * from APTTUS_DW.SF_CONGA1_0.OPPORTUNITY_SNAP_1596552099072
;



