
SELECT *
FROM APTTUS_DW.SNAPSHOTS.SNAP_ACTIVITY_LOG
order by CREATEDTIME desc
;

SELECT CREATEDTIME, PROCEDURE_NAME, STEP_NAME, ERROR_CODE, ERROR_STATE, ERROR_MESSAGE, STACK_TRACE, CREATEDBYID
FROM APTTUS_DW.SNAPSHOTS.SNAP_ACTIVITY_LOG
UNION ALL
SELECT CREATEDTIME, PROCEDURE_NAME, STEP_NAME, ERROR_CODE, ERROR_STATE, ERROR_MESSAGE, STACK_TRACE, CREATEDBYID
FROM APTTUS_DW.PRODUCT.ACTIVITY_LOG
order by CREATEDTIME desc
;

SELECT PROC_OR_STEP, RUN_FOR_MONTH, OPERATOR, EXECUTION_TIME, STATUS 
FROM APTTUS_DW.PRODUCT.PRODUCT_METRICS_RUN_CONTROL
order by EXECUTION_TIME desc
;
