
--DROP TABLE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL;


CREATE TABLE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL 
        ( IN_CATALOG VARCHAR(16777216)
        , IN_SCHEMA VARCHAR(16777216)
        , IN_OBJECT_NAME VARCHAR(16777216)
        , IN_OBJECT_TYPE VARCHAR(16777216) DEFAULT 'Stitch Table'
        , OUT_CATALOG VARCHAR(16777216)
        , OUT_SCHEMA VARCHAR(16777216)
        , OUT_OBJECT_NAME VARCHAR(16777216)
        , OUT_OBJECT_TYPE VARCHAR(16777216) DEFAULT 'Table'
        , CURRENT_SDC_TABLE_VERSION NUMBER
        , LAST_SDC_EXTRACTED_AT TIMESTAMPTZ
        , START_AFTER_SYSTEMMODSTAMP TIMESTAMPTZ
        , LAST_SNAPSHOT_START TIMESTAMPTZ
        , DESCRIPTION VARCHAR(16777216)
        , CREATEDBYID VARCHAR(16777216) DEFAULT 'CURRENT_USER()'
        , CREATEDTIME TIMESTAMPTZ DEFAULT CONVERT_TIMEZONE('UTC', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9)))
        , ID VARCHAR(16777216) DEFAULT 'UUID_STRING()' NOT NULL
        , CURRENT_SNAPSHOT_TABLE_VERSION NUMBER
        , PRIMARY KEY (ID));

/*
CREATE TABLE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL 
/* CAUTION! will delete any stranded rows in the STREAM * /
         ( IN_CATALOG VARCHAR(16777216)
         , IN_SCHEMA VARCHAR(16777216)
         , IN_OBJECT_NAME VARCHAR(16777216)
         , IN_OBJECT_TYPE VARCHAR(16777216) default 'Stitch Table'
         , OUT_CATALOG VARCHAR(16777216)
         , OUT_SCHEMA VARCHAR(16777216)
         , OUT_OBJECT_NAME VARCHAR(16777216)
         , OUT_OBJECT_TYPE VARCHAR(16777216) default 'Table'
         , CURRENT_SDC_TABLE_VERSION NUMBER(38,0)
         , LAST_SDC_EXTRACTED_AT TIMESTAMPTZ
         , START_AFTER_SYSTEMMODSTAMP TIMESTAMPTZ
         , LAST_SNAPSHOT_START TIMESTAMPTZ 
         , DESCRIPTION VARCHAR(16777216)
         , CREATEDBYID VARCHAR(16777216) default current_user
         , CREATEDTIME TIMESTAMPTZ default CONVERT_TIMEZONE('UTC',current_timestamp())
         , ID VARCHAR(16777216) NOT NULL default UUID_STRING()         
         , PRIMARY KEY (ID));
*/
ALTER TABLE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL ADD COLUMN CURRENT_SNAPSHOT_TABLE_VERSION NUMBER(38,0);

         
         
--INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- C1 Opportunity
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'OPPORTUNITY', 'Stitch Table', 'APTTUS_DW', 'SF_CONGA1_0', 'OPPORTUNITY_SNAP_', 'Snap Table'
       , 1596552099072, '2020-08-27 14:45:01.000 Z', '2020-08-27 14:45:26.341 Z', '2020-08-27 15:45:26.341 Z', 'C1 Opportunity Snap');

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- FMA_VALUES
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'SFFMA__FEATUREPARAMETERINTEGER__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'FMA_VALUES_SNAP_', 'Snap Table'
       , 1595012858504, '2020-09-01 14:51:56.000 Z', '2020-09-01 14:53:31.046 Z', '2020-09-02 13:45:00.000 Z', 'Snap of FMA parameter integers (the daily values)');

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- ASSET C1
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'ASSET', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'ASSET_C1_SNAP_', 'Snap Table'
       , 1595529536375, '2020-09-04 09:41:06.000 Z', '2020-09-04 14:55:50.027 Z', '2020-09-04 15:45:00.000 Z', 'Daily Snap of Asset C1');


INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- Account C1
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'ACCOUNT', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'ACCOUNT_C1_SNAP_', 'Snap Table'
       , 1596811849331, '2020-01-01 09:41:06.000 Z', '2020-01-01 14:55:50.027 Z', '2020-09-08 12:00:00.000 Z', 'Daily Snap of Account C1');

UPDATE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL set CURRENT_SNAPSHOT_TABLE_VERSION = 0 WHERE OUT_OBJECT_NAME = 'ACCOUNT_C1_SNAP_';       
       

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- LMA LICENSE C1
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'SFLMA__LICENSE__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'LMA_LICENSE_C1_SNAP_', 'Snap Table'
       , 1595011981947, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'Daily Snap of SFLMA__LICENSES for C1');

update APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL
   set DESCRIPTION = 'Daily Snap of SFLMA__LICENSES for C1'
where OUT_OBJECT_NAME = 'LMA_LICENSE_C1_SNAP_';

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- Opportunity C1
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'OPPORTUNITY', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'OPPORTUNITY_C1_SNAP_', 'Snap Table'
       , 1, '2020-09-08 14:54:19.000 Z', '2020-09-08 14:54:26.927 Z', '2020-09-08 12:00:00.000 Z', 'Daily Snap of Opportunity for C1');



--SHOW PARAMETERS LIKE 'TIMEZONE';

select * from APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL ;
--delete from APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL 
;

--update APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL
--   set START_AFTER_SYSTEMMODSTAMP = '2020-09-07 14:52:50.000 Z'
--     , LAST_SDC_EXTRACTED_AT = '2020-09-07 14:52:50.447 Z' 
--   WHERE ID = '2ffdd15d-0587-4126-8136-3a25925fe45b' 
--   ;

CREATE TABLE APTTUS_DW.SNAPSHOTS.SNAP_ACTIVITY_LOG
       (  procedure_name string
        , step_name string
        , error_code number default 0
        , error_state string default null
        , error_message string default 'Success'
        , stack_trace string default null
        , CREATEDBYID VARCHAR(16777216) default current_user
        , CREATEDTIME TIMESTAMPTZ default CONVERT_TIMEZONE('UTC',current_timestamp())        
        );

show tasks IN SCHEMA SNAPSHOTS;

