
--DROP TABLE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL;


CREATE TABLE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL 
        ( IN_CATALOG VARCHAR(16777216)
        , IN_SCHEMA VARCHAR(16777216)
        , IN_OBJECT_NAME VARCHAR(16777216)
        , IN_OBJECT_TYPE VARCHAR(16777216) DEFAULT 'Stitch Table'
        , OUT_CATALOG VARCHAR(16777216)
        , OUT_SCHEMA VARCHAR(16777216)
        , OUT_OBJECT_NAME VARCHAR(16777216)
        , OUT_OBJECT_TYPE VARCHAR(16777216) DEFAULT 'Table'
        , CURRENT_SDC_TABLE_VERSION NUMBER
        , LAST_SDC_EXTRACTED_AT TIMESTAMPTZ
        , START_AFTER_SYSTEMMODSTAMP TIMESTAMPTZ
        , LAST_SNAPSHOT_START TIMESTAMPTZ
        , DESCRIPTION VARCHAR(16777216)
        , CREATEDBYID VARCHAR(16777216) DEFAULT 'CURRENT_USER()'
        , CREATEDTIME TIMESTAMPTZ DEFAULT CONVERT_TIMEZONE('UTC', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9)))
        , ID VARCHAR(16777216) DEFAULT 'UUID_STRING()' NOT NULL
        , CURRENT_SNAPSHOT_TABLE_VERSION NUMBER
        , PRIMARY KEY (ID));

/*
CREATE TABLE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL 
/* CAUTION! will delete any stranded rows in the STREAM * /
         ( IN_CATALOG VARCHAR(16777216)
         , IN_SCHEMA VARCHAR(16777216)
         , IN_OBJECT_NAME VARCHAR(16777216)
         , IN_OBJECT_TYPE VARCHAR(16777216) default 'Stitch Table'
         , OUT_CATALOG VARCHAR(16777216)
         , OUT_SCHEMA VARCHAR(16777216)
         , OUT_OBJECT_NAME VARCHAR(16777216)
         , OUT_OBJECT_TYPE VARCHAR(16777216) default 'Table'
         , CURRENT_SDC_TABLE_VERSION NUMBER(38,0)
         , LAST_SDC_EXTRACTED_AT TIMESTAMPTZ
         , START_AFTER_SYSTEMMODSTAMP TIMESTAMPTZ
         , LAST_SNAPSHOT_START TIMESTAMPTZ 
         , DESCRIPTION VARCHAR(16777216)
         , CREATEDBYID VARCHAR(16777216) default current_user
         , CREATEDTIME TIMESTAMPTZ default CONVERT_TIMEZONE('UTC',current_timestamp())
         , ID VARCHAR(16777216) NOT NULL default UUID_STRING()         
         , PRIMARY KEY (ID));
*/
ALTER TABLE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL ADD COLUMN CURRENT_SNAPSHOT_TABLE_VERSION NUMBER(38,0);

         
         
--INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- C1 Opportunity
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'OPPORTUNITY', 'Stitch Table', 'APTTUS_DW', 'SF_CONGA1_0', 'OPPORTUNITY_SNAP_', 'Snap Table'
       , 1596552099072, '2020-08-27 14:45:01.000 Z', '2020-08-27 14:45:26.341 Z', '2020-08-27 15:45:26.341 Z', 'C1 Opportunity Snap');

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- FMA_VALUES
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'SFFMA__FEATUREPARAMETERINTEGER__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'FMA_VALUES_SNAP_', 'Snap Table'
       , 1595012858504, '2020-09-01 14:51:56.000 Z', '2020-09-01 14:53:31.046 Z', '2020-09-02 13:45:00.000 Z', 'Snap of FMA parameter integers (the daily values)');

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- ASSET C1
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'ASSET', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'ASSET_C1_SNAP_', 'Snap Table'
       , 1595529536375, '2020-09-04 09:41:06.000 Z', '2020-09-04 14:55:50.027 Z', '2020-09-04 15:45:00.000 Z', 'Daily Snap of Asset C1');


INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- Account C1
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'ACCOUNT', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'ACCOUNT_C1_SNAP_', 'Snap Table'
       , 1596811849331, '2020-01-01 09:41:06.000 Z', '2020-01-01 14:55:50.027 Z', '2020-09-08 12:00:00.000 Z', 'Daily Snap of Account C1');

UPDATE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL set CURRENT_SNAPSHOT_TABLE_VERSION = 0 WHERE OUT_OBJECT_NAME = 'ACCOUNT_C1_SNAP_';       
       

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- LMA LICENSE C1
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'SFLMA__LICENSE__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'LMA_LICENSE_C1_SNAP_', 'Snap Table'
       , 1595011981947, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'Daily Snap of SFLMA__LICENSES for C1');

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- LMA LICENSE CLMCPQ
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SALESFORCE_CLMCPQ', 'SFLMA__LICENSE__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'LMA_LICENSE_CLMCPQ_SNAP_', 'Snap Table'
       , 1600188187559, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'Daily Snap of SFLMA__LICENSES for CLMCPQ');


update APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL
   set DESCRIPTION = 'Daily Snap of SFLMA__LICENSES for C1'
where OUT_OBJECT_NAME = 'LMA_LICENSE_C1_SNAP_';

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- Opportunity C1
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'OPPORTUNITY', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'OPPORTUNITY_C1_SNAP_', 'Snap Table'
       , 1, '2020-09-08 14:54:19.000 Z', '2020-09-08 14:54:26.927 Z', '2020-09-08 12:00:00.000 Z', 'Daily Snap of Opportunity for C1');

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- product2 for c1
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_0', 'PRODUCT2', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'PRODUCT2_C1_SNAP_', 'Snap Table'
       , 0, '2020-09-11 15:32:16.000 Z', '2020-09-14 14:35:29.552 Z', '2020-09-08 12:00:00.000 Z', 'Daily Snap of Product2 for C1');
UPDATE APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL 
   set CURRENT_SNAPSHOT_TABLE_VERSION = 0
   WHERE OUT_CATALOG = 'APTTUS_DW'
     and OUT_SCHEMA = 'SNAPSHOTS'
     and OUT_OBJECT_NAME = 'PRODUCT2_C1_SNAP_'
     and OUT_OBJECT_TYPE = 'Snap Table'
;     

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- OPPORTUNITY c2 snap 
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, CURRENT_SNAPSHOT_TABLE_VERSION
      , START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_PRODUCTION', 'OPPORTUNITY_C2', 'VIEW', 'APTTUS_DW', 'SNAPSHOTS', 'OPPORTUNITY_C2_HISTORY', 'Snap Table'
       , 0, 0
       , '2020-10-06 14:54:19.000 Z', NULL, NULL, 'Daily Snap of Opportunity C2');

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- APTTUS_CONFIG2__ASSETLINEITEM__C
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_PRODUCTION', 'APTTUS_CONFIG2__ASSETLINEITEM__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'ASSETLINEITEM_SNAP_', 'Snap Table'
       , 1604728034695, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'Daily Snap of AssetLineItem');

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL -- CURRENCYTYPE
      (IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION) 
VALUES ('APTTUS_DW', 'SF_PRODUCTION', 'CURRENCYTYPE', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'CURRENCYTYPE_SNAP_', 'Snap Table'
       , 1604727252490, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'Daily Snap of CurrencyType');

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- A1 Opportunity
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION
      , CURRENT_SNAPSHOT_TABLE_VERSION) 
VALUES ('APTTUS_DW', 'SF_PRODUCTION', 'OPPORTUNITY', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'OPPORTUNITY_A1_SNAP_', 'Snap Table'
       , 1, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'A1 Opportunity Snap'
       , 0);

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- A1 Account
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION
      , CURRENT_SNAPSHOT_TABLE_VERSION) 
VALUES ('APTTUS_DW', 'SF_PRODUCTION', 'ACCOUNT', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'ACCOUNT_A1_SNAP_', 'Snap Table'
       , 1, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'A1 Account Snap'
       , 0);

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- A1 product2
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION
      , CURRENT_SNAPSHOT_TABLE_VERSION) 
VALUES ('APTTUS_DW', 'SF_PRODUCTION', 'PRODUCT2', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'PRODUCT2_A1_SNAP_', 'Snap Table'
       , 1, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'A1 Product2 Snap'
       , 0);             
         
INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- SF_PRODUCTION.APTTUS_PROPOSAL__PROPOSAL__C      
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION
      , CURRENT_SNAPSHOT_TABLE_VERSION) 
VALUES ('APTTUS_DW', 'SF_PRODUCTION', 'APTTUS_PROPOSAL__PROPOSAL__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'PROPOSAL_A1_SNAP_', 'Snap Table'
       , 1, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'A1 Proposal Snap from APTTUS_PROPOSAL__PROPOSAL__C'
       , 0);              

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- SF_PRODUCTION.APTTUS_PROPOSAL__PROPOSAL_LINE_ITEM__C      
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION
      , CURRENT_SNAPSHOT_TABLE_VERSION) 
VALUES ('APTTUS_DW', 'SF_PRODUCTION', 'APTTUS_PROPOSAL__PROPOSAL_LINE_ITEM__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'PROPOSAL_LINEITEM_A1_SNAP_', 'Snap Table'
       , 1, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'A1 Proposal Snap from APTTUS_PROPOSAL__PROPOSAL_LINE_ITEM__C'
       , 0);               
 
INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- SF_PRODUCTION.APTTUS_CONFIG2__PRODUCTCONFIGURATION__C      
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION
      , CURRENT_SNAPSHOT_TABLE_VERSION) 
VALUES ('APTTUS_DW', 'SF_PRODUCTION', 'APTTUS_CONFIG2__PRODUCTCONFIGURATION__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'PRODUCTCONFIGURATION_A1_SNAP_', 'Snap Table'
       , 1, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'A1 Proposal Snap from APTTUS_CONFIG2__PRODUCTCONFIGURATION__C'
       , 0);            
       
INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- SF_CONGA1_1.SBQQ__QUOTE__C     
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION
      , CURRENT_SNAPSHOT_TABLE_VERSION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_1', 'SBQQ__QUOTE__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'QUOTE_C1_SNAP_', 'Snap Table'
       , 1, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'C2 Quotes from SF_CONGA1_1.SBQQ__QUOTE__C'
       , 0);   

INSERT INTO APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL  -- SF_CONGA1_1.SBQQ__QUOTELINE__C     
      ( IN_CATALOG, IN_SCHEMA, IN_OBJECT_NAME, IN_OBJECT_TYPE, OUT_CATALOG, OUT_SCHEMA, OUT_OBJECT_NAME, OUT_OBJECT_TYPE
      , CURRENT_SDC_TABLE_VERSION, START_AFTER_SYSTEMMODSTAMP, LAST_SDC_EXTRACTED_AT, LAST_SNAPSHOT_START, DESCRIPTION
      , CURRENT_SNAPSHOT_TABLE_VERSION) 
VALUES ('APTTUS_DW', 'SF_CONGA1_1', 'SBQQ__QUOTELINE__C', 'Stitch Table', 'APTTUS_DW', 'SNAPSHOTS', 'QUOTELINE_C1_SNAP_', 'Snap Table'
       , 1, '1900-01-01 09:41:06.000 Z', '1900-01-01 14:55:50.027 Z', CONVERT_TIMEZONE('UTC',current_timestamp()), 'C2 Quotes Line items from SF_CONGA1_1.SBQQ__QUOTELINE__C'
       , 0);   
        
--SHOW PARAMETERS LIKE 'TIMEZONE';

select * from APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL ;
--delete from APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL 
;

--update APTTUS_DW.SNAPSHOTS.SNAPSHOT_CONTROL
--   set START_AFTER_SYSTEMMODSTAMP = '2020-09-07 14:52:50.000 Z'
--     , LAST_SDC_EXTRACTED_AT = '2020-09-07 14:52:50.447 Z' 
--   WHERE ID = '2ffdd15d-0587-4126-8136-3a25925fe45b' 
--   ;

CREATE TABLE APTTUS_DW.SNAPSHOTS.SNAP_ACTIVITY_LOG
       (  procedure_name string
        , step_name string
        , error_code number default 0
        , error_state string default null
        , error_message string default 'Success'
        , stack_trace string default null
        , CREATEDBYID VARCHAR(16777216) default current_user
        , CREATEDTIME TIMESTAMPTZ default CONVERT_TIMEZONE('UTC',current_timestamp())        
        );

show tasks IN SCHEMA SNAPSHOTS;

