
DROP TABLE APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_HISTORY;
-- APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_WEEKLY_HISTORY definition

create TABLE APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_HISTORY (
	CRM_SOURCE VARCHAR(255),
	OPPORTUNITY_ID VARCHAR(16777216),
	SNAPSHOT_DATE DATE,
	A1_PARTNER VARCHAR(16777216),
	ACCOUNT_ID VARCHAR(16777216),
	ACCOUNT_NAME VARCHAR(16777216),
	ACCOUNT_OWNER_NAME VARCHAR(16777216),
	ACCOUNT_URL VARCHAR(16777216),
	ANNUAL_RENEWAL FLOAT,
	ARR NUMBER(19,2),
	AGE_DAYS FLOAT,
	AGE_MONTHS FLOAT,
	AVERAGE_ACV NUMBER(19,2),
	BILLING_FREQUENCY VARCHAR(16777216),
	BOOKINGS_DATE DATE,
	BOOKING_STAMP VARCHAR(16777216),
	C1_PARTNER VARCHAR(16777216),
	C2_STAGE VARCHAR(16777216),
	C2_TYPE VARCHAR(16777216),
	CAMPAIGN_ID VARCHAR(16777216),
	CLOSE_BOOKINGS_DATE DATE,
	CLOSED_REASON_CATEGORY VARCHAR(16777216),
	CLOSED_REASON_DETAILS VARCHAR(16777216),
	CLOSED_REASON_NOTES VARCHAR(16777216),
	CLOSED_REASON_SUBCATEGORY_LOSS VARCHAR(16777216),
	CREATED_DATE DATE,
	CURRENCY VARCHAR(16777216),
	CURRENCY_CONVERSION_RATE FLOAT,
	CURRENT_AVG_MRR_TOTAL FLOAT,
	CUSTOMER_SUPPORT_ID VARCHAR(16777216),
	CUSTOMER_SUPPORT_NAME VARCHAR(16777216),
	DISCOUNT_RECAPTURE_MRR NUMBER(19,2),
	DOWNSELL_CHURN_CATEGORY VARCHAR(16777216),
	DOWNSELL_CHURN_SUB_CATEGORY VARCHAR(16777216),
	END_DATE DATE,
	ESTIMATED_CLOSE_DATE DATE,
	EXPANSION_DOLLARS FLOAT,
	FIRST_YEARS_BILLINGS NUMBER(19,2),
	FISCAL_WEEK VARCHAR(16777216),
	FORECAST_CATEGORY VARCHAR(16777216),
	GEO VARCHAR(16777216),
	HIGHEST_ACHIEVED_STAGE VARCHAR(16777216),
	INBOUND_OUTBOUND_OPPORTUNITY VARCHAR(16777216),
	LAST_EDIT_DATE DATE,
	LEAD_SOURCE VARCHAR(16777216),
	LEAD_SOURCE_DETAIL VARCHAR(16777216),
	MRR_SUB_END DATE,
	MRR_SUB_START DATE,
	NET_NEW_MRR NUMBER(19,2),
	NEXT_STEP VARCHAR(16777216),
	NEXT_STEP_LAST_EDITED TIMESTAMP_TZ(9),
	NN_DISCOUNT_RECAPTURE_ACV NUMBER(19,2),
	OPPORTUNITY_CHANNEL_SOURCE VARCHAR(16777216),
	OPPORTUNITY_NAME VARCHAR(16777216),
	OPPORTUNITY_URL VARCHAR(16777216),
	OPS_APPROVED BOOLEAN,
	OWNER_GEO_STAMP VARCHAR(16777216),
	OWNER_ID VARCHAR(16777216),
	OWNER_NAME VARCHAR(16777216),
	OWNER_ROLE VARCHAR(16777216),
	PLATFORM VARCHAR(16777216),
	PRIMARY_COMPETITOR VARCHAR(16777216),
	PRIMARY_QUOTE_ID VARCHAR(16777216),
	PRODUCTS_OF_INTEREST VARCHAR(16777216),
	PROBABILITY FLOAT,
	RAMPED_ACV NUMBER(19,2),
	REGION VARCHAR(16777216),
	RENEWED_AMOUNT FLOAT,
	RENEWAL_DOLLARS FLOAT,
	RENEWAL_DUE FLOAT,
	RENEWAL_DUE_DATE TIMESTAMP_TZ(9),
	RENEWAL_FORECAST_ARR FLOAT,
	RENEWAL_UPLIFT FLOAT,
	SALES_ENGINEER_NAME VARCHAR(16777216),
	SALES_MRR FLOAT,
	SALES_OPPORTUNITY_ACCEPTED VARCHAR(16777216),
	SALES_OPPORTUNITY_ACCEPTED_DATE DATE,
	SALESFORCE_ORG VARCHAR(16777216),
	SE_ID VARCHAR(16777216),
	SEGMENT VARCHAR(16777216),
	STAGE VARCHAR(16777216),
	STAGE_1_DATE_OF_ENTRY DATE,
	START_DATE DATE,
	SUB_TYPE VARCHAR(16777216),
	TCV_NON_RECURRING NUMBER(19,2),
	TCV_SERVICES NUMBER(19,2),
	TCV_SUBSCRIPTIONS NUMBER(19,2),
	TERM_MONTHS FLOAT,
	TERRITORY VARCHAR(16777216),
	TERRITORY_MANAGER_ID VARCHAR(16777216),
	TERRITORY_MANAGER_NAME VARCHAR(16777216),
	TM_SEGMENT_NAME VARCHAR(16777216),
	TOTAL_DEAL_VALUE NUMBER(19,2),
	TOTAL_RENEWAL_DUE NUMBER(19,2),
	TOTAL_UPSELL_DOWNSELL FLOAT,
	TYPE VARCHAR(16777216),
	VALID_UNTIL_DATE DATE,
	X15_DATE TIMESTAMP_TZ(9),
	XOPPORTUNITY_ID VARCHAR(16777216),
	OPPTY_MODSTAMP TIMESTAMP_TZ,
	ACCNT_MODSTAMP TIMESTAMP_TZ,
	LAST_MODSTAMP TIMESTAMP_TZ,
	CONTACT_ID  VARCHAR(16777216)
)

ALTER TABLE APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_HISTORY ADD COLUMN CONTACT_ID  VARCHAR(16777216);
;
--delete from APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_HISTORY;
update APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_HISTORY
   set SNAPSHOT_DATE = GREATEST(CREATED_DATE, '2020-02-01')
;

--DELETE
from APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_HISTORY
where snapshot_Date = '2020-10-06'
;

INSERT INTO APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_HISTORY
SELECT	  CRM_SOURCE
	, OPPORTUNITY_ID
        , current_date() AS SNAPSHOT_DATE
	, A1_PARTNER
	, ACCOUNT_ID
	, ACCOUNT_NAME
	, ACCOUNT_OWNER_NAME
	, ACCOUNT_URL
	, ANNUAL_RENEWAL
	, ARR
	, AGE_DAYS
	, AGE_MONTHS
	, AVERAGE_ACV
	, BILLING_FREQUENCY
	, BOOKINGS_DATE
	, BOOKING_STAMP
	, C1_PARTNER
	, C2_STAGE
	, C2_TYPE
	, CAMPAIGN_ID
	, CLOSE_BOOKINGS_DATE
	, CLOSED_REASON_CATEGORY
	, CLOSED_REASON_DETAILS
	, CLOSED_REASON_NOTES
	, CLOSED_REASON_SUBCATEGORY_LOSS
	, CREATED_DATE
	, CURRENCY
	, CURRENCY_CONVERSION_RATE
	, CURRENT_AVG_MRR_TOTAL
	, CUSTOMER_SUPPORT_ID
	, CUSTOMER_SUPPORT_NAME
	, DISCOUNT_RECAPTURE_MRR
	, DOWNSELL_CHURN_CATEGORY
	, DOWNSELL_CHURN_SUB_CATEGORY
	, END_DATE
	, ESTIMATED_CLOSE_DATE
	, EXPANSION_DOLLARS
	, FIRST_YEARS_BILLINGS
	, FISCAL_WEEK
	, FORECAST_CATEGORY
	, GEO
	, HIGHEST_ACHIEVED_STAGE
	, INBOUND_OUTBOUND_OPPORTUNITY
	, LAST_EDIT_DATE
	, LEAD_SOURCE
	, LEAD_SOURCE_DETAIL
	, MRR_SUB_END
	, MRR_SUB_START
	, NET_NEW_MRR
	, NEXT_STEP
	, NEXT_STEP_LAST_EDITED
	, NN_DISCOUNT_RECAPTURE_ACV
	, OPPORTUNITY_CHANNEL_SOURCE
	, OPPORTUNITY_NAME
	, OPPORTUNITY_URL
	, OPS_APPROVED
	, OWNER_GEO_STAMP
	, OWNER_ID
	, OWNER_NAME
	, OWNER_ROLE
	, PLATFORM
	, PRIMARY_COMPETITOR
	, PRIMARY_QUOTE_ID
	, PRODUCTS_OF_INTEREST
	, PROBABILITY
	, RAMPED_ACV
	, REGION
	, RENEWED_AMOUNT
	, RENEWAL_DOLLARS
	, RENEWAL_DUE
	, RENEWAL_DUE_DATE
	, RENEWAL_FORECAST_ARR
	, RENEWAL_UPLIFT
	, SALES_ENGINEER_NAME
	, SALES_MRR
	, SALES_OPPORTUNITY_ACCEPTED
	, SALES_OPPORTUNITY_ACCEPTED_DATE
	, SALESFORCE_ORG
	, SE_ID
	, SEGMENT
	, "STAGE"
	, STAGE_1_DATE_OF_ENTRY
	, START_DATE
	, SUB_TYPE
	, TCV_NON_RECURRING
	, TCV_SERVICES
	, TCV_SUBSCRIPTIONS
	, TERM_MONTHS
	, TERRITORY
	, TERRITORY_MANAGER_ID
	, TERRITORY_MANAGER_NAME
	, TM_SEGMENT_NAME
	, TOTAL_DEAL_VALUE
	, TOTAL_RENEWAL_DUE
	, TOTAL_UPSELL_DOWNSELL
	, "TYPE"
	, VALID_UNTIL_DATE
	, X15_DATE
	, XOPPORTUNITY_ID
	, OPPTY_MODSTAMP
	, ACCNT_MODSTAMP
	, LAST_MODSTAMP
FROM
	APTTUS_DW.SF_PRODUCTION."Opportunity_C2"
;


/*  old


INSERT INTO APTTUS_DW.SNAPSHOTS.OPPORTUNITY_C2_WEEKLY_HISTORY  
SELECT CRM_SOURCE, 
       OPPORTUNITY_ID, 
       to_Date('2020-10-03') AS SNAPSHOT_DATE,
       A1_PARTNER, 
       ACCOUNT_ID, 
       ACCOUNT_NAME, 
       ACCOUNT_OWNER_NAME, 
       ACCOUNT_URL, 
       ANNUAL_RENEWAL, 
       ARR, 
       AGE_DAYS, 
       AGE_MONTHS, 
       AVERAGE_ACV, 
       BILLING_FREQUENCY, 
       BOOKINGS_DATE, 
       BOOKING_STAMP, 
       C1_PARTNER, 
       C2_STAGE, 
       C2_TYPE, 
       CAMPAIGN_ID, 
       CLOSE_BOOKINGS_DATE, 
       CLOSED_REASON_CATEGORY, 
       CLOSED_REASON_DETAILS, 
       CLOSED_REASON_NOTES, 
       CLOSED_REASON_SUBCATEGORY_LOSS, 
       CREATED_DATE, 
       CURRENCY, 
       CURRENCY_CONVERSION_RATE, 
       CURRENT_AVG_MRR_TOTAL, 
       CUSTOMER_SUPPORT_ID, 
       CUSTOMER_SUPPORT_NAME, 
       DISCOUNT_RECAPTURE_MRR, 
       DOWNSELL_CHURN_CATEGORY, 
       DOWNSELL_CHURN_SUB_CATEGORY, 
       END_DATE, 
       ESTIMATED_CLOSE_DATE, 
       EXPANSION_DOLLARS, 
       FIRST_YEARS_BILLINGS, 
       FISCAL_WEEK, 
       FORECAST_CATEGORY, 
       GEO, 
       HIGHEST_ACHIEVED_STAGE, 
       INBOUND_OUTBOUND_OPPORTUNITY, 
       LAST_EDIT_DATE, 
       LEAD_SOURCE, 
       LEAD_SOURCE_DETAIL, 
       MRR_SUB_END, 
       MRR_SUB_START, 
       NET_NEW_MRR, 
       NEXT_STEP, 
       NEXT_STEP_LAST_EDITED, 
       NN_DISCOUNT_RECAPTURE_ACV, 
       OPPORTUNITY_CHANNEL_SOURCE, 
       OPPORTUNITY_NAME, 
       OPPORTUNITY_URL, 
       OPS_APPROVED, 
       OWNER_GEO_STAMP, 
       OWNER_ID, 
       OWNER_NAME, 
       OWNER_ROLE, 
       PLATFORM, 
       PRIMARY_COMPETITOR, 
       PRIMARY_QUOTE_ID, 
       PRODUCTS_OF_INTEREST, 
       PROBABILITY, 
       RAMPED_ACV, 
       REGION, 
       RENEWED_AMOUNT, 
       RENEWAL_DOLLARS, 
       RENEWAL_DUE, 
       RENEWAL_DUE_DATE, 
       RENEWAL_FORECAST_ARR, 
       RENEWAL_UPLIFT, 
       SALES_ENGINEER_NAME, 
       SALES_MRR, 
       SALES_OPPORTUNITY_ACCEPTED, 
       SALES_OPPORTUNITY_ACCEPTED_DATE, 
       SALESFORCE_ORG, 
       SE_ID, 
       SEGMENT, 
       STAGE, 
       STAGE_1_DATE_OF_ENTRY, 
       START_DATE, 
       SUB_TYPE, 
       TCV_NON_RECURRING, 
       TCV_SERVICES, 
       TCV_SUBSCRIPTIONS, 
       TERM_MONTHS, 
       TERRITORY, 
       TERRITORY_MANAGER_ID, 
       TERRITORY_MANAGER_NAME, 
       TM_SEGMENT_NAME, 
       TOTAL_DEAL_VALUE, 
       TOTAL_RENEWAL_DUE, 
       TOTAL_UPSELL_DOWNSELL, 
       TYPE, 
       VALID_UNTIL_DATE, 
       X15_DATE, 
       XOPPORTUNITY_ID, 
       '2020-10-03' As PeriodStartDate, 
       '2020-10-10' AS PeriodEndDate,
       dateclose."Fiscal Period"  AS "Close Fiscal Period",
       dateclose."Week (Quarter)" AS "Close Week (Quarter)",
       'FY21-Q3'                  AS "Snapshot Fiscal Period", 
       'Week 10'                  AS "Snapshot Week (Quarter)"
FROM                                "APTTUS_DW"."SF_PRODUCTION"."Opportunity_C2" O
INNER JOIN                          "APTTUS_DW"."SF_PRODUCTION"."Dates"          dateclose 
                 ON O.CLOSE_BOOKINGS_DATE = dateclose."Date"              
where CLOSE_BOOKINGS_DATE is null
   OR CLOSE_BOOKINGS_DATE > (current_Date() - 400)
;
*/ 

select * from "APTTUS_DW"."SF_PRODUCTION"."Opportunity_C2"
where LAST_MODSTAMP > (current_date() - 8)
--where CLOSE_BOOKINGS_DATE is null
--  OR CLOSE_BOOKINGS_DATE > (current_Date() - 400)
order by CREATED_DATE Asc
;

select * from "APTTUS_DW"."SF_PRODUCTION"."Opportunity_C2"
where ESTIMATED_CLOSE_DATE is null
;
